packages/examples/fortune/reputation-oracle/src/index.ts
packages/examples/fortune/reputation-oracle/src/services/s3.ts

In fortune reputation oracle saves the files locally before uploading them to s3 bucket, this fails in Vercel.
**Solution:** do not save files locally before uploading them to s3 bucket.

Remove saving files locally

---

packages/sdk/python/human_protocol_sdk/job.py
packages/sdk/python/setup.py

Use `bulk_paid` flag based on transaction receipt instead of checking `bulkPaid` flag inside contract.
Add debug logs.

Check bulk_paid flag based on transaction receipt.

---

.github/ISSUE_TEMPLATE/devs_feature_request.md

Create a simpler issue template for Human Protocol devs.

add devs feature request template

---

CONTRACTS_LIST.md

Create a list of deployed contracts
Add .md file containing a table of addresses
Nothing to test
Closes #133

add contracts list file

---

packages/apps/escrow-dashboard/src/components/SolvedTasks/index.tsx

Updated numbers of solved tasks till December

update solved tasks till December

---

.husky/pre-commit
packages/core/contracts/KVStore.sol
packages/core/package.json

Update KVStore contract, so that it can be used for subgraph.
Added `DataSaved` event emission, so that it can be used from subgraph.
Updated pre-commit script, so that it does not add unstaged files.

update KVStore contract

---

packages/apps/escrow-dashboard/src/components/SolvedTasks/index.tsx

Update the number of solved tasks in the escrow dashboard.
We should show the accumulated number of solved tasks till the December.

update escrow dashboard solved tasks

---

packages/core/contracts/Staking.sol
packages/core/package.json
packages/core/test/Staking.ts

Update `StakeSlashed` event interface.
Updated `StakeSlashed` event interface.
Before:
```
event StakeSlashed(
address indexed staker,
uint256 tokens
);
```
After:
```
event StakeSlashed(
address indexed staker,
uint256 tokens,
address indexed escrowAddress,
address slasher
);
```

fix staking contract slashed event fix

---

docs/Fortune-v1.md

Fortune functional document
Create .md file

add fortune v1 doc

---

.github/workflows/ci-lint.yaml
.github/workflows/ci-test-core.yaml
.github/workflows/ci-test-escrow-dashboard.yaml
.github/workflows/ci-test-fortune.yaml
.github/workflows/ci-test-node-sdk.yaml
.github/workflows/ci-test-python-sdk.yaml
.github/workflows/ci-test-subgraph.yaml
README.md

Update status badge.
Used specific branch & release for status badge on README.

Update status badge on README

---

packages/core/contracts/Escrow.sol
packages/core/contracts/interfaces/IEscrow.sol
packages/core/test/Escrow.ts
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/job.py
packages/sdk/typescript/human-protocol-sdk/src/job.ts

Rename fortunesRequested var in Escrow contract

Change fortune's name in protocol contracts

---

.github/workflows/cd-subgraph.yaml
CONTRACTS_LIST.md
packages/apps/escrow-dashboard/src/constants/index.ts
packages/examples/fortune/launcher/server/src/constants/networks.ts
packages/sdk/typescript/subgraph/config/goerli-v1.json
packages/sdk/typescript/subgraph/package.json

Deploy contracts from #87 feat/staking-slashing on Goerli testnet
Go to https://testnet.bscscan.com/ and check these contracts are verified
Staking Proxy Address:  0xf46B45Df3d956369726d8Bd93Ba33963Ab692920
Staking Implementation Address:  0x5e622FF522D81aa426f082bDD95210BC25fCA7Ed
Escrow Factory Proxy Address:  0x87469B4f2Fcf37cBd34E54244c0BD4Fa0603664c
Escrow Factory Implementation Address:  0x5D65C42cF4a140863744889BAd07f246C0211754
KVStore Address:  0xc9Fe39c4b6e1d7A2991355Af159956982DADf842
Reward Pool Proxy Address:  0x0376D26246Eb35FF4F9924cF13E6C05fd0bD7Fb4
Reward Pool Implementation Address:  0x6478312bE22FeE34a366d8e945d4dBd97388a306
Reputation Proxy Address:  0x6B220A6306D8D86C9878A1FBb3F49707b3E2b405
Reputation Implementation Address: …

Deploy contracts with proxies on Goerli

---

packages/apps/escrow-dashboard/src/constants/index.ts
packages/apps/escrow-dashboard/src/state/escrow/reducer.ts

Fixed escrow data loading issue.
1. Updated subgraph URL and factory address for some networks.
2. Added conditional check when there's no data in subgraphs.

fix constants, check stats

---

packages/apps/escrow-dashboard/src/components/SolvedTasks/index.tsx

Update solved tasks count till Jan 31, 2023
Updated static data for solved tasks count on front-end

update solved tasks till Jan 31

---

.github/workflows/cd-subgraph.yaml
CONTRACTS_LIST.md
packages/apps/escrow-dashboard/src/constants/index.ts
packages/core/README.md
packages/core/hardhat.config.ts
packages/core/scripts/deploy-proxies.ts
packages/examples/fortune/launcher/client/src/constants/index.ts
packages/examples/fortune/launcher/server/src/constants/networks.ts
packages/examples/fortune/reputation-oracle/src/constants/constants.ts
packages/sdk/typescript/subgraph/config/bsc-v1.json

Deploy contracts from #87 feat/staking-slashing on BSC
Go to https://bscscan.com/ and check these contracts are verified
Staking Proxy Address:  0x05398211bA2046E296fBc9a9D3EB49e3F15C3123
Staking Implementation Address:  0xC2163A0928034e020f0d31e1171Ba0D6d9AfFB6c
Escrow Factory Proxy Address:  0xD9c75a1Aa4237BB72a41E5E26bd8384f10c1f55a
Escrow Factory Implementation Address:  0xe44D7eb960f24797D36FAdD8a8FfF29C76375Ef0
KVStore Address:  0x70671167176C4934204B1C7e97F5e86695857ef2
Reward Pool Proxy Address:  0x4A5963Dd6792692e9147EdC7659936b96251917a
Reward Pool Implementation Address:  0x25E53A6D48A2744273C082e55bA5CCFCfD80f9e1

Deploy contracts with proxies on BSC

---

packages/examples/fortune/exchange/src/connectors/connectors.ts

Update WalletConnect config to use V2 modal instead of V1
Specify V2 into WalletConnect connector

Update WalletConnect modal to version 2

---

.github/workflows/cd-subgraph.yaml

Subgraphs CD is failing because doesn't find config files

Fix subgraphs cd

---

packages/apps/escrow-dashboard/src/state/escrow/hooks.ts

Chart bars should be ordered by date in desc order. This will close #223 
Fixed stacked bar chart with sorting

fix: chart date order

---

packages/apps/escrow-dashboard/src/constants/index.ts

Change bsc rpc because of cors error

BSC rpc down

---

.github/workflows/cd-subgraph.yaml

Update deploy subgraphs CD so it runs the workflow when the workflow itself is modified

deploy subgraphs when cd workflow is modified

---

package.json
packages/apps/escrow-dashboard/package.json
packages/examples/eth-kvstore-gui/package.json
packages/examples/fortune/exchange/package.json
yarn.lock

Fix wagmi dependency

---

packages/core/contracts/Escrow.sol
packages/core/contracts/interfaces/IEscrow.sol
packages/core/package.json
packages/core/test/Escrow.ts
packages/examples/fortune/recording-oracle/src/plugins/escrow.ts
packages/examples/fortune/recording-oracle/src/services/recordingOracle.ts
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/job.py
packages/sdk/typescript/human-protocol-sdk/src/job.ts
packages/sdk/typescript/subgraph/schema.graphql
packages/sdk/typescript/subgraph/src/mapping/Escrow.ts
packages/sdk/typescript/subgraph/template.yaml
packages/sdk/typescript/subgraph/tests/escrow/escrow.test.ts
packages/sdk/typescript/subgraph/tests/escrow/fixtures.ts
yarn.lock

Provide user/address statistics and data:
- Number of escrows solved
- Grants amount
- Escrows solved paid

Add workers data to track info with The Graph

---

packages/sdk/python/human-protocol-basemodels/Makefile

fix base models publish

---

packages/examples/fortune/reputation-oracle/src/services/rewards.ts

Check if address exist on workers array to avoid duplicate entries when calculating the rewards for each worker

Check if address exist on workers array to avoid duplicate entries

---

packages/examples/fortune/launcher/client/src/App.tsx
packages/examples/fortune/launcher/client/src/components/FiatJobRequest.tsx
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/job.py

The provider used in the fiat payment section is received from Wagmi, but we are not using any wallet, so we need to set it up manually
Change Wagmi provider to one configured with the JSON-RPC URL of the selected network

Change the provider of the fiat section

---

packages/examples/cvat/exchange-oracle/.gitignore
packages/examples/cvat/exchange-oracle/README.md
packages/examples/cvat/exchange-oracle/alembic/env.py
packages/examples/cvat/exchange-oracle/docker-compose.test.yml
packages/examples/cvat/exchange-oracle/poetry.lock
packages/examples/cvat/exchange-oracle/pyproject.toml
packages/examples/cvat/exchange-oracle/src/db/base.py
packages/examples/cvat/exchange-oracle/src/db/base_class.py
packages/examples/cvat/exchange-oracle/src/db/deps.py
packages/examples/cvat/exchange-oracle/src/db/session.py
packages/examples/cvat/exchange-oracle/src/modules/webhook/api.py
packages/examples/cvat/exchange-oracle/src/modules/webhook/model.py
packages/examples/cvat/exchange-oracle/tests/api/test_webhook.py
packages/examples/cvat/exchange-oracle/tests/config.py
packages/examples/cvat/exchange-oracle/tests/conftest.py
packages/examples/cvat/exchange-oracle/tests/utils/overrides.py
packages/examples/cvat/exchange-oracle/tests/utils/test_db.py

Pytest is added as a testing tool
Implementing tests
Changed DB initialization.
Added pytest as a testing tool.
#250 Subtask #3

Added pytest

---

packages/apps/escrow-dashboard/src/components/Header.tsx

Update header home button text from Scan to Dashboard.
This will close #293

dashboard - update home button text

---

packages/examples/fortune/launcher/client/src/__tests__/FiatJobRequest.test.tsx
packages/examples/fortune/launcher/client/src/__tests__/FundingMethod.test.tsx
packages/examples/fortune/launcher/client/src/__tests__/LaunchFail.test.tsx
packages/examples/fortune/launcher/server/src/plugins/stripe.ts
packages/examples/fortune/launcher/server/tests/plugins/escrow.test.ts
packages/examples/fortune/launcher/server/tests/plugins/stripe.test.ts

Add stripe testing on launcher back and front

---

packages/examples/cvat/exchange-oracle/alembic/versions/b819f6138bca_create_webhook_model.py
packages/examples/cvat/exchange-oracle/src/api.py
packages/examples/cvat/exchange-oracle/src/api_schema.py
packages/examples/cvat/exchange-oracle/src/config.py
packages/examples/cvat/exchange-oracle/src/db/base_class.py
packages/examples/cvat/exchange-oracle/src/modules/webhook/api.py
packages/examples/cvat/exchange-oracle/src/modules/webhook/api_schema.py
packages/examples/cvat/exchange-oracle/src/modules/webhook/constants.py
packages/examples/cvat/exchange-oracle/src/modules/webhook/model.py
packages/examples/cvat/exchange-oracle/tests/api/test_greet.py
packages/examples/cvat/exchange-oracle/tests/api/test_webhook.py

Multiple networks support added
`s3_url` is removed from incoming webhook API schema
#250 Subtask 4

Multiple networks support added

---

packages/core/README.md
packages/core/package.json
packages/core/scripts/upgrade-proxy.ts

Update readme with upgrade proxy info

Update readme with upgrade proxy info

---

.github/workflows/cd-deploy-contracts.yaml

Add path to restrict CD startup only when introducing changes to packages/core.

Add path into contracts CD

---

CONTRACTS_LIST.md
CONTRIBUTORS.md
packages/apps/escrow-dashboard/src/components/Faucet/FaucetView.tsx
packages/apps/escrow-dashboard/src/components/Faucet/RequestData.tsx
packages/apps/escrow-dashboard/src/components/Faucet/Success.tsx
packages/apps/escrow-dashboard/src/constants/index.ts
packages/apps/faucet-server/package.json
packages/apps/faucet-server/src/constants/networks.ts
packages/apps/faucet-server/src/index.ts
packages/apps/faucet-server/src/services/web3.ts
packages/core/hardhat.config.ts
packages/examples/fortune/exchange/src/connectors/chains.ts
packages/examples/fortune/exchange/src/connectors/connectors.ts
packages/examples/fortune/launcher/client/src/index.tsx
packages/examples/fortune/recording-oracle/src/constants/networks.ts
packages/sdk/typescript/subgraph/config/skale.json
packages/sdk/typescript/subgraph/package.json
packages/sdk/typescript/subgraph/template.yaml
yarn.lock

Hey guys,
Added reward pool to subgraph generation file
Fixed subgraph generation with no grafting
Add SKALE to fortune app

Add SKALE params

---

.github/workflows/cd-deploy-contracts.yaml
CONTRACTS_LIST.md
packages/apps/escrow-dashboard/src/constants/index.ts
packages/apps/faucet-server/src/constants/networks.ts
packages/core/.openzeppelin/unknown-1287.json
packages/examples/fortune/launcher/server/src/constants/networks.ts
packages/examples/fortune/recording-oracle/src/constants/networks.ts
packages/examples/fortune/reputation-oracle/src/constants/constants.ts
packages/sdk/typescript/subgraph/config/moonbase-alpha-v1.json

Redeploy contracts because maintainer lost the private key owner of the token. We have to deploy a new token and also the other contracts because the existing ones reference the old token
Update addresses

Redeploy Moonbase Alpha contracts

---

packages/examples/fortune-v2/job-launcher/server/package.json
packages/examples/fortune-v2/job-launcher/server/src/common/helpers/encryption.ts
packages/examples/fortune-v2/job-launcher/server/src/common/helpers/index.ts
packages/examples/fortune-v2/job-launcher/server/src/common/helpers/json.ts
packages/examples/fortune-v2/job-launcher/server/src/common/interfaces/encryption.ts
packages/examples/fortune-v2/job-launcher/server/src/index.ts
yarn.lock

Algorithm for signing, encrypting and decrypting messages at all levels of escrow processing.
The algorithm includes the implementation of the [PGP encryption algorithm](https://github.com/openpgpjs/openpgpjs) multi-public key encryption on typescript.
The algorithm for signing, encrypting and decrypting include several methods:
- encrypt(..)
- decrypt(..)
- sign(..)
- verify(..)
Used the vanilla [ed25519](https://en.wikipedia.org/wiki/EdDSA#Ed25519) implementation Schnorr signatures for signature and [curve25519](https://en.wikipedia.org/wiki/Curve25519) for encryption. [Learn more](https://wiki.polkadot.network/docs/learn-cryptography). 
Implemented encryption module.
`
const keyPair = await generateKeyPair()
const keyPair_1 = {
mnemonic: configService.get<string>("MNEMONIC", …

Implemented encryption module

---

packages/apps/escrow-dashboard/src/components/Leaderboard/LeaderboardView.tsx
packages/apps/escrow-dashboard/src/state/leader/reducer.ts
packages/apps/escrow-dashboard/src/utils/index.ts

Resolve comments from vercel deployment.
- Format wei amounts
- Remove unstaked users from the leaderboard table
- Fix copy address button
- Fix filtering by networks and roles

fix vercel comments on dashboard

---

CONTRIBUTING.MD
packages/apps/escrow-dashboard/src/components/App/App.tsx
packages/examples/fortune/exchange/package.json
packages/examples/fortune/launcher/client/src/index.tsx
yarn.lock

The goal is to set up a few rules on how to interact with this repository to keep history clean and clear.
Updated `CONTRIBUTING.MD` file.
In order to fulfill requirements presented in the updated file, I propose the following:
1. Create a `develop` branch which should be stable and reflect the current state of development. `main` branch must be stable and production-ready.
2. PR to the `main` branch could be only from a `develop` branch.

Update CONTRIBUTING.MD file

---

packages/apps/escrow-dashboard/src/components/Header/Header.tsx

Added a warning message at the top of dashboard.

add warning on escrow dashboard

---

.gitignore
packages/examples/fortune-v2/LICENSE
packages/examples/fortune-v2/docker-compose.yml
packages/examples/fortune-v2/package.json

Add Minio and Postgres services into docker compose to launch everything with a single command

Fortune V2 - Minio and Postgres services

---

.github/workflows/ci-dependency-review.yaml
package.json
packages/apps/faucet-server/package.json
packages/apps/faucet-server/src/index.ts
yarn.lock

Fix security issues / setup new workflows.
- Fixed security issues.
- Added `rate limit` to the faucet server, as code scanning suggested. We may need to adjust limit parameters.
- Setup new workflows.
- Added `dependency-review` workflow for dependency alerts within the PR.

Monorepo Cleanup

---

packages/apps/escrow-dashboard/src/constants/index.ts

add mainnet wagmi config

---

packages/examples/fortune/exchange-oracle/server/index.ts
packages/examples/fortune/exchange-oracle/server/package.json
packages/examples/fortune/exchange-oracle/server/vercel.json

Config ex oracle server to be deployed on vercel and update functionality
Add vercel config
Update get jobs endpoint
Run locally and go to http://localhost:3000/jobs?workeraddress=0x0376D26246Eb35FF4F9924cF13E6C05fd0bD7Fb6

Ex oracle server - vercel deployment and updates

---

packages/examples/fortune/exchange-oracle/server/vercel.json

Fix cors origin for exchange oracle server
Update vercel config to include cors origin header

Fix cors origin for exchange oracle server

---

packages/core/contracts/Escrow.sol

Remove unnecessary import of IRewardPool in Escrow contract
Remove import
Core CI

Escrow contract

---

packages/sdk/typescript/human-protocol-sdk/src/kvstore.ts

Add a decorator to check if ethers object has a Signer
Add a decorator on KVStoreClient

Typescript KVStore SDK

---

packages/examples/fortune/launcher/client/index.html
packages/examples/fortune/launcher/client/src/components/FiatJobRequest.tsx
packages/examples/fortune/launcher/client/src/components/Header.tsx
packages/examples/fortune/launcher/client/src/components/JobRequest.tsx
packages/examples/fortune/launcher/client/src/constants/index.ts
packages/examples/fortune/launcher/client/src/theme.ts

Improve UI/UX elements from the last feedback.
- Update Fiat Funds elements
- Update Network selector highlight color
- Update MuiSelect icon color
- Update header title
- Remove header box shadow

improve UI elements on job launcher

---

packages/core/contracts/Escrow.sol
packages/core/test/Escrow.ts

Use `trusted` modifier in `complete` function of `Escrow` contract.
Closes #457

use trusted modifier in complete function

---

.github/workflows/cd-deploy-contracts.yaml
packages/core/scripts/upgrade-proxies.ts

Add env variables in script for upgrade proxies, to check if each contract should be upgraded or not based on the inputs of the workflow
Update deployment script and workflow
Needs to be tested manually

Add env variables in script for upgrade

---

.github/workflows/cd-deploy-contracts.yaml
packages/core/scripts/upgrade-proxies.ts

Merge develop to main

---

CONTRACTS_LIST.md
packages/core/.openzeppelin/goerli.json
packages/core/.openzeppelin/polygon-mumbai.json
packages/sdk/typescript/subgraph/config/goerli-v1.json
packages/sdk/typescript/subgraph/config/mumbai-v1.json

modify addresses of upgraded contracts
Update addresses 
Update blocks for subgraph

modify addresses of upgraded contracts

---

packages/sdk/python/human-protocol-sdk/Pipfile
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/constants.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/kvstore.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/staking.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/utils.py
packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_escrow.py
packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_kvstore.py
packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_staking.py

Develop the Escrow SDK
- Create EscrowClient class
- Create create_escrow method
- Create setup method
- Create create_and_setup_escrow method
- Create fund method
- Create store_results method
- Create complete method
- Create bulk_payout method
- Create cancel method
- Create abort method
- Create add_trusted_handlers method
- Create get_balance method
- Create get_manifest_url method
- Create get_results_url method
- Create get_token_address method
- Create get_status method
Run make run-test inside python SDK folder
#443

Python Escrow SDK

---

packages/sdk/typescript/human-protocol-sdk/src/decorators.ts
packages/sdk/typescript/human-protocol-sdk/src/kvstore.ts
packages/sdk/typescript/human-protocol-sdk/src/staking.ts

Fix compilation error of requiresSigner decorator and make it common for all modules
Add a new file with the decorator code and call it in every method that writes to blockchain
Run the typescript SDK tests

Typescript requireSigner decorator

---

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/staking.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/utils.py

Use ERC20 token interface for escrow fund operations.
Closes #472

use erc20 token interface for escrow python sdk

---

.github/workflows/cd-deploy-contracts.yaml

release 20230522 (#491)

---

.github/workflows/cd-deploy-contracts.yaml
packages/core/.openzeppelin/goerli.json
packages/core/.openzeppelin/polygon-mumbai.json
packages/core/scripts/upgrade-proxies.ts
packages/sdk/typescript/subgraph/config/bsctest-v1.json
packages/sdk/typescript/subgraph/config/goerli-v1.json
packages/sdk/typescript/subgraph/config/moonbase-alpha-v1.json
packages/sdk/typescript/subgraph/config/mumbai-v1.json

Update history files after deployment failed

update upgrades history and remove reputation

---

packages/examples/fortune/exchange-oracle/client/package.json
packages/examples/fortune/launcher/client/package.json

Fix fortune ports
Modify start command for job launcher and exchange oracle clients

Fix fortune ports

---

.github/workflows/cd-deploy-contracts.yaml
packages/core/.openzeppelin/polygon-mumbai.json
packages/core/contracts/RewardPool.sol
packages/core/contracts/interfaces/IRewardPool.sol

Fix incompatibility error in addReward event and improve contracts CD so in case of error still execute some steps
Update RewardPool contract
Update contracts CD

Fix addReward event and improve contracts CD

---

.github/workflows/cd-deploy-contracts.yaml
packages/core/.openzeppelin/polygon-mumbai.json
packages/core/contracts/RewardPool.sol
packages/core/contracts/interfaces/IRewardPool.sol

fix addReward event and improve contracts CD (#507)

---

packages/examples/cvat/exchange-oracle/src/modules/cvat/model.py
packages/examples/cvat/exchange-oracle/src/modules/cvat/service.py
packages/examples/cvat/exchange-oracle/src/modules/webhook/service.py
packages/examples/cvat/exchange-oracle/tests/integration/test_cvat_service.py
packages/examples/cvat/exchange-oracle/tests/integration/test_webhook_service.py

Add integration tests to test the database
Add tests for Webhook service and CVAT service

CVAT Exchange Oracle integration tests

---

packages/examples/fortune/launcher/client/src/constants/index.ts

Enable networks fortune

---

packages/sdk/typescript/human-protocol-sdk/src/escrow.ts
packages/sdk/typescript/human-protocol-sdk/src/staking.ts
packages/sdk/typescript/human-protocol-sdk/src/storage.ts
packages/sdk/typescript/human-protocol-sdk/test/escrow.test.ts
packages/sdk/typescript/human-protocol-sdk/test/init.test.ts
packages/sdk/typescript/human-protocol-sdk/test/staking.test.ts

Fix Node.js SDK
Fix Lint & tsc build issues.

fix node.js sdk lint

---

packages/apps/escrow-dashboard/src/components/SolvedTasks/SolvedTasksContainer.tsx

Solved tasks numbers are outdated, need to update with new numbers.
Made changes to solved tasks numbers till April.

[Escrow-dashboard] Fix solved tasks

---

packages/examples/cvat/exchange-oracle/src/modules/cvat/job_creation.py
packages/examples/cvat/exchange-oracle/src/modules/webhook/api.py
packages/examples/cvat/exchange-oracle/src/modules/webhook/process_pending.py
packages/examples/cvat/exchange-oracle/src/utils/escrow.py
packages/examples/cvat/exchange-oracle/src/utils/helpers.py

Added a few TODOs, minor naming changes. Code regrouped to avoid merge conflicts in the future.

Prepare code for integrating `human-protocol-sdk`

---

.github/workflows/cd-python-sdk.yaml
packages/sdk/python/human-protocol-sdk/.gitignore
packages/sdk/python/human-protocol-sdk/MANIFEST.in
packages/sdk/python/human-protocol-sdk/Makefile
packages/sdk/python/human-protocol-sdk/Pipfile
packages/sdk/python/human-protocol-sdk/setup.py
packages/sdk/typescript/human-protocol-sdk/package.json
packages/sdk/typescript/human-protocol-sdk/src/constants.ts
packages/sdk/typescript/human-protocol-sdk/src/escrow.ts
packages/sdk/typescript/human-protocol-sdk/test/escrow.test.ts
packages/sdk/typescript/human-protocol-sdk/tsconfig.json
yarn.lock

Node.js and Python SDK for release
- Fixed `createEscrow` function of Node.js SDK
- Fixed wrong network config for local hardhat environment.
- Fixed dependencies of Node.js SDK
- Updated Python SDK dependency and setuptools

fix: node and python sdk for release

---

packages/apps/escrow-dashboard/src/components/Header/Header.tsx
packages/apps/escrow-dashboard/src/components/SolvedTasks/SolvedTasksContainer.tsx

Fix solved tasks numbers on dashboard
- Update solved tasks numbers
- Hide My HMT button for now

[Escrow Dashboard] patch solved tasks numbers

---

packages/apps/escrow-dashboard/src/components/Escrow/EscrowContainer.tsx
packages/apps/escrow-dashboard/src/components/TimeRangeButtons/index.tsx
packages/apps/escrow-dashboard/src/state/escrow/hooks.ts
packages/apps/escrow-dashboard/src/state/escrow/reducer.ts

Added the time range selector for escrow section
Here's figma link - https://www.figma.com/file/u81GKebVavmQW8zGHb5Jgo/Dashboards---Everything-Apps?type=design&node-id=2846-46820&t=Cc1IpKHyiiZYIyOS-0

add time range selector on escrow-dashboard

---

packages/apps/escrow-dashboard/src/components/SolvedTasks/SolvedTasksContainer.tsx
packages/apps/escrow-dashboard/src/constants/index.ts
packages/apps/escrow-dashboard/src/pages/Main/Main.tsx

- Fixed `taskSvg` issue
- Fixed BSC testnet RPC url

fix build issues on escrow-dashboard

---

.github/workflows/ci-mx-contracts.yaml
.github/workflows/ci-test-core.yaml
.github/workflows/ci-test-escrow-dashboard.yaml
.github/workflows/ci-test-faucet-server.yaml
.github/workflows/ci-test-fortune-v2.yaml
.github/workflows/ci-test-fortune.yaml
.github/workflows/ci-test-meta-code-verify.yml
.github/workflows/ci-test-node-basemodels.yaml
.github/workflows/ci-test-node-sdk.yaml
.github/workflows/ci-test-python-basemodels.yaml
.github/workflows/ci-test-python-sdk.yaml
.github/workflows/ci-test-subgraph.yaml

Updated couple Github CI workflows. We don't necessarily need to run fortune v2 CI tests for fortune changes, for example.
- Added paths for each Github CI to be run upon changes.
Closes #559

Feat: Update CI workflows to be run on changes.

---

packages/core/README.md
packages/core/contracts/EscrowFactory.sol

Core smart contracts clean up.
- Removed unused `isChild` function from `EscrowFactory`.
- Added functional documentation for core contracts.
Closes #560

remove unused isChild function and update doc

---

packages/apps/fortune/docker-compose.yml
packages/apps/fortune/recording-oracle/jest.config.js
packages/apps/fortune/recording-oracle/package.json
packages/apps/fortune/recording-oracle/src/common/config/ethereum.config.ts
packages/apps/fortune/recording-oracle/src/common/constants/index.ts
packages/apps/fortune/recording-oracle/src/common/constants/network.ts
packages/apps/fortune/recording-oracle/src/modules/job/job.controller.spec.ts
packages/apps/fortune/recording-oracle/src/modules/job/job.module.ts
packages/apps/fortune/recording-oracle/src/modules/job/job.service.spec.ts
packages/apps/fortune/recording-oracle/src/modules/job/job.service.ts
packages/apps/fortune/recording-oracle/src/modules/web3/web3.module.ts
packages/apps/fortune/recording-oracle/src/modules/web3/web3.service.spec.ts
packages/apps/fortune/recording-oracle/src/modules/web3/web3.service.ts
yarn.lock

Recording Oracle should support multiple chains, for the given chain id in the request payload.
- Removed JSON RPC Url from Recording Oracle deployment configuration.
- Added web3 service, which creates signers for different chain.
Closes #584

Fortune: Recording Oracle Multi Chain Support

---

packages/examples/cvat/exchange-oracle/alembic/versions/dc10ddee57c9_initial_migration.py
packages/examples/cvat/exchange-oracle/src/config.py
packages/examples/cvat/exchange-oracle/src/modules/cvat/api_calls.py
packages/examples/cvat/exchange-oracle/src/modules/cvat/format_annotations.py
packages/examples/cvat/exchange-oracle/src/modules/cvat/job_creation.py
packages/examples/cvat/exchange-oracle/src/modules/cvat/model.py
packages/examples/cvat/exchange-oracle/src/modules/cvat/revert_job_creation.py
packages/examples/cvat/exchange-oracle/src/modules/cvat/service.py
packages/examples/cvat/exchange-oracle/src/modules/oracle_webhooks/model.py
packages/examples/cvat/exchange-oracle/src/modules/oracle_webhooks/process_pending.py
packages/examples/cvat/exchange-oracle/src/modules/oracle_webhooks/service.py
packages/examples/cvat/exchange-oracle/tests/integration/service/test_cvat_service.py
packages/examples/cvat/exchange-oracle/tests/integration/service/test_webhook_service.py
packages/examples/cvat/exchange-oracle/tests/unit/helpers/predefined_annotations.py
packages/examples/cvat/exchange-oracle/tests/unit/helpers/test_format_annotations.py
packages/examples/cvat/exchange-oracle/tests/utils.py

Revert job creation on CVAT in case of an error.
Added job reverting process in case of an error during webhook processing.
Added max retry policy for webhooks.
Added unit and integration tests.
To close #607

Revert job creation on CVAT in case of an error.

---

packages/sdk/typescript/human-protocol-sdk/src/encryption.ts
packages/sdk/typescript/human-protocol-sdk/src/interfaces.ts
packages/sdk/typescript/human-protocol-sdk/test/encryption.test.ts

Develop encryption module in typescript SDK.
Encryption:
- encrypt
- decrypt
- sign
EncryptionUtils:
- generateKeyPair
- verify
- getSignedData
`yarn test test/encryption.test.ts`
Close #435

Add typescript encryption module

---

README.md
packages/sdk/typescript/human-protocol-sdk/README.md

Documentation updates
- Updated README of monorepo.
- Updated README of ts sdk.
Closes #624

update doc for monorepo and sdk

---

packages/examples/cvat/exchange-oracle/src/modules/chain/web3.py
packages/examples/cvat/exchange-oracle/src/modules/cvat/jobs/retrieve_annotations.py
packages/examples/cvat/exchange-oracle/src/modules/oracle_webhook/helpers.py

Added `construct_sign_and_send_raw_middleware`  to be able to interact with escrow using public provider (e.g. Infura)

Added `construct_sign_and_send_raw_middleware` 

---

packages/sdk/python/human-protocol-sdk/README.md
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/utils.py
packages/sdk/python/human-protocol-sdk/test/e2e/test_staking.py
packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_escrow.py
packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_kvstore.py
packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_staking.py

`construct_sign_and_send_raw_middleware` middleware for Python SDK 
- Added `construct_sign_and_send_raw_middleware` check.
- Updated Python SDK doc.
Closes #633

add sign and send raw middleware check and update doc for python sdk

---

packages/examples/fortune/README.md

Update fortune urls with domain humanprotocol.org
Update readme

update fortune urls

---

packages/apps/job-launcher/server/src/common/enums/job.ts
packages/apps/job-launcher/server/src/modules/job/job.dto.ts
packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/legacy_encryption.py
packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_encryption.py

Deprecated [JobMode enum type](https://github.com/humanprotocol/human-protocol/blob/0dc320f95b5d96227e198c9fe3e620a3c548c9d2/packages/apps/job-launcher/server/src/modules/job/job.dto.ts#L159) and related data because It is no longer up to date and used.
- Removed JobMode enum type
- Updated manifest 
- Updated tests
`yarn test`
[[Job Launcher] - Deprecate JobMode enum type and related data#684](https://github.com/humanprotocol/human-protocol/issues/684)

[Job Launcher] Removed job mode type

---

packages/apps/job-launcher/server/src/database/migrations/1677867985970-addAuthTable.ts

Added deletion of status in auth migration when reverting migration.

Added auth status to revert migration script

---

packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts

Manual tested and made some edits.
`POST /job/solve`
`{
"escrowAddress": "0x024CE36A2225D3Bbd3c84b4CC5f62e614eE270EF",
"chainId": 80001,
"workerAddress": "0x5A608C0eac2418c4EcE696A23a9d8D8BcAC818f6",
"solution": "Hello"
}`
[End-to-end testing of protocol services#708](https://github.com/humanprotocol/human-protocol/issues/708)

[Exchange oracle] Updates for job service

---

packages/apps/job-launcher/server/src/modules/job/job.service.ts
packages/apps/job-launcher/server/src/modules/payment/currency.service.ts
packages/apps/reputation-oracle/server/src/common/interfaces/manifest.ts
packages/apps/reputation-oracle/server/src/modules/reputation/reputation.controller.spec.ts
packages/apps/reputation-oracle/server/src/modules/reputation/reputation.repository.ts
packages/apps/reputation-oracle/server/src/modules/reputation/reputation.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/reputation/reputation.service.ts
packages/apps/reputation-oracle/server/src/modules/webhook/webhook.cron.ts
packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
packages/apps/reputation-oracle/server/test/constants.ts

It is required to organize proper manual testing and update the [documentation](https://www.notion.so/human-protocol/Reputation-Oracle-9c56f7fbc52e4f62a7c443878cd576d8).
`POST /webhook`
[[Reputation Oracle] - Proper testing and documentation updates#671](https://github.com/humanprotocol/human-protocol/issues/671)

[Reputation oracle] Updates

---

packages/apps/fortune/recording-oracle/src/modules/job/job.service.ts

Fortune/Recording Oracle has lint errors.
- Fixed lint errors

Fix lint error

---

packages/apps/fortune/recording-oracle/src/common/constants/errors.ts
packages/apps/fortune/recording-oracle/src/modules/job/job.dto.ts
packages/apps/fortune/recording-oracle/src/modules/job/job.service.spec.ts
packages/apps/fortune/recording-oracle/src/modules/job/job.service.ts

Added a check that the worker only submits a solution by fortune.
- Added validation
- Added unit test
- Updated error mesages and implement error job enum
`yarn test`
[Recording Oracle - Fortune - Only one solution by worker in fortune#705](https://github.com/humanprotocol/human-protocol/issues/705)

[Recording Oracle] Job type validation

---

packages/examples/cvat/recording-oracle/bin/start_dev.sh

Fixed `start_dev.sh` script
Added `alembic upgrade head` command to `start_dev.sh` script

[CVAT][Recording Oracle] Added `alembic upgrade head` command to `start_dev.sh` script

---

.github/workflows/ci-test-cvat-eo.yaml

Fix `ci-test-cvat-eo.yaml`
Fixed path in `ci-test-cvat-eo.yaml` action
`ci-test-cvat.yaml` renamed to `ci-test-cvat-eo.yaml`

Fixed path in `ci-test-cvat-eo.yaml` action

---

packages/apps/escrow-dashboard/src/components/SolvedTasks/NewsView.tsx
packages/apps/escrow-dashboard/src/components/SolvedTasks/SolvedTasksView.tsx

Updated the `Solved Tasks` section in the escrow dashboard.
- Added `QoQ Growth` value.
- Used the area chart for solved tasks instead of the bar chart.

use area chart for solved tasks in escrow dashboard

---

packages/apps/job-launcher/server/src/modules/payment/payment.service.spec.ts
packages/apps/job-launcher/server/src/modules/payment/payment.service.ts

Fix balance calculation, only succeeded payments have to be considered for the balance calculation
Filter payments by status and fix tests
yarn test

fix balance calculation and tests

---

.github/workflows/cd-subgraph.yaml

Allow manual workflow trigger for subgraph deployment

allow manual subgraph deployment

---

packages/apps/fortune/recording-oracle/src/modules/job/job.service.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts
packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
packages/sdk/typescript/human-protocol-sdk/src/storage.ts
packages/sdk/typescript/human-protocol-sdk/test/storage.test.ts

Add nullable credentials in storage SDK
Add nullable credentials in storage SDK and update tests
`yarn test`

[SDK] Nullable credentials

---

packages/apps/job-launcher/server/src/modules/job/job.service.ts

Fix build error of Job Launcher

Job Launcher - fix build error

---

packages/apps/fortune/recording-oracle/src/modules/job/job.service.ts
packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts
packages/apps/job-launcher/server/test/constants.ts

Fix job bounties calculations to be precise with on chain calculations
Modify calculations using BigNumber
`yarn test`

[Job Launcher] Job bounties

---

packages/apps/job-launcher/server/src/modules/job/job.controller.ts

Job Launcher - fix cron job route

---

packages/apps/job-launcher/server/src/modules/job/job.controller.ts

Make a constant path relative
Make a constant path relative

[Job Launcher] Make a constant path relative

---

packages/apps/escrow-dashboard/src/components/Cards/Charts/BarChart.tsx
packages/apps/escrow-dashboard/src/components/Cards/Charts/StackedBarChart.tsx

Fixed the current UI bug on Ethereum network.
Make nullable `date` property access.

fix escrow dashboard charts

---

packages/sdk/typescript/human-protocol-sdk/example/escrow.ts
packages/sdk/typescript/human-protocol-sdk/src/escrow.ts
packages/sdk/typescript/human-protocol-sdk/src/interfaces.ts

- Fixed `getEscrows` function to accept `EscrowStatus` enum value in filter.
Closes #862

fix: [SDK] getEscrows function

---

packages/apps/job-launcher/server/src/common/enums/job.ts
packages/apps/job-launcher/server/src/common/enums/webhook.ts
packages/apps/job-launcher/server/src/modules/job/job.dto.ts
packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts

- Remove IMAGE_LABEL_BINARY type of task
- Add `user_guide` to job creation for CVAT
- Update `event_type`
`yarn test`
[[Job Launcher] Hide IMAGE_LABEL_BINARY job type#882](https://github.com/humanprotocol/human-protocol/issues/882)

[Job Launcher] Added minor improvements

---

.github/workflows/cd-deploy-contracts.yaml
packages/core/.openzeppelin/polygon-mumbai.json

Need to commit changes in upgrade history file

Fix deploy contracts

---

packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.spec.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts
packages/sdk/python/human-protocol-sdk/example.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py
packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_escrow.py
packages/sdk/typescript/human-protocol-sdk/example/escrow.ts
packages/sdk/typescript/human-protocol-sdk/src/escrow.ts
packages/sdk/typescript/human-protocol-sdk/src/graphql/types.ts
packages/sdk/typescript/human-protocol-sdk/src/index.ts
packages/sdk/typescript/human-protocol-sdk/src/interfaces.ts
packages/sdk/typescript/human-protocol-sdk/test/escrow.test.ts

Add network array to getEscrows filter to retrieve information from all networks
`yarn test` for Typescript and `make run-test` for Python

[SDK][Typescript][Python] Add network array to getEscrows filter

---

packages/apps/job-launcher/server/src/main.ts

Fix nest configuration on Job Launcher to work with the new `@nestjs/platform-express` version 10.2.6
Update `NestExpressApplication` to `INestApplication`

[Job Launcher] Fix nest configuration

---

packages/apps/escrow-dashboard/vercel.json
packages/apps/faucet-server/vercel.json
packages/apps/job-launcher/client/vercel.json
packages/apps/job-launcher/server/vercel.json
packages/examples/fortune/exchange-oracle/client/vercel.json
packages/examples/fortune/exchange-oracle/server/vercel.json
packages/examples/fortune/launcher/server/vercel.json
packages/examples/fortune/recording-oracle/vercel.json
packages/examples/fortune/reputation-oracle/vercel.json

Added git ignore command to make sure it's only triggering vercel deployment on relevant change.
Closes #938

[CI/CD] Vercel Configuration

---

packages/apps/escrow-dashboard/vercel.json
packages/examples/fortune/launcher/client/vercel.json

fix vercel config

---

packages/sdk/python/human-protocol-sdk/example.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/filter.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/escrow.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/payout.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/statistics.py
packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_escrow.py
packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_statistics.py
packages/sdk/typescript/human-protocol-sdk/example/statistics.ts
packages/sdk/typescript/human-protocol-sdk/src/graphql/queries/index.ts
packages/sdk/typescript/human-protocol-sdk/src/graphql/queries/payout.ts
packages/sdk/typescript/human-protocol-sdk/src/graphql/types.ts
packages/sdk/typescript/human-protocol-sdk/src/interfaces.ts
packages/sdk/typescript/human-protocol-sdk/src/statistics.ts
packages/sdk/typescript/human-protocol-sdk/test/statistics.test.ts

We need to add tasks statistics data, and fix workers statistics data from SDK.
- Calculate tasks statistics data from IM API.
- Fix workers statistics data by calculating different payout recipients.
Closes #970

[SDK] fix: statistics client for tasks and workers 

---

packages/apps/job-launcher/server/src/modules/payment/payment.controller.ts

Job Launcher - fix route of import

---

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/utils.py

Improve error logging for failed transaction
Add error logging to handle_transaction

Add  handle transaction error logging

---

.github/workflows/cd-cvat-exchange-oracle.yaml
.github/workflows/cd-cvat-recording-oracle.yaml
.github/workflows/ci-lint.yaml
.github/workflows/ci-test-escrow-dashboard.yaml
.github/workflows/ci-test-faucet-server.yaml
.github/workflows/ci-test-fortune-v3.yaml
.github/workflows/ci-test-fortune.yaml
.github/workflows/ci-test-meta-code-verify.yaml
.github/workflows/ci-test-node-sdk.yaml
.github/workflows/ci-test-subgraph.yaml
package.json
packages/examples/fortune/exchange-oracle/client/src/App.test.tsx
packages/examples/fortune/exchange-oracle/client/src/connectors/connectors.ts
packages/examples/fortune/exchange-oracle/client/tests/utils.tsx
packages/sdk/typescript/human-protocol-sdk/src/storage.ts
yarn.lock

Clean up node dependencies, and make it up-to-date.
- Cleaned up `package.json` by removing `ejs` from dependency list since it's irrelevant.
- And specified `^` for `fast-xml-parser` package.
- Reinstalled all the packages to make them up to date.

feat: update node dependencies

---

packages/apps/reputation-oracle/server/src/common/enums/role.ts
packages/apps/reputation-oracle/server/src/common/guards/signature.auth.spec.ts
packages/apps/reputation-oracle/server/src/common/guards/signature.auth.ts
packages/apps/reputation-oracle/server/src/common/utils/signature.ts
packages/apps/reputation-oracle/server/src/modules/reputation/reputation.controller.spec.ts
packages/apps/reputation-oracle/server/src/modules/reputation/reputation.controller.ts
packages/apps/reputation-oracle/server/src/modules/reputation/reputation.service.ts
packages/apps/reputation-oracle/server/src/modules/webhook/webhook.controller.ts
packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts

Add signature to all webhook endpoints
- Improve signature guard
- Add signature verification to all webhook endpoints
- Format code
`yarn test`
Close #1026 #1030

[Reputation Oracle] Add signature to all webhook endpoints

---

packages/apps/job-launcher/server/vercel.json

Change the interval of execution of crons jobs to reduce the computation time of the database

Job Launcher - Change cron expression to every 10 min

---

packages/apps/meta-code-verify/src/js/__tests__/contentUtils.test.ts

Package updates are causing this mock function calls.

update mock call function times

---

.github/dependabot.yml

Adding cargo package ecosystem to dependabot config for rust dependency updates.

[Monorepo] [CI/CD] add cargo package ecosystem to dependabot for rust

---

packages/sdk/typescript/human-protocol-sdk/package.json
packages/sdk/typescript/human-protocol-sdk/src/index.ts

Export Encryption and EncryptionUtils and add OpenPGP as dependency in package.json

[SDK][Typescript] Export Encryption and EncryptionUtils

---

.github/dependabot.yml
packages/apps/job-launcher/server/src/app.module.ts
packages/apps/job-launcher/server/src/main.ts
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/staking.py
packages/sdk/typescript/human-protocol-sdk/package.json
packages/sdk/typescript/human-protocol-sdk/src/escrow.ts
packages/sdk/typescript/human-protocol-sdk/src/index.ts
packages/sdk/typescript/human-protocol-sdk/src/staking.ts

Release 20231019

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/PULL_REQUEST_TEMPLATE.md

Simplify the templates for bugs and PRs

Monorepo - simplify templates

---

packages/apps/fortune/exchange-oracle/server/src/modules/job/job.controller.spec.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.dto.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.spec.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts

Exchange Oracle should stop requesting solutions if already got the ones required.
Get manifest on solveJobs to check the amount of sent solutions
Get solutions on getDetails to check if the job has already been completed
`yarn test`
#1086

[Exchange Oracle ] Stop requesting solutions

---

packages/examples/cvat/exchange-oracle/src/core/config.py
packages/examples/cvat/exchange-oracle/src/cvat/api_calls.py

- Removed the `CVAT_ADMIN_USER_ID` parameter, which is not needed for any function calls.

[CVAT example] Remove extra CVAT_ADMIN_USER_ID param

---

packages/apps/reputation-oracle/server/src/common/enums/job.ts
packages/apps/reputation-oracle/server/src/modules/webhook/webhook.dto.ts
packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
packages/apps/reputation-oracle/server/test/constants.ts

Create a reputation system to increase or decrease the reputation of workers and oracles as appropiate
Remove Reputation Oracle check on fortune solutions
Increase reputation of valid workers
Decrease reputation of invalid workers
Modify exchange oracle reputation based on the solutions received in Recording Oracle
Increase reputation of Recording and Job Launcher
`yarn test`
#1089

[Reputation Oracle] Create reputation system

---

packages/apps/job-launcher/server/src/modules/job/job.service.ts
packages/apps/job-launcher/server/src/modules/web3/web3.service.spec.ts
packages/apps/job-launcher/server/src/modules/web3/web3.service.ts

Fix getJobsList endpoint
Cast networks and EscrowStatus arrays to Number
`yarn test`

[Job Launcher] Fix job status and chain id in getJobsList

---

packages/apps/job-launcher/server/src/modules/job/job.dto.ts
packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts

Fix job status in getJobsList add status in job details
Update wrong for loop 
Add status in job details
`yarn test`

[Job Launcher] Fix job status in getJobsList add status in job details

---

packages/apps/hufi/exchange-oracle/server/src/app.module.ts
packages/apps/hufi/job-launcher/server/src/app.module.ts
packages/apps/job-launcher/server/src/app.module.ts

Fix swagger static files routes for Vercel deployment

Hufi - fix swagger static files routes

---

packages/examples/cvat/exchange-oracle/Dockerfile
packages/examples/cvat/recording-oracle/Dockerfile

Dockerfile setup fix for CVAT Exchange and Recording oracles
Added `ffmpeg`, `libsm6` and `libxext6` libs to Dockerfile setup to fix deps issue on a startup
To close #1138

Dockerfile setup fix for CVAT Exchange and Recording oracles

---

packages/apps/hufi/exchange-oracle/server/package.json
packages/apps/hufi/exchange-oracle/server/src/modules/job/job.module.ts

Fix Hufi Exchange Oracle deployment on vercel

Hufi Exchange Oracle - fix vercel deployment

---

packages/apps/reputation-oracle/server/package.json
packages/apps/reputation-oracle/server/vercel.json

Vercel setup
Add `vercel.json`
Add `vercel-build` in `package.json`

[Reputation Oracle] Vercel setup

---

packages/apps/job-launcher/client/src/services/job.ts
packages/apps/job-launcher/client/src/types/index.ts

To fix a bug during CVAT job launch.
Added missing `userGuide` field to `/job/cvat` request
To close #1167

Added missing field to `/job/cvat` request

---

packages/examples/fortune/recording-oracle/src/plugins/config.ts
packages/examples/fortune/recording-oracle/src/plugins/curses.ts
packages/examples/fortune/recording-oracle/src/services/recordingOracle.ts
yarn.lock

Fix lint issues, and dependency lock.

[Monorepo] Fix: Lint

---

packages/apps/hufi/exchange-oracle/server/src/modules/job/job.controller.ts
packages/apps/hufi/exchange-oracle/server/src/modules/job/job.dto.ts
packages/apps/hufi/exchange-oracle/server/src/modules/job/job.service.ts

The get liquidity endpoint was returning a boolean instead of the score value.

Hufi - fix Exchange Oracle return liquidity value

---

packages/apps/job-launcher/server/src/modules/job/job.dto.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts

Added additional format for sendWebhook method. 
- Added CVATWebhookDto and FortuneWebhookDto
`yarn test`
- Create CVAT job
- Cancel Fortune or CVAT job
[[Job Launcher] Change format for webhook call#1186](https://github.com/humanprotocol/human-protocol/issues/1186)

[Job Launcher] Changed format for webhook call

---

packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts

Fixed incorrect `job_bounty` calculation
`fundAmount` is replaced with `tokenFundAmount`
To close #1197

[Job Launcher] Fixed incorrect `job_bounty` calculation

---

packages/apps/job-launcher/server/src/modules/job/job.service.ts

Added optional encryption for send webhook method
- Updated sendWebhook method
`yarn test`

[Job Launcher] Add optional encryption for send webhook method

---

packages/apps/reputation-oracle/server/src/common/enums/webhook.ts
packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts

Modify event name for incoming webhooks in reputation oracle
Modify event name
Update dto
Update service to check new event name
Update tests
´yarn test´

[Reputation Oracle] Modify event name for incoming webhooks

---

packages/examples/cvat/exchange-oracle/src/crons/process_job_launcher_webhooks.py
packages/examples/cvat/recording-oracle/src/crons/process_reputation_oracle_webhooks.py

Temp switch to a camelCase for webhooks: exchange oracle -> job launcher, recording oracle -> reputation oracle
snake_case replaced with camelCase

[CVAT][Oracles] Temp switch to a camelCase for webhooks

---

packages/apps/job-launcher/server/src/modules/auth/auth.dto.ts

Add `+` sign to special character list of password validation regex.
Closes #1170

[Job Launcher] fix: job launcher server password special character

---

packages/apps/reputation-oracle/server/src/modules/auth/auth.dto.ts
packages/apps/reputation-oracle/server/src/modules/storage/storage.service.ts

Update absolute paths to run on Vercel
Replace absolute paths with relative paths
`yarn test`

[Reputation Oracle] Update absolute paths to run on Vercel

---

packages/apps/job-launcher/server/src/modules/job/job.dto.ts
packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts

Results endpoint should return the array of answers for fortune and the url to the file for other job types
Modify get results endpoint and tests
yarn test

Job Launcher - Fix results endpoint

---

packages/apps/job-launcher/client/src/components/Jobs/Create/FundingMethod.tsx
packages/apps/job-launcher/client/src/components/TopUpAccount/TopUpMethod.tsx
packages/apps/job-launcher/client/src/constants/chains.ts

Allow only polygon network and crypto payments for mainnet

Job Launcher Client - mainnet restrictions

---

packages/apps/job-launcher/server/src/modules/payment/payment.service.spec.ts
packages/apps/job-launcher/server/src/modules/payment/payment.service.ts

Fix failing tests in Payment module
Add a new mock for a method added previously
`yarn test`

[Job Launcher] Fix failing tests in Payment module

---

packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.spec.ts
packages/apps/fortune/exchange-oracle/server/src/modules/storage/storage.service.spec.ts
packages/apps/fortune/exchange-oracle/server/src/modules/storage/storage.service.ts
packages/apps/fortune/recording-oracle/src/modules/storage/storage.service.spec.ts
packages/apps/fortune/recording-oracle/src/modules/storage/storage.service.ts
packages/apps/hufi/exchange-oracle/server/src/modules/job/job.service.spec.ts
packages/apps/job-launcher/server/src/modules/storage/storage.service.spec.ts
packages/apps/job-launcher/server/src/modules/storage/storage.service.ts
packages/apps/reputation-oracle/server/src/modules/storage/storage.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/storage/storage.service.ts
packages/examples/fortune/launcher/server/src/plugins/s3.ts
packages/examples/fortune/recording-oracle/src/plugins/s3.ts
packages/examples/fortune/reputation-oracle/src/services/s3.ts
packages/sdk/typescript/human-protocol-sdk/src/storage.ts
packages/sdk/typescript/human-protocol-sdk/test/storage.test.ts

Remove google cloud cache for all oracles
Disable this cache by adding the header `Cache-Control': 'no-store'` when uploading the file
`yarn test`
#1174

All oracles - Google Storage cache

---

package.json
packages/apps/faucet-server/package.json
packages/apps/hufi/job-launcher/server/package.json
packages/apps/hufi/reputation-oracle/server/package.json
packages/apps/job-launcher/server/package.json
packages/apps/reputation-oracle/server/package.json
packages/core/hardhat.config.ts
packages/core/package.json
packages/examples/fortune/exchange-oracle/client/package.json
packages/examples/fortune/launcher/client/package.json
packages/examples/fortune/package.json
packages/examples/fortune/recording-oracle/package.json
packages/examples/fortune/reputation-oracle/package.json
yarn.lock

Update old node dependencies.
- Updated package.json for old packages.
- Disabled tenderly in core, since we are not using it.

[Monorepo] feat: update node dependencies

---

packages/apps/reputation-oracle/server/src/common/interfaces/index.ts
packages/apps/reputation-oracle/server/src/common/interfaces/reputation.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.controller.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.dto.ts
packages/apps/reputation-oracle/server/src/modules/health/health.controller.ts
packages/apps/reputation-oracle/server/src/modules/reputation/reputation.controller.spec.ts
packages/apps/reputation-oracle/server/src/modules/reputation/reputation.controller.ts
packages/apps/reputation-oracle/server/src/modules/reputation/reputation.dto.ts
packages/apps/reputation-oracle/server/src/modules/reputation/reputation.service.ts
packages/apps/reputation-oracle/server/src/modules/webhook/webhook.controller.ts
packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts

Description
Add documentation to Reputation Oracle swagger API based on [Nest Swagger docs](https://docs.nestjs.com/openapi/operations)
Summary of changes
Add documentation to swagger API
Fix a couple of void functions that returned boolean
How test the changes
yarn test
Related issues
Close #1264

[Reputation Oracle] Swagger docs

---

packages/apps/job-launcher/server/src/modules/job/job.service.ts
packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts

Reenable cron jobs of job launcher disabled by mistake
- Reenable cron jobs
- Fix lint errors

Job Launcher - Reenable cron jobs

---

packages/apps/fortune/recording-oracle/src/common/config/server.ts
packages/apps/fortune/recording-oracle/src/common/config/validation.ts
packages/apps/fortune/recording-oracle/src/modules/job/job.service.spec.ts
packages/apps/fortune/recording-oracle/src/modules/storage/storage.service.spec.ts
packages/apps/fortune/recording-oracle/src/modules/storage/storage.service.ts
packages/apps/fortune/recording-oracle/test/constants.ts

Manifest and exchange oracle solutions are uploaded encrypted, so need to decrypt it.
- Updated storage service download function to decrypt file, in case it's encrypted.
- Updated unit tests.
Closes #1037

[Fortune] [Recording Oracle] Decrypt solution/manifest

---

packages/apps/fortune/recording-oracle/src/common/config/server.ts
packages/apps/fortune/recording-oracle/src/common/config/validation.ts
packages/apps/fortune/recording-oracle/src/modules/job/job.service.spec.ts
packages/apps/fortune/recording-oracle/src/modules/storage/storage.service.spec.ts
packages/apps/fortune/recording-oracle/src/modules/storage/storage.service.ts
packages/apps/fortune/recording-oracle/test/constants.ts

Solution file uploaded from recording oracle should be encrypted with reputation oracle public key.
- Updated storage service of recording oracle to encrypt solutions before uploading the data.
- Relevant test cases are updated.
Closes #315

[Fortune] [Recording Oracle] feat: encrypt solutions file uploaded

---

docs/sdk/SUMMARY.md
docs/sdk/changelog.md

SDK changelog for v1.1.19

---

packages/apps/job-launcher/server/src/modules/job/job.service.ts
packages/apps/job-launcher/server/src/modules/user/user.dto.ts

Fix job launcher relative paths
Update `src/...` with `.

[Job Launcher] Fix relative paths

---

packages/apps/escrow-dashboard/src/components/Cards/Container/Container.tsx
packages/apps/escrow-dashboard/src/components/HumanAppData/HumanAppDataView.tsx
packages/apps/escrow-dashboard/src/components/SolvedTasks/NewsView.tsx
packages/apps/escrow-dashboard/src/components/SolvedTasks/SolvedTasksView.tsx

Fixed card spacings according to Figma - https://www.figma.com/file/zRHM9A1jqZbgY1UlcMpwPD/Leaderboard%2FLaunchpad?type=design&node-id=614-2345&mode=dev

fix card paddings on dashboard

---

packages/apps/job-launcher/server/Dockerfile

Fix workspace name in dockerfile
`docker compose build job-launcher`

Job Launcher - Fix dockerfile

---

docs/sdk/SUMMARY.md

Changelog cannot be clicked in sdk docs

Fix changelog in docs

---

docs/sdk/SUMMARY.md

Fix changelog in docs (#1352)

---

packages/apps/job-launcher/client/src/components/Jobs/Create/CreateJob.tsx
packages/apps/job-launcher/client/src/components/Jobs/Create/FundingMethod.tsx
packages/apps/job-launcher/client/src/components/Jobs/Create/PayJob.tsx
packages/apps/job-launcher/client/src/components/TopUpAccount/TopUpMethod.tsx
packages/apps/job-launcher/client/src/constants/chains.ts
packages/apps/job-launcher/client/src/pages/Profile/TopUpAccount/index.tsx
packages/apps/job-launcher/client/src/providers/CreateJobPageUIProvider.tsx

This will close #1356 , disabled hCaptcha and fortune on mainnet.

[Job Launcher] Disable Fortune and hCaptcha on mainnet

---

docs/sdk/changelog.md

SDK changelog update

---

.github/workflows/cd-node-sdk.yaml
.github/workflows/cd-python-sdk.yaml
package.json
packages/apps/faucet-server/package.json
packages/apps/job-launcher/client/package.json
packages/apps/meta-code-verify/package.json
packages/core/package.json
yarn.lock

- Fix SDK CD
- Update some dependencies

Fix SDK CD

---

packages/apps/job-launcher/server/src/modules/storage/storage.service.ts
packages/apps/reputation-oracle/server/src/modules/storage/storage.service.ts

Fix wrong param passed to hashStream function

Reputation Oracle - Wrong param hashStream

---

packages/apps/job-launcher/client/src/components/Accordion/index.tsx
packages/apps/job-launcher/client/src/components/Jobs/Create/CvatJobRequestForm.tsx
packages/apps/job-launcher/client/src/components/Jobs/Create/FortuneJobRequestForm.tsx
packages/apps/job-launcher/client/src/components/Jobs/Create/HCaptchaJobRequestForm.tsx
packages/apps/job-launcher/client/src/components/Jobs/Create/schema.ts
packages/apps/job-launcher/client/src/services/job.ts
packages/apps/job-launcher/client/src/types/index.ts

This will close #1361, updated job launcher client to support S3 buckets on CVAT.
- Fortune job form - updated the UI to use accordions like others.
- CVAT job form - updated the UI to select s3 provider, region, bucket name and path.

[Job Launcher] CVAT S3 buckets

---

packages/apps/job-launcher/server/src/modules/webhook/webhook.controller.ts
packages/apps/job-launcher/server/src/modules/webhook/webhook.service.spec.ts
packages/apps/job-launcher/server/src/modules/webhook/webhook.service.ts
packages/apps/job-launcher/server/vercel.json

Add new cron jobs and change cron expression
yarn test

Job Launcher - Add cron jobs

---

packages/apps/dashboard/ui/src/hooks/useMonthlyTaskSummaries.ts

This will fix #1438 , correctly sort the solved tasks data series by its date.
Added sort param to the API query.

fix date sorting for solved tasks chart

---

packages/apps/job-launcher/server/src/modules/job/job.controller.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts

- Fix endpoint request type
- Fix setting Recording Oracle address as Reputation Oracle

Job Launcher - Fix issues detected

---

packages/apps/reputation-oracle/server/src/app.module.ts
packages/apps/reputation-oracle/server/src/common/interceptors/snake-case.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.dto.ts
packages/apps/reputation-oracle/server/src/modules/reputation/reputation.controller.ts
packages/apps/reputation-oracle/server/src/modules/reputation/reputation.dto.ts
packages/apps/reputation-oracle/server/src/modules/user/user.dto.ts
packages/apps/reputation-oracle/server/src/modules/webhook/webhook.dto.ts

- Setup snake case interceptor.
- Configure name from `ApiProperty`.
Closes #1452

feat: use snake case for reputation oracle API request/response

---

packages/apps/job-launcher/client/src/components/Jobs/Create/CreateJob.tsx
packages/apps/job-launcher/client/src/providers/CreateJobPageUIProvider.tsx

Set default job type CVAT and  remove Fortune and HCaptcha from the dropdown. Also remove Hcaptcha for testnet.
Also, modified the network select to set a default value when you have a supported chain selected in your wallet or when you request to pay with card
Check the different environments 
#1445

[Job Launcher][Client] Disable job types

---

docs/sdk/changelog.md

Update SDK changelog for release

Update SDK changelog

---

packages/apps/reputation-oracle/server/src/modules/storage/storage.module.ts

[Reputation Oracle] fix: storage module init

---

package.json
packages/apps/dashboard/ui/package.json
packages/apps/job-launcher/client/package.json
packages/apps/meta-code-verify/package.json
yarn.lock

Update vite version to fix security issue.
https://github.com/vitejs/vite/security/advisories/GHSA-c24v-8rfc-w8vw

fix: update vite version to fix security warning

---

packages/apps/job-launcher/server/src/modules/job/job.repository.ts

Update getJobsByStatus to take into account new job statuses:
-   CREATED
-   SET_UP 
Add new statuses to the repository filter
`yarn test`
#1497

[Job Launcher] Add new untracked statuses to getJobsByStatus

---

packages/apps/job-launcher/server/src/modules/job/job.service.ts
packages/apps/job-launcher/server/src/modules/storage/storage.module.ts
packages/apps/job-launcher/server/src/modules/storage/storage.service.spec.ts
packages/apps/job-launcher/server/src/modules/storage/storage.service.ts

Fix the usage of encryption module inside Job Launcher
Remove all the encryption instances and use always the same defined in encryption module
`yarn test`
#1490

[Job Launcher] Encryption module

---

packages/apps/dashboard/admin/config/api.ts
packages/apps/dashboard/admin/config/cron-tasks.ts
packages/apps/dashboard/admin/package.json
packages/apps/dashboard/admin/src/api/daily-task-summary/content-types/daily-task-summary/schema.json
packages/apps/dashboard/admin/src/api/daily-task-summary/controllers/daily-task-summary.ts
packages/apps/dashboard/admin/src/api/daily-task-summary/routes/01-custom-daily-task-summary.ts
packages/apps/dashboard/admin/src/api/daily-task-summary/routes/daily-task-summary.ts
packages/apps/dashboard/admin/src/api/daily-task-summary/services/daily-task-summary.ts
packages/apps/dashboard/admin/types/generated/contentTypes.d.ts

- Build the dashboard admin 
- Move codebase from standalone repo

fix build issue, move codebase

---

packages/apps/job-launcher/server/src/common/exceptions/database.filter.ts

Fix imports for vercel
Update from `src/` to `../..`

[Job Launcher] Update imports for Vercel

---

packages/apps/reputation-oracle/server/src/database/database.module.ts

Reputation Oracle - Fix import route

---

packages/apps/job-launcher/server/src/database/database.enum.ts
packages/apps/job-launcher/server/src/database/database.error.ts
packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts
packages/apps/job-launcher/server/src/modules/payment/payment.dto.ts
packages/apps/job-launcher/server/src/modules/payment/payment.repository.ts
packages/apps/job-launcher/server/src/modules/payment/payment.service.spec.ts
packages/apps/job-launcher/server/src/modules/payment/payment.service.ts
packages/apps/job-launcher/server/src/modules/user/user.repository.ts

Rework service - repository schema in payment module
Remove all unnecessary methods from user repository and extend it from base Repository
`yarn test`
#1532

[Job Launcher] Rework payment service - repository schema

---

packages/examples/cvat/exchange-oracle/tests/integration/chain/test_escrow.py
packages/examples/cvat/exchange-oracle/tests/integration/chain/test_kvstore.py
packages/examples/cvat/exchange-oracle/tests/integration/cron/test_process_job_launcher_webhooks.py
packages/examples/cvat/exchange-oracle/tests/integration/cron/test_process_recording_oracle_webhooks.py
packages/examples/cvat/recording-oracle/tests/integration/chain/test_escrow.py
packages/examples/cvat/recording-oracle/tests/integration/chain/test_kvstore.py
packages/examples/cvat/recording-oracle/tests/integration/endpoints/test_webhook.py

Fix CVAT failing tests in recording and exchange oracles for the changes made in #1547
`docker-compose -f docker-compose.test.yml up --build test --attach test --exit-code-from test`
#1547

[CVAT] Fix tests

---

packages/apps/job-launcher/server/src/database/base.repository.ts
packages/apps/job-launcher/server/src/modules/cron-job/cron-job.module.ts
packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.spec.ts
packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.ts
packages/apps/job-launcher/server/src/modules/job/job.repository.ts
packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts
packages/apps/job-launcher/server/src/modules/payment/payment.repository.ts
packages/apps/job-launcher/server/src/modules/user/user.repository.ts

Rework service - repository schema in job module
Rework service - repository schema in job module
Add a `base.repository.ts` to avoid duplicated code
`yarn test`
#1532

[Job Launcher] Rework job service - repository schema

---

packages/apps/job-launcher/server/src/modules/job/job.controller.ts

Added an ApiKey() decorator to the getDetails method in the job controller. This change enforces API key authentication to secure the job detail endpoint when accessed via Discord integrations.
- Added ApiKey() decorator to the getDetails function in job.controller.ts to require an API key for access.
- This change was made to enhance the security of our API, particularly for requests originating from Discord bots or webhooks.
To test these changes, you should:
1. Ensure that the API key middleware is properly configured to validate the keys.
2. Use an API testing tool like Postman:
- Send a request to the getDetails endpoint with a valid API key and verify that the response is successful.
- Send a request to the same endpoint with an invalid API key and confirm that access is denied with …

[Discord Job Launcher Milestone-2]

---

packages/apps/job-launcher/client/src/components/Auth/ResetPasswordForm.jsx
packages/apps/job-launcher/client/src/components/Auth/SignInForm.jsx
packages/apps/job-launcher/client/src/components/Auth/SignUpForm.jsx
packages/apps/job-launcher/client/src/types/index.ts
packages/apps/job-launcher/server/src/common/config/env.ts
packages/apps/job-launcher/server/src/common/constants/errors.ts
packages/apps/job-launcher/server/src/common/utils/hcaptcha.ts
packages/apps/job-launcher/server/src/modules/auth/auth.controller.ts
packages/apps/job-launcher/server/src/modules/auth/auth.dto.ts
packages/apps/job-launcher/server/src/modules/auth/auth.service.spec.ts
packages/apps/job-launcher/server/src/modules/auth/auth.service.ts
packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.ts
packages/apps/job-launcher/server/src/modules/user/user.dto.ts
packages/apps/job-launcher/server/src/modules/user/user.service.spec.ts

Send hcaptcha token to server for verification
Add the hcaptcha token to server and client login dtos
Check the token in hcaptcha server
If the token is correct, send the proper tokens to the client
`yarn test`
#1487

[Job Launcher] Send hcaptcha token for verification

---

packages/apps/job-launcher/server/src/common/config/env.ts
packages/apps/job-launcher/server/src/modules/auth/auth.service.ts

Temporarily disable hcaptcha token verification, while we get the new secret.

Job Launcher - Temporarily disable hcaptcha token verification

---

packages/apps/job-launcher/server/src/modules/auth/auth.service.ts

Fix token for email validaiton not saved:
`ERROR [ExceptionsHandler] invalid input syntax for type uuid: "undefined"`

Job Launcher - Fix token for email validaiton not saved

---

packages/examples/cvat/exchange-oracle/poetry.lock
packages/examples/cvat/recording-oracle/poetry.lock

https://github.com/humanprotocol/human-protocol/actions/runs/7971976179/job/21762973647?pr=1467
- Updated `cryptography`: 42.0.1 -> 42.0.3

Update cryptography package in CVAT oracles

---

docs/sdk/SUMMARY.md

Fix route to operatorUtils in sdk docs

Fix ts sdk docs

---

docs/sdk/SUMMARY.md

fix ts sdk docs (#1610)

---

packages/apps/reputation-oracle/server/src/common/constants/errors.ts
packages/apps/reputation-oracle/server/src/common/constants/index.ts
packages/apps/reputation-oracle/server/src/common/enums/user.ts
packages/apps/reputation-oracle/server/src/common/enums/web3.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.controller.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.dto.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts
packages/apps/reputation-oracle/server/src/modules/user/user.controller.ts
packages/apps/reputation-oracle/server/src/modules/user/user.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/user/user.service.ts
packages/apps/reputation-oracle/server/src/modules/web3/web3.controller.ts
packages/apps/reputation-oracle/server/src/modules/web3/web3.dto.ts
packages/apps/reputation-oracle/server/src/modules/web3/web3.module.ts
packages/apps/reputation-oracle/server/src/modules/web3/web3.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/web3/web3.service.ts

Create an endpoint to disable an operator
Add a new endpoint to disable an operator
Modify last preWeb3SignUp endpoint to make it generic
`yarn test`
#1607

[Reputation Oracle] Disable Operator endpoint

---

packages/apps/fortune/exchange-oracle/server/src/common/utils/case-converter.ts
packages/apps/fortune/recording-oracle/src/common/utils/case-converter.ts
packages/apps/job-launcher/server/src/common/utils/case-converter.ts
packages/apps/reputation-oracle/server/src/common/interceptors/snake-case.ts

Fix camelCase converter for nested objects
Update the transformToCamelCase method to transform also nested objects
`yarn test`
#1617

[Oracles] camelCase converter

---

packages/apps/reputation-oracle/server/src/common/constants/index.ts
packages/apps/reputation-oracle/server/src/modules/webhook/webhook.dto.ts
packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts

Follow the webhook standard.
- Updated Header name.
- Added `event_data` to request payload.
- Removed unused variables from webhook test.
Closes #1507

feat: Reputation Oracle - Modify webhook endpoint

---

packages/apps/reputation-oracle/server/src/common/constants/index.ts

Undo signature header change to follow the same in all oracles

Reputation Oracle - Undo signature header change

---

packages/apps/reputation-oracle/server/src/common/constants/errors.ts
packages/apps/reputation-oracle/server/src/modules/web3/web3.service.ts

Fix gas price calculation
Edit calculateGasPrice in web3.service.ts to throw an error when gas price cannot be obtained
`yarn test`

[Reputation Oracle] Fix gas price calculation

---

.prettierrc

Modify prettier on root folder. 
Following [Prettier Configuration File](https://www.npmjs.com/package/prettier-plugin-solidity) add `["prettier-plugin-solidity"]` plugin on `.prettierrc`
Closes #1646

Add Solidity Plugin on Prettier  

---

packages/apps/job-launcher/server/src/modules/webhook/webhook.module.ts

Job Launcher - Fix webhook module

---

packages/apps/reputation-oracle/server/src/database/migrations/1709188760416-DropCheckPassedColumnFromWebhookIncoming.ts

[Reputation Oracle] Added missing migration

---

packages/apps/job-launcher/server/src/app.module.ts
packages/apps/job-launcher/server/src/modules/webhook/webhook.dto.ts
packages/apps/job-launcher/server/src/modules/webhook/webhook.module.ts

Webhook module has not been registered, so webhook notifications cannot be received.

Job Launcher - Fix: webhook module not being registered

---

packages/examples/cvat/exchange-oracle/src/chain/escrow.py
packages/examples/cvat/exchange-oracle/tests/integration/chain/test_escrow.py
packages/examples/cvat/recording-oracle/src/chain/escrow.py
packages/examples/cvat/recording-oracle/tests/integration/chain/test_escrow.py

Copy of #1665 for the M2 branch.

[CVAT] Fix escrow manifest downloading (M2)

---

packages/apps/job-launcher/server/src/database/migrations/1707813322453-removeAuthTable.ts

Fix job launcher migrations in tokens table

Fix Job Launcher migrations

---

packages/examples/cvat/exchange-oracle/src/utils/annotations.py
packages/examples/cvat/recording-oracle/src/handlers/process_intermediate_results.py

When CVAT jobs don't have points, the validation will be skipped even if the GT point is not visible. Fix this by adding point stubs marked as absent for correct comparison.
- Fixed invalid comparison for absent/hidden points in jobs

[CVAT] Fix comparison for absent points

---

packages/examples/cvat/recording-oracle/docker-compose.test.yml

Healthcheck interval increased for local blockchain node to avoid a container being unhealthy

[CVAT] Healthcheck interval increased for local blockchain node

---

packages/examples/cvat/recording-oracle/docker-compose.test.yml

Ported #1700 into the M2 branch.

[CVAT-M2] Fix RecOr tests

---

packages/core/contracts/governance/DAOSpokeContract.sol
packages/core/contracts/governance/MetaHumanGovernor.sol
packages/core/contracts/test/WormholeMock.sol

This pull request adds [Wormhole Receive Refunds](https://docs.wormhole.com/wormhole/quick-start/tutorials/hello-wormhole/beyond-hello-wormhole#feature-receive-refunds) functionality.
Added parameters to wormhole communication to support refunds on targetChain.

MHG-11 - added Feature: Receive Refunds for Wormhole communication

---

packages/apps/job-launcher/server/api/app.ts
packages/apps/job-launcher/server/package.json
packages/apps/job-launcher/server/src/app-init.ts
packages/apps/job-launcher/server/src/app.module.ts
packages/apps/job-launcher/server/src/main.ts
packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.ts
packages/apps/job-launcher/server/vercel.json
yarn.lock

Create app.ts to use Job Launcher as serverless function so that we can increase Vercel timeout

Job Launcher server - serverless functions

---

packages/apps/job-launcher/server/src/modules/job/job.service.ts
yarn.lock

Modified the setup method to detect hCaptcha job types.
If the job type is hCaptcha, skip manifest download and validation.
- Updated setup method
https://github.com/humanprotocol/human-protocol/issues/1732

[Job Launcher] Add job type check

---

packages/apps/job-launcher/server/vercel.json

Define controllers in vercel.json to avoid requests to non defined routes

Job Launcher - Improve Vercel config

---

packages/examples/cvat/exchange-oracle/src/handlers/job_creation.py
packages/examples/cvat/exchange-oracle/src/utils/annotations.py

- Added better handling for COCO instances (polygons and masks) to be compatible with original COCO
- Added more validations
- Fixed handling relative paths in cloud storage with input data

[CVAT-M2] Various improvements in task creation

---

packages/apps/job-launcher/server/api/app.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts
packages/apps/job-launcher/server/src/modules/webhook/webhook.controller.ts
packages/apps/job-launcher/server/vercel.json

Job Launcher - Quick launch fixes

---

packages/apps/fortune/exchange-oracle/server/src/app.module.ts
packages/apps/fortune/exchange-oracle/server/src/common/config/env.ts
packages/apps/fortune/exchange-oracle/server/src/common/constant/errors.ts
packages/apps/fortune/exchange-oracle/server/src/common/constant/index.ts
packages/apps/fortune/exchange-oracle/server/src/common/enums/cron-job.ts
packages/apps/fortune/exchange-oracle/server/src/common/enums/webhook.ts
packages/apps/fortune/exchange-oracle/server/src/common/guards/cron.auth.ts
packages/apps/fortune/exchange-oracle/server/src/common/interfaces/base.ts
packages/apps/fortune/exchange-oracle/server/src/common/interfaces/cron-job.ts
packages/apps/fortune/exchange-oracle/server/src/database/database.module.ts
packages/apps/fortune/exchange-oracle/server/src/database/migrations/1710871038249-initialMigration.ts
packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.controller.ts
packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.interface.ts
packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.repository.ts
packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.service.ts
packages/apps/fortune/exchange-oracle/server/src/modules/cron-job/cron-job.entity.ts
packages/apps/fortune/exchange-oracle/server/src/modules/cron-job/cron-job.module.ts
packages/apps/fortune/exchange-oracle/server/src/modules/cron-job/cron-job.repository.ts
packages/apps/fortune/exchange-oracle/server/src/modules/cron-job/cron-job.service.ts
packages/apps/fortune/exchange-oracle/server/src/modules/cron-job/cron.job.controller.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.controller.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.dto.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.module.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts
packages/apps/fortune/exchange-oracle/server/src/modules/webhook/webhook.module.ts
packages/apps/fortune/exchange-oracle/server/src/modules/webhook/webhook.repository.ts
packages/apps/fortune/exchange-oracle/server/src/modules/webhook/webhook.service.ts

Add a new cron job module to send all outgoing webhooks
Create cron-job module
Fix some bugs with paths
Add webhooks to database instead of sending them directly in job.service.ts
Check workerAddress in getAssignmentsList
Check assignments before solving a job in solveJob
Generate new migrations

[Exchange Oracle] Cron-job module

---

packages/apps/job-launcher/server/src/common/guards/signature.auth.spec.ts
packages/apps/job-launcher/server/src/common/guards/signature.auth.ts
packages/apps/job-launcher/server/src/modules/webhook/webhook.service.spec.ts
packages/apps/job-launcher/server/src/modules/webhook/webhook.service.ts
packages/apps/reputation-oracle/server/src/common/guards/signature.auth.spec.ts
packages/apps/reputation-oracle/server/src/common/guards/signature.auth.ts
packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts

Fix signature authentication guard
Fix signature authentication guard
Check response status of webhooks instead of data
yarn test

Fix signature authentication guard

---

packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts

Used fund amount in quick launch endpoint as HMT not USD
`yarn test`
Job Launcher - Fund amount in HMT for quick launch #1744

[Job Launcher]  Quick launch currency

---

packages/apps/dashboard/ui/src/hooks/useMonthlyTaskSummaries.ts

Temporal fix for hcaptcha task numbers while their services are down

Dashboard - Temp fix for hcaptcha downtime

---

packages/examples/cvat/exchange-oracle/src/handlers/job_creation.py
packages/examples/cvat/exchange-oracle/src/utils/annotations.py
packages/examples/cvat/recording-oracle/src/handlers/validation.py
packages/examples/cvat/recording-oracle/src/utils/assignments.py

- Improved logging for excluded GT points in BOXES_FROM_POINTS
- Fixed an error in mismatching labels reporting for GT labels in BOXES_FROM_POINTS
- Reduced min class GT bbox threshold in BOXES_FROM_POINTS
- Fixed bbox out of image validation in BOXES_FROM_POINTS
- RoI cuts are made more reliable in BOXES_FROM_POINTS by adding a cut validity threshold
- Fixed data conversion on job rejection webhook sending

[CVAT-M2] Fix validations for boxes from points task creation

---

packages/examples/cvat/exchange-oracle/src/core/config.py
packages/examples/cvat/exchange-oracle/src/core/manifest.py
packages/examples/cvat/exchange-oracle/src/core/tasks/skeletons_from_boxes.py
packages/examples/cvat/exchange-oracle/src/crons/process_job_launcher_webhooks.py
packages/examples/cvat/exchange-oracle/src/crons/state_trackers.py
packages/examples/cvat/exchange-oracle/src/handlers/job_creation.py
packages/examples/cvat/exchange-oracle/src/services/exchange.py
packages/examples/cvat/exchange-oracle/src/utils/annotations.py
packages/examples/cvat/exchange-oracle/src/utils/assignments.py
packages/examples/cvat/exchange-oracle/src/utils/webhooks.py
packages/examples/cvat/exchange-oracle/tests/integration/cron/state_trackers/test_track_task_creation.py
packages/examples/cvat/exchange-oracle/tests/integration/cron/test_process_job_launcher_webhooks.py
packages/examples/cvat/recording-oracle/src/core/manifest.py
packages/examples/cvat/recording-oracle/src/crons/process_reputation_oracle_webhooks.py
packages/examples/cvat/recording-oracle/src/utils/webhooks.py

- Removed M0 compatibility stubs in Launcher and Reputation Oracle messaging
- assignment `max_time` is optional in the manifest
- label `type` is optional in the manifest
- Enabled and fixed the disabled M1 test for task creation status tracking

[CVAT-M2] Prepare for merge into develop

---

packages/apps/job-launcher/server/src/modules/cron-job/cron.job.controller.ts
packages/apps/job-launcher/server/src/modules/webhook/webhook.service.ts

Fixed typo in `/webhook/process` endpoint
Fixed typo in `webhook.service.ts`
Changed route name:`/wehbhook/process` -> `/webhook/process`
Change typo in `webhook.service.ts`: `webhook` instead of a `wehbook`
To close #1782

[Job Launcher] Multiple typos fixed

---

packages/sdk/typescript/human-protocol-sdk/src/operator.ts

Set reputation address to lowercase before fetching graphql
Set the received address to lowercase
`yarn test`

[SDK] Fix reputation network address

---

packages/apps/job-launcher/server/src/modules/webhook/webhook.dto.ts
packages/apps/reputation-oracle/server/src/modules/user/user.dto.ts
packages/apps/reputation-oracle/server/src/modules/webhook/webhook.dto.ts

Missing `@IsOptional` decorators added in multiple DTOs
Missing `@IsOptional` decorators added in multiple DTOs to avoid throwing unexpected errors
To close #1796

Missing `@IsOptional` decorators added in multiple DTOs

---

packages/apps/fortune/exchange-oracle/server/src/modules/cron-job/cron.job.controller.ts
packages/apps/reputation-oracle/server/src/modules/cron-job/cron.job.controller.ts

Fix webhook cron job endpoints typo

Fix webhook typo

---

packages/apps/reputation-oracle/server/src/modules/auth/auth.dto.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts
packages/apps/reputation-oracle/server/test/constants.ts

Add hcaptcha token to signin dto
Update `SignInDto`
`yarn test`

Reputation Oracle - add hcaptcha token to signin dto

---

.github/workflows/ci-dependency-review.yaml

dependency review update

---

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/agreement/measures.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/escrow.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/hmtoken.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/reward.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/statistics.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/operator/operator_utils.py
packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/operator/test_operator_utils.py

Convert all addresses to lowercase when calling subgraph
Convert all addresses to lowercase when calling subgraph
Avoid exception when no subgraph data
`make run-test`

[SDK][Python] Subgraph addresses

---

package.json
packages/apps/job-launcher/server/package.json
yarn.lock

Fix dependency review

---

packages/apps/job-launcher/server/vercel.json

Update cron jobs expression to be executed every 5 min

Release - Job Launcher - Update cron expression

---

packages/apps/job-launcher/server/test/e2e/env-setup.ts
packages/apps/job-launcher/server/test/e2e/quick-launch-workflow.e2e-spec.ts

Implemented e2e quick launch workflow.
- Added end-to-end tests using Supertest to simulate HTTP requests.
- Implemented tests for quick launch.
- Covered successful flow, not enough funds, manifest hash does not exist.
`yarn test:e2e`
[Job Launcher] Implement e2e quick launch workflow
[#1840](https://github.com/humanprotocol/human-protocol/issues/1840)

[Job Launcher] Implemented e2e quick launch workflow

---

packages/examples/cvat/exchange-oracle/src/handlers/job_creation.py
packages/examples/cvat/recording-oracle/src/handlers/process_intermediate_results.py

- Fixed mismatches between the expected and actual job count (filtered-out GT RoIs were subject for annotation)
- Fixed which GT is used when adding GT in the final results
- Fixed GT preparation for `SKELETONS_FROM_BOXES`
- Fixed a debug message in recording oracle

[CVAT-M2] Review GT use

---

packages/apps/job-launcher/server/docker-compose.yml
packages/apps/job-launcher/server/package.json
packages/apps/job-launcher/server/src/app.module.ts
packages/apps/job-launcher/server/src/common/constants/index.ts
packages/apps/job-launcher/server/src/modules/auth/auth.dto.ts
packages/apps/job-launcher/server/src/modules/sendgrid/sendgrid.service.ts
packages/apps/job-launcher/server/test/e2e/app.e2e-spec.ts
packages/apps/job-launcher/server/test/e2e/auth-workflow.e2e-spec.ts
packages/apps/job-launcher/server/test/e2e/env-setup.ts
packages/apps/job-launcher/server/test/e2e/quick-launch-workflow.e2e-spec.ts
packages/apps/job-launcher/server/test/e2e/restore-password.e2e-spec.ts
packages/apps/reputation-oracle/server/src/database/migrations/1712220998800-removeOracleAddress.ts
packages/apps/reputation-oracle/server/src/modules/cron-job/cron-job.service.ts
packages/apps/reputation-oracle/server/src/modules/webhook/webhook-incoming.entity.ts
packages/core/package.json
packages/examples/cvat/exchange-oracle/src/handlers/job_creation.py
packages/examples/cvat/recording-oracle/src/handlers/process_intermediate_results.py
yarn.lock

Release Sprint 8 week 1
- JL e2e tests
- Cvat oracle fixes

Release Sprint 8 - W1

---

packages/examples/cvat/exchange-oracle/src/handlers/job_creation.py

- Fixed exclusion of some discarded annotations during inputs validation in boxes from points and skeletons from boxes
- Improved coordinate checks
- Changed image exclusion to annotation exclusion when a GT annotation has invalid coordinates

[CVAT-M2] Improve and fix inputs validation

---

packages/apps/dashboard/admin/config/cron-tasks.ts
packages/apps/dashboard/admin/package.json
yarn.lock

Admin dashboard was failing with deprecated chains
Remove deprecated chains
Closes #1874

Dashboard - Fix strapi admin

---

packages/apps/job-launcher/server/src/common/config/stripe-config.service.ts
packages/apps/job-launcher/server/test/e2e/env-setup.ts
packages/apps/job-launcher/server/test/e2e/fiat-account-deposit-workflow.e2e-spec.ts

Implemented e2e deposit fiat payment workflow.
- Added end-to-end tests using Supertest to simulate HTTP requests.
- Implemented tests for deposit fiat payment.
- Covered successful flow for deposit fiat payment.
`yarn test:e2e`
[Job Launcher] Implement e2e deposit account with fiat workflow
[#1862](https://github.com/humanprotocol/human-protocol/issues/1862)

[Job Launcher] Implemented e2e deposit fiat payment workflow

---

packages/core/contracts/governance/DAOSpokeContract.sol
packages/core/test/DAOSpokeContract.ts

This PR adds a fallback function to the DAOSpokeContract that can be failed in case of failed message delivery when the `receiveWormholeMessages` is called
- added a new function to call the vote collection functionality of DAOSpokeContract

Add sendVoteResultToHub function to DAOSpokeContract.sol

---

packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts

Can't get the jwt when the user is not validated
Remove status check in login endpoint
`yarn test`
#1896

Fix login endpoint in Reputation Oracle to return token for inactive users

---

packages/examples/cvat/exchange-oracle/src/handlers/completed_escrows.py

Follow up for #1919, now for jobs.

[CVAT-M2] Request jobs 1 by 1

---

packages/examples/cvat/recording-oracle/src/handlers/process_intermediate_results.py

Validation can fail if a job was rejected due to insufficient GT. This PR fixes this problem. Note that jobs that could not be validated now will have their quality set to -1 in the Recording Oracle results.

[CVAT-M2] Fix validation for jobs with no GT left

---

packages/examples/cvat/recording-oracle/src/handlers/process_intermediate_results.py

This PR changes the logic so that if there are no rejected jobs or only unverifiable jobs are rejected, the escrow is finished.

[CVAT-M2] Finish escrow if only unverifiable jobs left

---

packages/examples/cvat/exchange-oracle/src/handlers/job_export.py

Skipped points were exported as occluded (`hidden`), is not correct. The visibility should be `absent` instead.

[CVAT-M2] Fix visibility attribute of skipped points

---

packages/core/contracts/governance/DAOSpokeContract.sol
packages/core/contracts/governance/MetaHumanGovernor.sol
packages/core/contracts/governance/vhm-token/VHMToken.sol
packages/core/test/DAOSpokeContract.ts
packages/core/test/GovernanceUtils.ts
packages/core/test/MetaHumanGovernor.ts

- Since Governor v4.9, all voting contracts  rely on [IERC6372](https://docs.openzeppelin.com/contracts/4.x/api/interfaces#IERC6372) for clock management. The MetaHumanGovernor will automatically detect the clock mode used by the token and adapt to it. 
- Update the VHMToken overrides.

[Governance] Operate with timestamps

---

packages/examples/cvat/exchange-oracle/src/handlers/completed_escrows.py

- Fixed annotation downloading for large tasks with skeletons

[CVAT-M2] Fix annotation downloading for skeletons

---

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/constants.py

Fixing the Polygon Amoy Subgraph URL for Python SDK.

[SDK] fix: Python SDK amoy subgraph URL

---

packages/core/hardhat.config.ts
packages/core/scripts/deploy.ts

- Verify contracts on https://amoy.polygonscan.com/ 
Modify Amoy api url and browser in custom chain of hardhat config 
Modify HUMAN Token in deploy script 
Closes  #1898

change verify params for Amoy

---

packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.ts
packages/apps/job-launcher/server/src/modules/job/job.repository.ts
packages/apps/job-launcher/server/vercel.json
packages/sdk/typescript/human-protocol-sdk/src/escrow.ts

Fix to avoid timeouts and skipping funding escrow.
Adjust cron expression
`yarn test`

Job Launcher - Fix to avoid timeouts and skipping funding escrow

---

packages/core/contracts/governance/MetaHumanGovernor.sol
packages/core/test/MetaHumanGovernor.ts

Refactor to ensure a proposal becomes uncancellable by the proposer when voting period ends. 
Due to OZ v4.9 including the public `cancel()` function. 
- Change `state()` function and `execute()` function

[Governance] Update contracts 

---

.github/workflows/ci-dependency-review.yaml

Fix dependency review purl error as mentioned [https://github.com/actions/dependency-review-action/issues/763](here)
Update to v4.3.2

Fix dependency-review error

---

packages/apps/reputation-oracle/server/src/database/database.module.ts
packages/apps/reputation-oracle/server/src/modules/payout/payout.interface.ts
packages/apps/reputation-oracle/server/src/modules/payout/payout.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/reputation/reputation.interface.ts

Fix import routes for credentialling

[Reputation Oracle] Fix credentialling routes

---

packages/apps/job-launcher/server/src/common/guards/cron.auth.ts
packages/apps/job-launcher/server/src/common/guards/jwt.auth.ts
packages/apps/job-launcher/server/src/common/guards/signature.auth.spec.ts
packages/apps/job-launcher/server/src/common/guards/signature.auth.ts
packages/apps/job-launcher/server/src/common/utils/index.ts
packages/apps/job-launcher/server/src/common/utils/signature.spec.ts
packages/apps/job-launcher/server/src/common/utils/signature.ts
packages/apps/job-launcher/server/src/common/utils/storage.ts
packages/apps/job-launcher/server/src/modules/auth/auth.service.spec.ts
packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.spec.ts
packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.ts
packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
packages/apps/job-launcher/server/src/modules/payment/payment.service.spec.ts
packages/apps/job-launcher/server/src/modules/payment/payment.service.ts
packages/apps/job-launcher/server/src/modules/sendgrid/sendgrid.service.spec.ts
packages/apps/job-launcher/server/src/modules/sendgrid/sendgrid.service.ts
packages/apps/job-launcher/server/src/modules/storage/storage.service.spec.ts
packages/apps/job-launcher/server/src/modules/web3/web3.service.spec.ts
packages/apps/job-launcher/server/src/modules/webhook/webhook.service.spec.ts
packages/apps/job-launcher/server/src/modules/webhook/webhook.service.ts
packages/apps/reputation-oracle/server/src/common/guards/signature.auth.ts

Enhance unit tests by including checks for specific error messages when exceptions are thrown, particularly when a ControlledError is thrown. For example, rather than simply validating the type of error thrown, we should also confirm that the error messages themselves are appropriate and helpful
Update from: 
```// Current test
expect(
authService.forgotPassword({ email: 'user@example.com' }),
).rejects.toThrow(ControlledError);
```
To:
```// Enhanced test
expect(
authService.forgotPassword({ email: 'user@example.com' }),
).rejects.toThrow(new ControlledError("User not found",  HttpStatus.NO_CONTENT));
```
`yarn test`
#1995

[Job Launcher Server] Improve tests

---

packages/apps/dashboard/ui/src/constants/index.ts

Remove deprecated networks from faucet
- Removed Goerli, and Polygon Mumbai from faucet UI.
Closes #1989

[Faucet] feat: remove deprecated networks (#1989)

---

packages/apps/reputation-oracle/server/src/modules/credentials/credential.controller.ts

- Add POST endpoint to create a credential by Credential Validators only. 
- Update `credential.controller.ts `
Closes #1961

add post endpoint

---

packages/apps/job-launcher/server/test/e2e/fortune-workflow.e2e-spec.ts
packages/apps/job-launcher/server/test/e2e/quick-launch-workflow.e2e-spec.ts
packages/apps/job-launcher/server/test/e2e/utils.ts

Implemented e2e create Fortune workflow.
- Added end-to-end tests using Supertest to simulate HTTP requests.
- Implemented tests for Fortune.
- Covered successful flow, not enough funds.
`yarn test:e2e`
[Job Launcher] Implement e2e launching Fortune job workflow
[#1841](https://github.com/humanprotocol/human-protocol/issues/1841)

[Job Launcher] Implemented e2e create Fortune workflow

---

packages/apps/job-launcher/server/src/common/pipes/validation.ts
packages/apps/job-launcher/server/src/modules/auth/auth.controller.ts
packages/apps/job-launcher/server/src/modules/auth/strategy/jwt.http.ts
packages/apps/job-launcher/server/src/modules/job/job.controller.ts
packages/apps/job-launcher/server/src/modules/payment/payment.controller.ts
packages/apps/reputation-oracle/server/src/common/exceptions/exception.filter.ts
packages/apps/reputation-oracle/server/src/common/pipes/validation.ts
packages/apps/reputation-oracle/server/src/modules/auth/strategy/jwt.http.ts

Fix error with absolute path in Reputation Oracle
Catch validationPipe errors as ControlledError
- Update absolute path to relative
- Catch validationPipe errors as ControlledError
`yarn test`

[Reputation Oracle] Fix path error

---

packages/examples/cvat/exchange-oracle/run.py

Temporary fix for launch config investigation.

Disable server reload for exchange oracle

---

packages/apps/job-launcher/server/src/modules/auth/auth.module.ts
packages/apps/job-launcher/server/src/modules/job/job.controller.ts
packages/apps/job-launcher/server/src/modules/user/user.controller.ts
packages/apps/job-launcher/server/src/modules/user/user.module.ts

Add API Key auth to job controller and user controller
Add API Key auth to job controller and user controller
`yarn test`

[Job Launcher] API Key

---

packages/examples/cvat/exchange-oracle/poetry.lock
packages/examples/cvat/exchange-oracle/pyproject.toml
packages/examples/cvat/exchange-oracle/src/core/config.py
packages/examples/cvat/exchange-oracle/src/endpoints/__init__.py
packages/examples/cvat/exchange-oracle/src/endpoints/middleware.py

- Added an option to enable request info logging ("REQUEST_LOGGING_ENABLED=yes")
- Added an option to profile specific requests by passing request parameters (enable by "PROFILING_ENABLED=yes" in the env & `profile=1` in the request query params)

[CVAT] Add request logging options in exchange oracle

---

packages/apps/job-launcher/server/src/common/config/server-config.service.ts
packages/apps/job-launcher/server/src/common/constants/index.ts
packages/apps/job-launcher/server/src/common/constants/payment.ts
packages/apps/job-launcher/server/src/common/interfaces/payments.ts
packages/apps/job-launcher/server/src/common/utils/index.ts
packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.spec.ts
packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts
packages/apps/job-launcher/server/src/modules/payment/payment.controller.ts
packages/apps/job-launcher/server/src/modules/payment/payment.module.ts
packages/apps/job-launcher/server/src/modules/payment/payment.service.spec.ts
packages/apps/job-launcher/server/src/modules/payment/payment.service.ts
packages/apps/job-launcher/server/src/modules/payment/rate.service.spec.ts
packages/apps/job-launcher/server/src/modules/payment/rate.service.ts

Create a rate service to cache requests
Create a new rate service with cache
Remove the old utils
Update references to old getRate implementation
`yarn test`
#2047

[Job Launcher] Cache rates requests

---

packages/apps/job-launcher/server/src/common/config/env-schema.ts
packages/apps/job-launcher/server/src/common/config/server-config.service.ts
packages/apps/job-launcher/server/src/modules/payment/rate.service.ts
render.yaml

Add the option to use a coingecko api key to avoid rate limits
Call get rates endpoint

[Job Launcher] Add coingecko api key

---

packages/apps/job-launcher/client/src/components/Jobs/Table.tsx
packages/apps/job-launcher/client/src/components/Table/index.tsx
packages/apps/job-launcher/client/src/hooks/useJobs.ts
packages/apps/job-launcher/client/src/services/job.ts
packages/apps/job-launcher/server/src/common/enums/job.ts
packages/apps/job-launcher/server/src/common/pagination/pagination.dto.ts
packages/apps/job-launcher/server/src/modules/job/job.controller.ts
packages/apps/job-launcher/server/src/modules/job/job.dto.ts
packages/apps/job-launcher/server/src/modules/job/job.interface.ts
packages/apps/job-launcher/server/src/modules/job/job.repository.ts
packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts

Fix pagination for getJobList endpoint
- Update job service to query all jobs from database
- Add the right parameters to server pagination
- Adapt front to use server pagination and use the new parameters
`yarn test`
#2017

[Job Launcher] Pagination

---

packages/apps/job-launcher/client/src/components/Table/index.tsx
packages/apps/job-launcher/server/src/common/pagination/pagination.dto.ts

Fix pagination errors in Job Launcher
- Increase maximum number of rows in backend
- Remove empty rows in frontend
`yarn test`

[Job Launcher] Fix pagination

---

render.yaml

Upgrade plan to avoid suspended deployment when free limit is reached

Upgrade render plan of JL frontend

---

docs/sdk/python/human_protocol_sdk.operator.operator_utils.md
docs/sdk/typescript/classes/base.BaseEthersClient.md
docs/sdk/typescript/classes/encryption.Encryption.md
docs/sdk/typescript/classes/encryption.EncryptionUtils.md
docs/sdk/typescript/classes/escrow.EscrowClient.md
docs/sdk/typescript/classes/escrow.EscrowUtils.md
docs/sdk/typescript/classes/kvstore.KVStoreClient.md
docs/sdk/typescript/classes/operator.OperatorUtils.md
docs/sdk/typescript/classes/staking.StakingClient.md
docs/sdk/typescript/classes/statistics.StatisticsClient.md
docs/sdk/typescript/classes/storage.StorageClient.md
packages/apps/dashboard/ui/src/state/leader/reducer.ts

Generate sdk docs after changes
- Docs update
- Fix get leaders call in dashboard

regenerate docs and fix dashboard

---

packages/apps/reputation-oracle/server/src/modules/user/user.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/user/user.service.ts

Remove chain id default parameter and get a valid chain from the current env to register address
`yarn test`

[Reputation Oracle] Register address

---

packages/apps/reputation-oracle/server/src/app-init.ts
render.yaml

Add Reputation Oracle to render,yaml
- Add Reputation Oracle to render,yaml
- Read session secret from config
Merge and test deployment on Render

Add reputation oracle to render.yaml

---

render.yaml

Fix indentation in render.yaml

Fix indentation in render.yaml

---

packages/examples/cvat/exchange-oracle/poetry.lock
packages/examples/cvat/exchange-oracle/pyproject.toml

Upgrade uvicorn to >= 0.27.1 to include the resolve the problem with closed requests.
```
h11._util.LocalProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
```

[CVAT] Upgrade uvicorn in Exchange Oracle

---

packages/examples/cvat/exchange-oracle/src/handlers/job_creation.py
packages/examples/cvat/recording-oracle/src/validation/dataset_comparison.py

- Allowed GT skeletons with only 1 visible point
- Allowed GT skeletons without visible points
- Fixed validation for skeleton points with different visibility (if skeletons have more than 1 point, but it's unused now)

[CVAT-M2] Allow invisible skeletons and 1-point skeletons in GT

---

packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.controller.spec.ts
packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.controller.ts
packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.dto.ts
packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.service.spec.ts
packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.service.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.controller.spec.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.controller.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.dto.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.spec.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts

Move resign endpoint to assignment controller
- Move resign endpoint to assignment controller
- Fix tests
yarn test

[Fortune Exchange Oracle] Move resign to assignment

---

packages/examples/cvat/recording-oracle/src/validation/dataset_comparison.py

Follow-up for #2103 
- Fixed an error in return type for the OKS computation function
- Fixed type annotations for visibility array input types

[CVAT-M2] Fix result type for point comparison

---

packages/examples/cvat/exchange-oracle/src/handlers/job_creation.py

Follow up for #2107 
- Removed remaining checks for fully invisible skeletons

[CVAT-M2] Update GT skeleton validation for absent points in job creation

---

packages/apps/job-launcher/client/src/pages/Job/JobDetail/index.tsx
packages/apps/job-launcher/client/src/types/index.ts
packages/apps/job-launcher/server/src/common/constants/errors.ts
packages/apps/job-launcher/server/src/common/constants/index.ts
packages/apps/job-launcher/server/src/modules/auth/auth.module.ts
packages/apps/job-launcher/server/src/modules/cron-job/cron-job.module.ts
packages/apps/job-launcher/server/src/modules/job/job.module.ts
packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts
packages/apps/job-launcher/server/src/modules/user/user.module.ts
packages/apps/job-launcher/server/src/modules/webhook/webhook.module.ts
packages/apps/job-launcher/server/src/modules/webhook/webhook.service.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/user/user.module.ts
packages/apps/reputation-oracle/server/src/modules/user/user.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/user/user.service.ts

Fix to allow cancel jobs in status CREATED, SET_UP, PARTIAL
- Change allowed statuses that can be cancelled
- Set some services/repositories instances private
- Tests
yarn test

Fix for allowed statuses to cancel a job

---

packages/apps/job-launcher/server/src/modules/user/user.module.ts

Fix api key injection in user module
Add AuthModule to UserModule
'yarn test'

[Job Launcher] Api key injection

---

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/utils.py
packages/sdk/typescript/human-protocol-sdk/src/error.ts

Fix warning messages for missing SUBGRAPH_API_KEY

---

packages/apps/fortune/exchange-oracle/server/test/setup.ts
packages/apps/fortune/recording-oracle/test/setup.ts
packages/apps/job-launcher/server/src/common/config/pgp-config.service.ts
packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts
packages/apps/job-launcher/server/test/setup.ts
packages/apps/reputation-oracle/server/src/common/config/network-config.service.ts
packages/apps/reputation-oracle/server/src/modules/storage/storage.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/storage/storage.service.ts
packages/apps/reputation-oracle/server/src/modules/web3/web3.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/web3/web3.service.ts
packages/apps/reputation-oracle/server/test/setup.ts

Fix encryption for all oracles
Add to setup all the PGP keys
Refactor getValidChains in Reputation Oracle
`yarn test`
#2087

[Oracles] Encryption

---

packages/apps/job-launcher/client/src/components/Jobs/Create/CryptoPayForm.tsx
packages/apps/job-launcher/client/src/components/TopUpAccount/CryptoTopUpForm.tsx

Wait for transactions until they have the minimun required amount of confirmations
Add a waitForTransactionReceipt after each transfer 
#2085

Wait for transactions until they have min confirmations

---

packages/apps/job-launcher/server/src/common/constants/errors.ts
packages/apps/job-launcher/server/src/common/exceptions/exception.filter.ts
packages/apps/job-launcher/server/src/modules/auth/auth.service.spec.ts
packages/apps/job-launcher/server/src/modules/auth/auth.service.ts
packages/apps/reputation-oracle/server/src/common/constants/errors.ts
packages/apps/reputation-oracle/server/src/common/exceptions/exception.filter.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts
packages/apps/reputation-oracle/server/src/modules/user/user.repository.ts
packages/apps/reputation-oracle/server/src/modules/user/user.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/user/user.service.ts

Improve error message on duplicated address
Use baseRepository instead of entity.save
Remove Database Error from user responses
`yarn test
#2135

[Reputation Oracle][Job Launcher] Improve error handling

---

packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts

Add hcaptcha sitekey to JWT if it exists
Add sitekey to JWT if it exists
#2139

[Reputation Oracle] Add hcaptcha sitekey to JWT

---

packages/apps/job-launcher/server/src/common/constants/errors.ts
packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.ts
packages/apps/job-launcher/server/src/modules/job/job.dto.ts
packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts

Added failed reason in get job details response
- Added failed reason to all places where is it needed 
- Updated get job details endpoint
- Added new escrow errors 
[Job Launcher] Add failed reason in job details
[#2045](https://github.com/humanprotocol/human-protocol/issues/2045)

Added failed reason

---

.github/workflows/cd-subgraph.yaml

Update subgraphs cd for the graph network
Subgraphs already deployed using it
Closes #2119

[Subgraph] Update subgraphs cd for the graph network

---

packages/apps/job-launcher/server/src/app.module.ts
packages/apps/job-launcher/server/src/common/guards/apikey.auth.spec.ts
packages/apps/job-launcher/server/src/common/guards/apikey.auth.ts
packages/apps/reputation-oracle/server/src/app.module.ts

Fix swagger error on Render 
Fix wrong unauthorized error in Job launcher
`yarn test`

[Job Launcher][Reputation Oracle] Fix swagger error on Render 

---

packages/apps/job-launcher/client/src/components/Table/index.tsx
packages/apps/job-launcher/client/src/pages/Job/JobDetail/index.tsx
packages/apps/job-launcher/server/src/modules/job/job.service.ts

Job Launcher is not showing the results for Fortune jobs
Parse the object in backend when it comes as JSON
Fix table properties in client 
`yarn test`
#2114

[Job Launcher] Fortune job results not showing up

---

packages/apps/reputation-oracle/server/src/modules/auth/token.repository.ts

Add KYC status to JWT token on refresh
Update token repository to add KYC relations to users
`yarn test`

[Reputation Oracle] Refresh token

---

packages/apps/fortune/exchange-oracle/server/src/common/enums/role.ts

Transform roles to uppercase
Transform roles enum values to uppercase
`yarn test`

[Exchange Oracle] Transform roles to uppercase

---

packages/apps/job-launcher/server/src/common/constants/errors.ts
packages/apps/job-launcher/server/src/common/utils/storage.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts

Fix  failing CVAT Job creation
Fix pathname for listing objects in bucket
Add checks to avoid unhandled errors
`yarn test`

[Job Launcher] Fix CVAT Job creation

---

packages/apps/fortune/exchange-oracle/server/src/common/enums/job.ts
packages/apps/fortune/exchange-oracle/server/src/common/guards/strategy/jwt.http.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.dto.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.interface.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.repository.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts

Fix get job filters, add new filters for updated_at param and improve jwt error handling
Add date filters
Fix created_at ordering and add updated_at
Improve jwt error handling
`yarn test`
#2203 #2193 #2198

[Exchange Oracle] Fix get job filters 

---

packages/apps/reputation-oracle/server/src/common/constants/errors.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts
packages/apps/reputation-oracle/server/src/modules/user/user.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/user/user.service.ts

Add kvstore keys check
Check that the following keys exist and have correct values in the kvstore:
- role (already implemented)
- url
- fee
- job_types
Modify web3signature setting address parameters to lowercase
`yarn test`
#2200

[Reputation Oracle] Add kvstore keys check

---

packages/apps/reputation-oracle/server/src/common/enums/user.ts
packages/apps/reputation-oracle/server/src/database/migrations/1719922587868-AddKYCStatusError.ts
packages/apps/reputation-oracle/server/src/modules/kyc/kyc.dto.ts
packages/apps/reputation-oracle/server/src/modules/kyc/kyc.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/kyc/kyc.service.ts

Fix KYC status update service
- Rename property state to status
- Only set approved status if the service is ID_DOCUMENT and country exists
Pass kyc process

[Reputation Oracle] Fix KYC status update

---

packages/apps/job-launcher/server/src/modules/auth/auth.service.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts

Modified verification expiration date
- Updated the `signup` method in `AuthService` to set the expiration date.
- Updated the `resendEmailVerification` method in `AuthService` to set the expiration date.
`yarn test`
[Job Launcher | Reputation Oracle] Email verification expiration time in seconds
[#2216](https://github.com/humanprotocol/human-protocol/issues/2216)

[Job Launcher | Reputation Oracle] Modified verification expiration date

---

packages/apps/reputation-oracle/server/src/modules/kyc/kyc.controller.spec.ts
packages/apps/reputation-oracle/server/src/modules/kyc/kyc.controller.ts
packages/apps/reputation-oracle/server/src/modules/kyc/kyc.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/kyc/kyc.service.ts

Add some checks to `kyc/on-chain` endpoint 
Add checks to KYC on chain endpoint and move it to the service
`yarn test`

[Reputation Oracle] Add checks to `kyc/on-chain`

---

packages/apps/dashboard/server/.env.example
packages/apps/dashboard/server/.eslintrc.js
packages/apps/dashboard/server/.gitignore
packages/apps/dashboard/server/.prettierrc
packages/apps/dashboard/server/README.md
packages/apps/dashboard/server/docker-compose.yml
packages/apps/dashboard/server/nest-cli.json
packages/apps/dashboard/server/package.json
packages/apps/dashboard/server/src/app.controller.ts
packages/apps/dashboard/server/src/app.module.ts
packages/apps/dashboard/server/src/common/config/cache-factory.config.ts
packages/apps/dashboard/server/src/common/config/config.module.ts
packages/apps/dashboard/server/src/common/config/env-config.service.ts
packages/apps/dashboard/server/src/common/config/redis-config.service.ts
packages/apps/dashboard/server/src/main.ts
packages/apps/dashboard/server/src/modules/redis/redis.module.ts
packages/apps/dashboard/server/src/modules/redis/redis.service.ts
packages/apps/dashboard/server/src/modules/stats/dto/hmt-price.dto.ts
packages/apps/dashboard/server/src/modules/stats/stats.controller.ts
packages/apps/dashboard/server/src/modules/stats/stats.module.ts
packages/apps/dashboard/server/src/modules/stats/stats.service.ts
packages/apps/dashboard/server/tsconfig.build.json
packages/apps/dashboard/server/tsconfig.json

Dashboard backend init commit
Added dashboard backend server with Redis as a caching solution

[Dashboard Backend] Init

---

packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.dto.ts

Fix assignment_id api type
Change OsNumber to IsString

fix assignment id type

---

packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts

Add operator status to JWT
Check on kvstore operator status and include it in JWT
yarn test

[Reputation Oracle] Add operator status to JWT

---

packages/apps/dashboard/server/package.json
packages/apps/dashboard/server/src/app.module.ts
packages/apps/dashboard/server/src/modules/details/details.controller.ts
packages/apps/dashboard/server/src/modules/details/details.module.ts
packages/apps/dashboard/server/src/modules/details/details.service.ts
packages/apps/dashboard/server/src/modules/details/dto/details-response.dto.ts
packages/apps/dashboard/server/src/modules/details/dto/escrow.dto.ts
packages/apps/dashboard/server/src/modules/details/dto/leader.dto.ts
packages/apps/dashboard/server/src/modules/details/dto/wallet.dto.ts
yarn.lock

Added `/details` controller.
Added `/details` controller. to fetch data about given wallet address.

[Dashboard] Added `/details` controller

---

packages/apps/dashboard/server/src/modules/details/details.controller.ts
packages/apps/dashboard/server/src/modules/details/details.service.ts
packages/apps/dashboard/server/src/modules/details/dto/details-pagination.dto.ts
packages/apps/dashboard/server/src/modules/details/dto/details-response.dto.ts
packages/apps/dashboard/server/src/modules/details/dto/escrow.dto.ts
packages/apps/dashboard/server/src/modules/details/dto/transaction.dto.ts

Added `/details/transactions/:address` endpoint
Added `/details/transactions/:address` endpoint

[Dashboard] Added `/details/transactions/:address` endpoint

---

packages/apps/dashboard/server/src/common/pipes/address-validation.pipe.ts
packages/apps/dashboard/server/src/modules/details/details.controller.ts
packages/apps/dashboard/server/src/modules/details/details.service.ts
packages/apps/dashboard/server/src/modules/details/dto/details-pagination.dto.ts
packages/apps/dashboard/server/src/modules/details/dto/validation/role-validation.ts

Added `/details/escrows/:address` endpoint
Added `/details/escrows/:address` endpoint.
Custom validation for a role.

[Dashboard] Added `/details/escrows/:address` endpoint

---

packages/apps/fortune/exchange-oracle/client/package.json
packages/apps/fortune/exchange-oracle/client/vite.config.ts

Fix exchange oracle client build to deploy in prod
Modify the way the build was generated by adding core to commonjsOptions

[Exchange Oracle Client] Fix prod deployment

---

package.json
packages/apps/human-app/frontend/package.json
yarn.lock

Regenerate yarn.lock because human app yarn build was not working
- Regenerate yarn.lock
- Add start:prod script
`yarn build` for HUMAN App frontend

fix yarn lock

---

packages/sdk/typescript/subgraph/.gitignore
packages/sdk/typescript/subgraph/config/amoy.json
packages/sdk/typescript/subgraph/config/avalanche.json
packages/sdk/typescript/subgraph/config/bsc-testnet.json
packages/sdk/typescript/subgraph/config/bsc.json
packages/sdk/typescript/subgraph/config/celo-alfajores.json
packages/sdk/typescript/subgraph/config/celo.json
packages/sdk/typescript/subgraph/config/ethereum.json
packages/sdk/typescript/subgraph/config/fuji.json
packages/sdk/typescript/subgraph/config/localhost.json
packages/sdk/typescript/subgraph/config/moonbase-alpha.json
packages/sdk/typescript/subgraph/config/moonbeam.json
packages/sdk/typescript/subgraph/config/polygon.json
packages/sdk/typescript/subgraph/config/sepolia.json
packages/sdk/typescript/subgraph/config/xlayer-testnet.json
packages/sdk/typescript/subgraph/config/xlayer.json
packages/sdk/typescript/subgraph/package.json
packages/sdk/typescript/subgraph/src/mapping/HMTokenTemplate.ts
packages/sdk/typescript/subgraph/template.yaml
yarn.lock

Fox HMT deployers the balance was negative in Holders entity because did not take into account the initial supply from the constructor
Create an HMToken template for the indexer service and replace the value of the contract deployer and the total supply with mustache
Deployed on local subgraph and verified the data
Closes #2271

[Subgraph] Fix hmt deployer negative balance

---

packages/apps/job-launcher/server/src/common/constants/errors.ts
packages/apps/reputation-oracle/server/src/common/constants/errors.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.dto.ts

Fix some error messages after HUMAN App UI review

Fix some error messages

---

packages/apps/human-app/frontend/src/auth-web3/wallet-connect-modal.tsx

Add the env variable in place of the modal link

fix(app/wallet-modal): add misink link

---

packages/apps/reputation-oracle/server/src/database/migrations/1721994760450-nullableSiteKey.ts
packages/apps/reputation-oracle/server/src/modules/auth/token.repository.ts
packages/apps/reputation-oracle/server/src/modules/user/user.entity.ts

Fix internal server error in email verification
Make site keys nullable
yarn test

[Reputaiton Oracle] Fix error in email verification

---

packages/apps/human-app/server/.env.example
packages/apps/human-app/server/src/app.module.ts
packages/apps/human-app/server/src/common/config/environment-config.service.ts
packages/apps/human-app/server/src/common/middleware/host-check.middleware.ts

Added middleware for checking request host.
Added middleware for checking request host to block all the requests that are being sent not to the allowed host.

[Human APP][Server] Added middleware for checking request host

---

packages/apps/job-launcher/client/index.html

Changed client description.
Set "Launch data-annotation jobs to a global workforce of annotators. Set the annotation type, budget, and desired accuracy, and receive thousands of responses."
[Job Launcher Client] Change app description
[#2330](https://github.com/humanprotocol/human-protocol/issues/2330)

[Job Launcher Client] Updated description

---

packages/apps/job-launcher/server/package.json
packages/apps/job-launcher/server/src/common/constants/index.ts
packages/apps/job-launcher/server/src/modules/job/job.controller.ts
packages/apps/job-launcher/server/src/modules/job/job.module.ts
packages/apps/job-launcher/server/src/modules/mutex/mutex-manager.service.spec.ts
packages/apps/job-launcher/server/src/modules/mutex/mutex-manager.service.ts
yarn.lock

Add mutex for job creation to avoid negative balances when several requests are received.
Add mutex manager service
yarn test

[Job Launcher] Add mutex for job creation

---

packages/apps/job-launcher/server/src/modules/auth/auth.dto.ts
packages/apps/job-launcher/server/src/modules/auth/auth.service.ts

Temporally disable hcapthca token verification from Job Launcher login
Comment verification and allow null value

[Job Launcher] Disable hcatpcha token verification in login

---

packages/sdk/typescript/subgraph/schema.graphql

Remove inmutable property from KVStore entity
Remove inmutable property from KVStore entity
`yarn test`
#2346

[Subgraph] KVStore entity

---

packages/apps/human-app/server/src/integrations/exchange-oracle/exchange-oracle.gateway.ts
packages/apps/human-app/server/src/modules/cron-job/cron-job.service.ts

The cron job fails if one the exchange oracles return an error
- Add try catch
- Remove logs to avoid token printing in logs

[HUMAN APP] Fix cron job

---

packages/apps/human-app/server/src/modules/cron-job/cron-job.service.ts
packages/apps/human-app/server/src/modules/jobs-discovery/jobs-discovery.service.ts
packages/apps/human-app/server/src/modules/jobs-discovery/spec/jobs-discovery.service.spec.ts

Add job description and reward amount to cached jobs. Also add filters
Add job description and reward amount to cached jobs. Also add filters

[Human App] Filters

---

packages/apps/fortune/exchange-oracle/server/src/modules/storage/storage.service.spec.ts
packages/apps/fortune/exchange-oracle/server/src/modules/web3/web3.service.spec.ts
packages/apps/fortune/exchange-oracle/server/src/modules/web3/web3.service.ts

Remove unused function getRpcUrl
Remove function
`yarn test`

remove unused getRpcUrl function

---

packages/apps/human-app/frontend/src/smart-contracts/contracts.ts
packages/apps/human-app/frontend/vite.config.mjs

HUMAN App is showing a white screen
Remove optimizeDeps and commonjsOptions previously added to fix sdk imports
yarn build
yarn dev

[HUMAN App] Fix frontend white screen

---

packages/apps/dashboard/ui/src/components/Header/Header.tsx

[Dashboard-UI] Changing dashboard banner

---

packages/apps/human-app/frontend/src/components/layout/drawer-menu-items/drawer-menu-items-worker.tsx
packages/apps/human-app/frontend/src/router/router-paths.ts
packages/apps/human-app/frontend/src/router/routes.tsx
packages/apps/human-app/server/src/modules/jobs-discovery/jobs-discovery.controller.ts
packages/apps/human-app/server/src/modules/jobs-discovery/spec/jobs-discovery.controller.spec.ts
packages/apps/human-app/server/src/modules/oracle-discovery/oracle-discovery.controller.ts
packages/apps/human-app/server/src/modules/oracle-discovery/spec/oracle-discovery.controller.spec.ts

Temporally disable jobs discovery before beta testing
Disable jobs discovery from both backend and fronted.

[HUMAN App] Temporally disable jobs discovery

---

packages/apps/reputation-oracle/server/src/common/pipes/validation.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.controller.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.dto.ts

Severe password restrictions removed
To close #2385

[Reputation Oracle] Severe password restrictions removed

---

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow/escrow_utils.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/statistics.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/operator/operator_utils.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/transaction/transaction_utils.py
packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/operator/test_operator_utils.py
packages/sdk/typescript/human-protocol-sdk/src/graphql/queries/statistics.ts
packages/sdk/typescript/human-protocol-sdk/src/operator.ts
packages/sdk/typescript/human-protocol-sdk/src/transaction.ts
packages/sdk/typescript/human-protocol-sdk/test/operator.test.ts

Avoid NoneType object has no attribute get errors
Check values from subgraph before assigning them
`make run-test`

[SDK][Python] Avoid NoneType object has no attribute get errors

---

packages/apps/dashboard/server/src/modules/details/dto/leader.dto.ts
packages/apps/dashboard/server/src/modules/stats/dto/hcaptcha.dto.ts
packages/apps/dashboard/server/src/modules/stats/stats.service.ts

Remove served field from hcaptcha endpoints and amountAllocated, amountLocked, lockedUntilTimestamp, reward from leaders
Remove served field from hcaptcha endpoints and amountAllocated, amountLocked, lockedUntilTimestamp, reward from leaders
#2399

[Dashboard][Server] Improve dashboard storage

---

packages/apps/fortune/exchange-oracle/server/src/modules/stats/stats.dto.ts
packages/apps/fortune/exchange-oracle/server/src/modules/stats/stats.service.ts

Updated oracle stats endpoint to match [this](https://docs.humanprotocol.org/hub/human-tech-docs/architecture/components/exchange-oracle/standard#oracle-stats)
- Updated DTO
- Updated Stats Service
`yarn test`
[Fortune Exchange Oracle] Update oracle stats endpoint
[#2359](https://github.com/humanprotocol/human-protocol/issues/2359)

[Fortune Exchange Oracle] Updated oracle stats endpoint

---

packages/apps/human-app/server/src/modules/statistics/model/oracle-statistics.model.ts
packages/apps/human-app/server/src/modules/statistics/spec/statistics.fixtures.ts

Updated oracle stats endpoint to match [this](https://docs.humanprotocol.org/hub/human-tech-docs/architecture/components/exchange-oracle/standard#oracle-stats)
- Updated DTO
- Updated Stats Service
`yarn test`
[Human App] Fetch oracle stats update
[#2360](https://github.com/humanprotocol/human-protocol/issues/2360)

[Human App] Fetch oracle stats update

---

packages/apps/human-app/server/src/modules/cron-job/cron-job.service.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts
packages/apps/reputation-oracle/server/src/modules/user/user.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/user/user.service.ts

Sometimes cannot find the keys in kvstore because have been set with different case.
- Use lowercase when writing and reading an address in/from kvstore.

[Reputation Oracle] Fix case sensitive write/read kvstore

---

packages/apps/dashboard/server/src/modules/details/details.service.ts
packages/apps/dashboard/server/src/modules/details/dto/leader.dto.ts

`address` field in `LeaderDto` is now use @expose decorator

[Dashboard][Server] `address` field in `LeaderDto` is now use @expose decorator

---

packages/apps/dashboard/server/src/common/utils/constants.ts
packages/apps/dashboard/server/src/modules/details/details.controller.ts
packages/apps/dashboard/server/src/modules/details/details.service.ts
packages/apps/dashboard/server/src/modules/details/dto/details-pagination.dto.ts
packages/apps/dashboard/server/src/modules/stats/stats.service.ts

reduce possible chain ids in requests queries
Use MainnetsId as type instead of ChainId
#2424

[Dashboard][Server] Reduce possible chain ids in requests query

---

packages/apps/reputation-oracle/server/src/modules/reputation/reputation.service.spec.ts
packages/sdk/typescript/human-protocol-sdk/package.json
yarn.lock

Remove unnecessary dependencies
Remove:
- aws-sdk
- winston
yarn test

[SDK] Remove unnecessary dependencies

---

packages/apps/human-app/frontend/src/pages/worker/profile/profile-actions.tsx

Disable Register KYC on chain button
Commented the part of the code where the button is added
#2431

[Human App] Disable Register KYC on chain button

---

docs/sdk/python/human_protocol_sdk.constants.md
docs/sdk/python/human_protocol_sdk.md
docs/sdk/typescript/base/classes/BaseEthersClient.md
docs/sdk/typescript/encryption/classes/Encryption.md
docs/sdk/typescript/encryption/classes/EncryptionUtils.md
docs/sdk/typescript/escrow/classes/EscrowClient.md
docs/sdk/typescript/escrow/classes/EscrowUtils.md
docs/sdk/typescript/kvstore/classes/KVStoreClient.md
docs/sdk/typescript/kvstore/classes/KVStoreUtils.md
docs/sdk/typescript/operator/classes/OperatorUtils.md
docs/sdk/typescript/staking/classes/StakingClient.md
docs/sdk/typescript/statistics/classes/StatisticsClient.md
docs/sdk/typescript/storage/classes/StorageClient.md
docs/sdk/typescript/transaction/classes/TransactionUtils.md

Regenerate sdk docs

---

packages/apps/human-app/frontend/src/pages/worker/hcaptcha-labeling/hcaptcha-labeling/hcaptcha-labeling.page.tsx

Fixed `canSolveCaptcha` condition
Using AND instead of OR:
```
const canSolveCaptcha =
dailyHmtSpent &&
hcaptchaUserStats &&
hcaptchaUserStats.solved < env.VITE_DAILY_SOLVED_CAPTCHA_LIMIT &&
dailyHmtSpent.spend < env.VITE_HMT_DAILY_SPENT_LIMIT;
```

[Human APP][Frontend] Fixed `canSolveCaptcha` condition

---

packages/apps/dashboard/server/src/modules/details/details.service.ts

Added reputation for `/details/{address}` endpoint
For `/details/{address}` endpoint added reputation fetching from reputation oracle.
Closes #2456

[Dashboard][Server] Added reputation for `/details/{address}` endpoint

---

packages/apps/dashboard/server/src/modules/stats/stats.service.ts

`fetchAndCacheHmtDailyStats` is returning the data for Ethereum network
Modify `fetchAndCacheHmtDailyStats` to query all networks and sum all values before caching them
#2455

[Dashboard] stats/hmt/daily returning wrong data

---

packages/apps/fortune/recording-oracle/src/modules/job/job.service.spec.ts
packages/apps/fortune/recording-oracle/src/modules/job/job.service.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts
packages/apps/job-launcher/server/src/modules/qualification/qualification.service.spec.ts
packages/apps/job-launcher/server/src/modules/qualification/qualification.service.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts
packages/apps/reputation-oracle/server/src/modules/user/user.service.ts
packages/sdk/typescript/human-protocol-sdk/src/error.ts
packages/sdk/typescript/human-protocol-sdk/src/kvstore.ts

Check all references to `KVStoreUtils.get` method and update them to handle exceptions properly to avoid errors
Handle exceptions on `KVStoreUtils.get`
`yarn test`
#2435

KVStoreUtils get method error handling

---

packages/apps/dashboard/ui/index.html
packages/apps/dashboard/ui/src/components/Header/Header.tsx
packages/apps/dashboard/ui/src/routes/routes.ts
packages/apps/human-app/frontend/src/smart-contracts/chains.ts
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/constants.py
packages/sdk/typescript/human-protocol-sdk/src/constants.ts

Allow only see the faucet in the legacy dashboard so that users can still have a faucet after new dashboard release

[Faucet] Turn legacy dashboard into faucet only

---

packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts
packages/apps/reputation-oracle/server/src/modules/user/user.repository.ts

Add qualifications to JWT
Add qualifications to user's relations in user repository
Add qualifications to access token payload
`yarn test`
#2468

[Reputation Oracle] Add Qualifications to JWT

---

packages/apps/human-app/frontend/src/smart-contracts/EthKVStore/config.ts

Fix the role Job Launcher to use upper case.

[HUMAN App] Fix the role Job Launcher to use upper case

---

packages/apps/dashboard/ui-2024/src/utils/config/networks.ts

update(dashboard/ui-2024): remove unwanted chain id

---

packages/apps/job-launcher/client/src/components/Disclaimer/BetaDisclaimer.tsx
packages/apps/job-launcher/client/src/layouts/DefaultLayout.tsx
packages/apps/job-launcher/client/src/layouts/index.tsx

Add a disclaimer to Job Launcher UI saying:
"This is a Beta version, please contact us here: https://calendly.com/saqib-hmt/20min"
#2287

[Job Launcher Client] Add beta disclaimer

---

packages/apps/human-app/server/src/common/config/params-decorators.ts
packages/apps/human-app/server/src/common/filter/global-exceptions.filter.ts
packages/apps/human-app/server/src/integrations/h-captcha-labeling/h-captcha-verify.gateway.ts
packages/apps/human-app/server/src/modules/cron-job/cron-job.service.ts

Fix crashing issue and add some logs

[Human App] Fix crashing issue and add some logs

---

docs/sdk/typescript/base/classes/BaseEthersClient.md
docs/sdk/typescript/encryption/classes/Encryption.md
docs/sdk/typescript/encryption/classes/EncryptionUtils.md
docs/sdk/typescript/escrow/classes/EscrowClient.md
docs/sdk/typescript/escrow/classes/EscrowUtils.md
docs/sdk/typescript/kvstore/classes/KVStoreClient.md
docs/sdk/typescript/kvstore/classes/KVStoreUtils.md
docs/sdk/typescript/operator/classes/OperatorUtils.md
docs/sdk/typescript/staking/classes/StakingClient.md
docs/sdk/typescript/statistics/classes/StatisticsClient.md
docs/sdk/typescript/storage/classes/StorageClient.md
docs/sdk/typescript/transaction/classes/TransactionUtils.md
packages/sdk/typescript/human-protocol-sdk/src/encryption.ts

Fix writing errores in encryption docs

Fix writing errores in encryption docs 

---

packages/apps/human-app/frontend/src/pages/homepage/update-version-modal.tsx

Update welcome message
Remove hyphen and update text in `update-version-modal.tsx`

[Human App] Update welcome message

---

packages/apps/dashboard/server/src/modules/details/details.service.ts
packages/apps/dashboard/server/src/modules/details/dto/transaction.dto.ts
packages/sdk/python/human-protocol-sdk/example.py
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/transaction.py
packages/sdk/typescript/human-protocol-sdk/src/graphql/queries/transaction.ts
packages/sdk/typescript/human-protocol-sdk/src/transaction.ts

Fixed get transactions
- Updated Dashboard server
- Added negative symbol for outgoing transactions.
- Updated Typescript SDK
- Update Python SDK
`http://localhost:3001/search/137/0xFB134E202d1eFdC2a8954AA0fF76589f6766Cc52`
[Dashboard] Dashboard is not showing any transaction
[#2508](https://github.com/humanprotocol/human-protocol/issues/2508)

[Dashboard] Fixed get transactions

---

packages/apps/dashboard/ui-2024/src/components/Search/Search.tsx
packages/apps/dashboard/ui-2024/src/helpers/formatHMTDecimals.ts
packages/apps/dashboard/ui-2024/src/pages/SearchResults/WalletAddress/WalletAddress.tsx
packages/apps/dashboard/ui-2024/src/pages/SearchResults/WalletAddress/WalletAddressTransactions/cells/TransactionTableCellValue.tsx

In this pull request, the following tasks have been completed:
HDM-7
HDM-8
HDM-9
HDM-10

[dashboard] improvements-20-09-2024

---

packages/apps/human-app/frontend/src/api/services/worker/available-jobs-data.ts
packages/apps/human-app/frontend/src/api/services/worker/my-jobs-data.ts
packages/apps/human-app/frontend/src/pages/worker/jobs/components/available-jobs/desktop/available-jobs-table.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs/components/my-jobs/desktop/my-jobs-table.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs/components/my-jobs/mobile/my-jobs-table-mobile.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs/components/reward-amount.tsx

Reward amount in a response schema changed to string.
1. `url` might be null
2. `reward_amount` changed to string
To close #2537

[Human APP][Frontend] `reward_amount` to string

---

packages/apps/human-app/frontend/src/shared/helpers/format-date.ts

Expires at column will show now a full timestamp (with hrs, mins, secs)
Changed the way of showing assignment expiration time.

[Human APP][Frontend] Show an exact assignment expiration time

---

packages/apps/job-launcher/client/src/components/Jobs/Create/CvatJobRequestForm.tsx
packages/apps/job-launcher/client/src/components/Jobs/Create/FortuneJobRequestForm.tsx
packages/apps/job-launcher/client/src/components/Jobs/Create/HCaptchaJobRequestForm.tsx

Add a hint to qualifications input
Create a new title for Qualifications and add a hint next to it
#2547

[Job Launcher Client] Add hint to qualifications field

---

packages/apps/fortune/exchange-oracle/server/src/modules/job/job.dto.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts
packages/apps/human-app/server/src/integrations/exchange-oracle/exchange-oracle.gateway.ts

Change reward_amount to string to follow standardard defined

[Fortune Exchange Oracle] Change reward_amount to string

---

packages/apps/human-app/frontend/src/i18n/en.json
packages/apps/human-app/frontend/src/pages/homepage/update-version-modal.tsx

Update links in updateVersionModal to be able to switch properly to dark mode
Changed `a` to `Link` to use the app theme
Added translations to texts 
Check updated version modal on frontend startup

[Human App frontend] Fix UpdateVersionModal links colors

---

packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.repository.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.spec.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts
packages/apps/fortune/recording-oracle/src/modules/job/job.service.ts

Fix system when two users send the same solution
- Update algorithm of classifying workers's solutions in recording oracle
- Update assignment status of rejected solutions in exchange oracle
- Create a new job
- Send two solutions from two different users with the same value
- The first solution is going to be accepted and the second one rejected

[Recording Oracle][Exchange Oracle] Fix duplicated solutions

---

packages/apps/human-app/server/.env.example
packages/apps/human-app/server/src/modules/cron-job/cron-job.service.ts

Fixed crashing error.
Added error handler to `updateJobsListCron`.
`export FEATURE_FLAG_JOBS_DISCOVERY='true'`
Run **cron**.
[HUMAN App] Crashing error
[#2548](https://github.com/humanprotocol/human-protocol/issues/2548)

[HUMAN App] Fixed crashing error

---

packages/apps/human-app/frontend/src/components/layout/drawer-menu-items/drawer-menu-items-worker.tsx
packages/apps/human-app/frontend/src/i18n/en.json
packages/apps/human-app/frontend/src/router/router.tsx

Disable Hcaptcha Labeling and Job Discovery for non approved users
Disabled Hcaptcha Labeling and Job Discovery for non approved users
Added default redirect for unrecognised routes
When user is logged in and he doesn't have kyc approved, both labels will apear disabled

[Human App] Disable Hcaptcha Labeling and Job Discovery for non approved users

---

packages/apps/job-launcher/server/src/modules/encryption/encryption.module.ts

Fix condition for pgp encryption enablement

Fix condition for pgp encryption enablement

---

packages/apps/job-launcher/server/src/common/guards/whitelist.auth.ts
packages/apps/job-launcher/server/src/database/database.module.ts
packages/apps/job-launcher/server/src/database/migrations/1728056930604-whitelist.ts
packages/apps/job-launcher/server/src/database/migrations/1728374018070-whitelist.ts
packages/apps/job-launcher/server/src/modules/payment/payment.controller.ts
packages/apps/job-launcher/server/src/modules/payment/payment.module.ts
packages/apps/job-launcher/server/src/modules/user/user.entity.ts
packages/apps/job-launcher/server/src/modules/whitelist/whitelist.entity.ts
packages/apps/job-launcher/server/src/modules/whitelist/whitelist.module.ts
packages/apps/job-launcher/server/src/modules/whitelist/whitelist.repository.ts
packages/apps/job-launcher/server/src/modules/whitelist/whitelist.service.spec.ts
packages/apps/job-launcher/server/src/modules/whitelist/whitelist.service.ts

Implement a whitelist of users who will be allowed to continue using crypto payments
Create a new whitelist module to access whilelist table
Create a new whitelist guard 
Generate new migration with the changes
Try to register a crypto payment without adding your user to whitelist table
#2581

[Job Launcher] Crypto payments for whitelisted users

---

packages/apps/job-launcher/server/src/modules/payment/payment.controller.ts

Comment whitelist decorator to disable it untill we have billing system

[Job Launcher] Comment whitelist

---

packages/examples/cvat/exchange-oracle/src/core/config.py
packages/examples/cvat/exchange-oracle/src/endpoints/authentication.py
packages/examples/cvat/exchange-oracle/tests/api/test_exchange_api.py

Changed JWT decoding algorithm from `HS256` to `ES256`.

[CVAT][Exchange Oracle] Changed JWT algo from HS256 to ES256

---

packages/apps/fortune/exchange-oracle/server/scripts/set-manifest-url.ts

Fix the script that reads manifest urls from the blockchain and set them in the database in the new column manifest_url
- Add load env
- Remove private key requirement
- Lint

[Fortune Exchange Oracle] Fix script to set manifests urls

---

packages/apps/job-launcher/server/src/modules/auth/auth.service.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts

Fix expiration date for forgot password tokens
- Multiply the value by 1000 convert to ms.

Fix expiration date for forgot password tokens

---

packages/examples/cvat/exchange-oracle/src/core/config.py
packages/examples/cvat/exchange-oracle/src/crons/_cron_job.py
packages/examples/cvat/exchange-oracle/src/crons/cvat/state_trackers.py
packages/examples/cvat/exchange-oracle/src/services/cvat.py
packages/examples/cvat/exchange-oracle/tests/conftest.py
packages/examples/cvat/exchange-oracle/tests/integration/cron/state_trackers/test_track_completed_escrows.py

Fix bug in `track_completed_tasks` as well as flaw in tests that made this bug unnoticed.
- Fix complete_tasks_with_completed_jobs return type
- Prevent swallowing exceptions in state trackers while testing
- Fix track completed escrows tests

[CVAT][Exchange Oracle] Fix track completed tasks

---

packages/examples/cvat/exchange-oracle/src/endpoints/exchange.py
packages/examples/cvat/exchange-oracle/src/endpoints/serializers.py

Fix exchange serialization/retrieval for deleted projects
- Add PROJECT_COMPLETED_STATUSES to account for deleted status

[CVAT][Exchange Oracle] Fix exchange API for deleted projects

---

packages/apps/dashboard/server/src/common/config/network-config.service.ts
packages/apps/dashboard/server/src/common/utils/constants.ts

Add eth to mainnets and add env variable for RPC

[Dashboard] Add eth to mainnets and add env variable for RPC

---

packages/apps/fortune/exchange-oracle/server/src/modules/user/user.controller.ts
packages/apps/human-app/frontend/src/api/api-paths.ts
packages/apps/human-app/frontend/src/api/services/worker/oracles.ts
packages/apps/human-app/frontend/src/api/services/worker/user-registration.ts
packages/apps/human-app/frontend/src/i18n/en.json
packages/apps/human-app/frontend/src/pages/worker/registration/registration.page.tsx
packages/apps/human-app/server/src/integrations/exchange-oracle/exchange-oracle.gateway.ts
packages/apps/human-app/server/src/integrations/exchange-oracle/exchange-oracle.mapper.profile.ts
packages/apps/human-app/server/src/integrations/exchange-oracle/spec/exchange-oracle.gateway.mock.ts
packages/apps/human-app/server/src/integrations/exchange-oracle/spec/exchange-oracle.gateway.spec.ts
packages/apps/human-app/server/src/integrations/reputation-oracle/reputation-oracle.gateway.ts
packages/apps/human-app/server/src/integrations/reputation-oracle/reputation-oracle.mapper.profile.ts
packages/apps/human-app/server/src/integrations/reputation-oracle/spec/reputation-oracle.gateway.spec.ts
packages/apps/human-app/server/src/modules/user-worker/model/worker-registration.model.ts
packages/apps/human-app/server/src/modules/user-worker/spec/worker.controller.spec.ts
packages/apps/human-app/server/src/modules/user-worker/spec/worker.fixtures.ts
packages/apps/human-app/server/src/modules/user-worker/spec/worker.service.mock.ts
packages/apps/human-app/server/src/modules/user-worker/spec/worker.service.spec.ts
packages/apps/human-app/server/src/modules/user-worker/worker.controller.ts
packages/apps/human-app/server/src/modules/user-worker/worker.mapper.profile.ts
packages/apps/human-app/server/src/modules/user-worker/worker.service.ts
packages/apps/reputation-oracle/server/src/modules/user/user.controller.ts
packages/apps/reputation-oracle/server/src/modules/user/user.dto.ts
packages/apps/reputation-oracle/server/src/modules/user/user.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/user/user.service.ts

Fix registration page and rename registration-related stuff from Register to Registration
Fix registration page and rename registration-related stuff from Register to Registration
Try to see jobs from an exchange oracle that has registration enabled in Human App. You'll see the new page with the instructions to register

Worker registration

---

packages/apps/human-app/frontend/src/components/ui/chip.tsx
packages/apps/human-app/frontend/src/i18n/en.json
packages/apps/human-app/frontend/src/pages/worker/jobs/components/available-jobs/mobile/available-jobs-table-mobile.tsx

(HUM-64): change copy, wrap whitespace, move chip to next line

---

packages/apps/human-app/frontend/src/components/ui/page-card.tsx

(HUM-62): mobile padding for content without cards

---

packages/apps/human-app/frontend/src/i18n/en.json
packages/apps/human-app/frontend/src/pages/worker/jobs-discovery/components/oracles-table/oracles-table-job-types-select.tsx

HUM-54: change copy

---

packages/apps/human-app/frontend/src/pages/worker/jobs/jobs.page.tsx

(HUM-57): dm round corners

---

packages/apps/human-app/frontend/src/components/layout/protected/drawer-navigation.tsx
packages/apps/human-app/frontend/src/components/layout/protected/navbar.tsx

Hum 35 check paddings in navbar

---

packages/apps/human-app/frontend/src/components/layout/protected/layout.tsx

Hum 44 overlap with some layout element blocks UI interaction

---

packages/apps/human-app/frontend/src/api/services/worker/assign-job.ts
packages/apps/human-app/frontend/src/pages/worker/jobs/components/available-jobs/desktop/available-jobs-table.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs/components/available-jobs/mobile/available-jobs-table-mobile.tsx

Hum 45 possibility to click on select job while one is in progress

---

packages/apps/human-app/frontend/src/components/data-entry/input.tsx

(HUM-51): dm dark mode white autofill

---

packages/apps/human-app/frontend/src/pages/worker/jobs-discovery/components/oracles-table/oracles-table-mobile.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs/components/evm-address.tsx

HUM-55: dm address color on mobile

---

packages/apps/human-app/frontend/src/components/ui/chip.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs/components/available-jobs/mobile/available-jobs-table-mobile.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs/components/my-jobs/desktop/my-jobs-table.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs/components/my-jobs/mobile/my-jobs-table-mobile.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs/jobs.page.tsx

Hum 38 invalid status chip color on mobile

---

packages/apps/human-app/frontend/src/pages/worker/jobs/components/my-jobs/desktop/my-jobs-table.tsx

fix(human-app/frontend): build error

---

packages/apps/human-app/frontend/src/pages/worker/hcaptcha-labeling/hcaptcha-labeling/hcaptcha-labeling.page.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs-discovery/jobs-discovery.page.tsx
packages/apps/human-app/frontend/src/router/router.tsx

[HUM-48] fix router issues

---

packages/apps/human-app/frontend/src/components/ui/table-button.tsx
packages/apps/human-app/frontend/src/pages/homepage/components/welcome.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs/components/available-jobs/desktop/available-jobs-table.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs/components/reject-button.tsx
packages/apps/human-app/frontend/src/styles/color-palette.ts
packages/apps/human-app/frontend/src/styles/dark-color-palette.ts

(HUM-52): dm button colors and states

---

packages/apps/job-launcher/client/src/pages/Job/JobDetail/index.tsx

Fix for enums conversion to lower case caused by #2610

Fix for enums conversion to lower case.

---

packages/apps/human-app/frontend/src/components/ui/no-records.tsx
packages/apps/human-app/frontend/src/hooks/use-get-oracles-notifications.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs-discovery/components/oracles-table/oracles-table-mobile.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs-discovery/jobs-discovery.page.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs/jobs.page.tsx

(HUM-46): fix no error messages for jobs discovery when data load fails

---

packages/apps/human-app/frontend/src/components/layout/protected/drawer-navigation.tsx

(HUM-59): menu mobile font size fix

---

packages/examples/cvat/exchange-oracle/src/core/config.py
packages/examples/cvat/exchange-oracle/src/core/tasks/simple.py
packages/examples/cvat/exchange-oracle/src/core/types.py
packages/examples/cvat/exchange-oracle/src/handlers/job_creation.py
packages/examples/cvat/exchange-oracle/tests/utils/manifest.json
packages/examples/cvat/exchange-oracle/tests/utils/setup_cvat.py
packages/examples/cvat/recording-oracle/src/core/tasks/simple.py
packages/examples/cvat/recording-oracle/src/core/types.py
packages/examples/cvat/recording-oracle/tests/utils/manifest.json

- Align task type names with other components
Note, that there is no data migration added (this is in line with other enum name changes made recently). Older manifests are not expected to be used.

[CVAT] Move to lowercase task type names

---

packages/apps/human-app/frontend/src/components/data-entry/multi-select.tsx
packages/apps/human-app/frontend/src/styles/dark-theme.ts
packages/apps/human-app/frontend/src/styles/theme.ts

(HUM-60): fix dropdown icon color in jobs discovery

---

packages/examples/cvat/exchange-oracle/src/schemas/exchange.py
packages/examples/cvat/exchange-oracle/tests/api/test_exchange_api.py

Job/assignment statuses transformed to a lower case in API responses
To align with changes in #2610

[CVAT][Exchange Oracle] Job and assignments statuses to lowercase

---

packages/apps/human-app/frontend/src/pages/homepage/components/chat.tsx

(HUM-70): align chat icon with figma

---

packages/examples/cvat/exchange-oracle/docker-compose.dev.yml

- Makes dev minio data persistent across container restarts

[CVAT] Add persistence to dev minio

---

packages/examples/cvat/exchange-oracle/src/cvat/api_calls.py
packages/examples/cvat/exchange-oracle/src/handlers/job_creation.py
packages/examples/cvat/exchange-oracle/src/utils/assignments.py

Depends on https://github.com/cvat-ai/cvat/pull/8634, https://github.com/cvat-ai/cvat/pull/8635
- Changed image_points task to use single shape mode and have just 1 annotation with multiple points

[CVAT] Update image_points task 

---

packages/apps/fortune/exchange-oracle/server/src/common/interceptors/transform-enum.interceptor.ts
packages/apps/fortune/exchange-oracle/server/src/common/pagination/pagination.dto.ts
packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.controller.spec.ts
packages/apps/human-app/frontend/.eslintrc.cjs
packages/apps/human-app/frontend/src/api/api-paths.ts
packages/apps/human-app/frontend/src/api/services/worker/refresh-tasks.ts
packages/apps/human-app/frontend/src/components/ui/icons.tsx
packages/apps/human-app/frontend/src/components/ui/table/table-header-cell.tsx
packages/apps/human-app/frontend/src/contexts/homepage-state.tsx
packages/apps/human-app/frontend/src/contexts/registered-oracles.tsx
packages/apps/human-app/frontend/src/i18n/en.json
packages/apps/human-app/frontend/src/pages/worker/jobs/components/my-jobs/desktop/my-jobs-table.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs/components/my-jobs/mobile/my-jobs-table-mobile.tsx
packages/apps/human-app/server/src/main.ts

Add refresh button to my tasks table
Add a refresh button to refresh user's jobs in Human App
Test "my jobs" section and click refresh
#2723

[HUMAN App Client] Add refresh button to my tasks table

---

packages/apps/human-app/server/src/app.module.ts
packages/apps/human-app/server/src/common/config/environment-config.service.ts
packages/apps/human-app/server/src/modules/job-assignment/job-assignment.service.ts
packages/apps/human-app/server/src/modules/job-assignment/spec/job-assignment.service.spec.ts

Rename env variable CACHE_TTL_JOB_ASSIGNMENTS to JOB_ASSIGNMENTS_DATA_RETENTION_DAYS in HUMAN App

[HUMAN App] Rename CACHE_TTL_JOB_ASSIGNMENTS to JOB_ASSIGNMENTS_DATA_RETENTION_DAYS

---

packages/apps/fortune/exchange-oracle/client/src/providers/WagmiProvider.tsx
packages/apps/job-launcher/client/src/providers/WagmiProvider.tsx

NaN is being showed in amounts when we try to pay for an escrow with card
Add default transport for wagmi config
Open JL Frontend and check if fee percentage is being loaded
#2731

[Job Launcher client] NaN amounts

---

packages/apps/human-app/frontend/src/api/services/worker/oracles.ts
packages/apps/human-app/frontend/src/components/layout/drawer-menu-items/drawer-menu-items-worker.tsx
packages/apps/human-app/frontend/src/router/routes.tsx

Release fix #2753

---

packages/sdk/typescript/subgraph/src/mapping/KVStore.ts

Fix case changes introduced here #2600
Updated comparison in Subgraph from uppercase to lowercase
Deployed fortune locally and registered a new oracle in Reputation Oracle
Subgraph has to be deployed
None

[Subgraph] Fix uppercase error when registering a new oracle

---

packages/apps/fortune/exchange-oracle/server/src/common/enums/collection.ts
packages/apps/fortune/exchange-oracle/server/src/common/pagination/pagination.dto.ts
packages/apps/fortune/exchange-oracle/server/src/database/database.enum.ts
packages/apps/fortune/exchange-oracle/server/src/database/database.utils.ts
packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.repository.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.repository.ts
packages/apps/job-launcher/server/src/common/enums/collection.ts
packages/apps/job-launcher/server/src/database/database.enum.ts
packages/apps/job-launcher/server/src/database/database.utils.ts
packages/apps/job-launcher/server/src/modules/job/job.repository.ts

Enums conversion done in #2600
Convert SortDirection to lower case
None
Deploy Ex Oracle
None

Convert SortDirection to lowercase

---

packages/apps/human-app/frontend/src/pages/worker/jobs/components/available-jobs/desktop/available-jobs-table.tsx

(HUM-71): select task button has no margin

---

packages/apps/human-app/frontend/src/pages/worker/jobs/components/available-jobs/mobile/available-jobs-drawer-mobile.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs/components/available-jobs/mobile/available-jobs-table-mobile.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs/components/my-jobs/mobile/my-jobs-drawer-mobile.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs/components/reward-amount.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs/jobs.page.tsx

(HUM-43): fix filters for jobs tables not opening as expected on mobile devices

---

packages/examples/cvat/exchange-oracle/src/crons/webhooks/_common.py
packages/examples/cvat/exchange-oracle/src/crons/webhooks/job_launcher.py
packages/examples/cvat/exchange-oracle/src/crons/webhooks/recording_oracle.py
packages/examples/cvat/exchange-oracle/src/crons/webhooks/reputation_oracle.py
packages/examples/cvat/recording-oracle/src/crons/_utils.py
packages/examples/cvat/recording-oracle/src/crons/process_exchange_oracle_webhooks.py

Fixes the problem discovered in https://github.com/humanprotocol/human-protocol/actions/runs/11839479631/job/32991004141?pr=2780
- Oracles should correctly accumulate processing attempts and change statuses both for inbox and outbox queues

[CVAT] Fix invalid webhook handling in oracles

---

packages/examples/cvat/exchange-oracle/src/crons/webhooks/recording_oracle.py
packages/examples/cvat/exchange-oracle/src/endpoints/exchange.py
packages/examples/cvat/exchange-oracle/src/endpoints/serializers.py
packages/examples/cvat/exchange-oracle/src/models/cvat.py
packages/examples/cvat/exchange-oracle/src/services/cvat.py
packages/examples/cvat/exchange-oracle/tests/api/test_exchange_api.py
packages/examples/cvat/exchange-oracle/tests/integration/cron/test_process_recording_oracle_webhooks.py

- Removed projects in intermediate states (`completed`, `validation`) from `/job` responses
- Added updating of final assignments on escrow finishing. This is needed to align implicit state updates with the `updated_at` filter in API

[CVAT] Oracle API updates

---

packages/examples/cvat/recording-oracle/src/crons/process_exchange_oracle_webhooks.py
packages/examples/cvat/recording-oracle/src/endpoints/webhook.py
packages/examples/cvat/recording-oracle/src/handlers/validation.py
packages/examples/cvat/recording-oracle/tests/integration/cron/test_process_exchange_oracle_webhooks.py

In Recording Oracle:
- Changed escrow validation from endpoint handler to queue handler
- Changed the list of acceptable escrow states for escrow cleanup event

[CVAT] Move escrow validation to before handling

---

packages/apps/human-app/frontend/src/api/services/worker/oracles.ts
packages/apps/human-app/frontend/src/pages/worker/jobs-discovery/components/oracles-table/oracles-table-mobile.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs-discovery/components/oracles-table/oracles-table.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs-discovery/jobs-discovery.page.tsx

N/A
Follow up to https://github.com/humanprotocol/human-protocol/pull/2816: changing schema on UI, so response validation doesn't fail
Merge & deploy
No

[Human App] fix: oracle discovery schema

---

packages/apps/reputation-oracle/server/src/modules/cron-job/cron-job.service.ts

N/A
Changed escrow desired status to Pending in escrow completion tracker.
Locally
N/A
N/A

[Reputation Oracle] fix: changed escrow desired status to Pending

---

packages/examples/cvat/exchange-oracle/src/endpoints/exchange.py
packages/examples/cvat/exchange-oracle/tests/api/test_exchange_api.py

- Fixed the problem in the `/job` endpoint that if there are several projects under one escrow, completed projects could shadow ones in the `annotation` status, and such escrows would be hidden from the response after
Unit test
Manual test

[CVAT] Fix job retrieval from db in /job endpoint

---

packages/examples/cvat/exchange-oracle/src/handlers/job_creation.py

- Improved target quality setting for the point annotation task
- Improved the reasoning comment

[CVAT] Improve quality setup for point annotation task

---

packages/apps/human-app/frontend/src/pages/worker/jobs/components/my-jobs-table-actions.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs/components/my-jobs/desktop/my-jobs-table.tsx
packages/apps/human-app/frontend/src/pages/worker/jobs/components/my-jobs/mobile/my-jobs-table-mobile.tsx

[HUM-77] implement loading state on resign btn for a specific job

---

packages/apps/job-launcher/client/src/pages/Job/JobDetail/index.tsx

#2817
Remove unused fields from job details
None
None

[Job Launcher client] Remove fields from job details 

---

packages/apps/dashboard/server/package.json

Fix production start script 
Fix script `start:prod`
Run locally 
NA
NA

fix start:prod script

---

packages/apps/human-app/frontend/src/components/data-entry/input.tsx
packages/apps/human-app/frontend/src/hooks/use-web3-provider.tsx
packages/apps/human-app/frontend/src/pages/worker/profile/wallet-connect-done.tsx

[HUM-80] fix: fix type assertion in web3 provider hook

---

packages/core/.openzeppelin/bsc-testnet.json
packages/core/.openzeppelin/sepolia.json
packages/core/.openzeppelin/unknown-80002.json
packages/core/contracts/EscrowFactory.sol
packages/core/contracts/test/EscrowFactoryV0.sol
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/constants.py
packages/sdk/typescript/human-protocol-sdk/src/constants.ts
packages/sdk/typescript/subgraph/template.yaml

Issue caused by PR #2576 
Fix events indexing issue caused by adding `indexed` to escrow factory contract events 
Remove `indexed` and redeploy contracts and subgraph
Deployed and verified on subgraph
NA
NA

[Subgraph] Events indexing issue

---

packages/apps/dashboard/server/package.json
packages/apps/faucet/server/package.json
packages/apps/fortune/exchange-oracle/server/package.json
packages/apps/fortune/recording-oracle/package.json
packages/apps/human-app/server/package.json
packages/apps/job-launcher/server/package.json
packages/apps/reputation-oracle/server/package.json
yarn.lock

Reverts humanprotocol/human-protocol#2809
It breaks faucet server

Revert "chore(deps-dev): bump @types/express from 4.17.21 to 5.0.0"

---

packages/apps/dashboard/ui-2024/src/features/Leaderboard/components/DataGridWrapper.tsx

HDM-32
I removed initial sorting and data will we displayed as it is received from backend
reloading app to see if rows are in correct order
normal deploy

HDM-32: fix table row order

---

packages/apps/dashboard/ui-2024/src/assets/styles/color-palette.ts
packages/apps/dashboard/ui-2024/src/components/SearchResults/AbbreviateClipboard.tsx
packages/apps/dashboard/ui-2024/src/pages/SearchResults/RoleDetails/RoleDetailsEscrows/tableComponents/EscrowsTableBody.tsx
packages/apps/dashboard/ui-2024/src/theme.tsx

HDM-23
Update link colors in different states
manually
normal deploy

HDM-23: update link colors for hover/visited states

---

packages/apps/job-launcher/client/src/components/BillingDetails/BillingDetailsModal.tsx
packages/apps/job-launcher/client/src/components/Jobs/Create/FiatPayForm.tsx
packages/apps/job-launcher/client/src/components/Jobs/Create/FundingMethod.tsx
packages/apps/job-launcher/client/src/components/Jobs/Create/PayJob.tsx
packages/apps/job-launcher/client/src/components/TopUpAccount/CryptoTopUpForm.tsx
packages/apps/job-launcher/client/src/components/TopUpAccount/TopUpMethod.tsx
packages/apps/job-launcher/client/src/pages/Profile/Settings/index.tsx
packages/apps/job-launcher/client/src/pages/Profile/TopUpAccount/index.tsx
packages/apps/job-launcher/client/src/state/auth/reducer.ts
packages/apps/job-launcher/client/src/state/auth/types.ts
packages/apps/job-launcher/client/src/utils/jwt.ts
packages/apps/job-launcher/server/src/common/guards/whitelist.auth.spec.ts
packages/apps/job-launcher/server/src/modules/auth/auth.module.ts
packages/apps/job-launcher/server/src/modules/auth/auth.service.spec.ts
packages/apps/job-launcher/server/src/modules/auth/auth.service.ts
packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.ts
packages/apps/job-launcher/server/src/modules/payment/payment.controller.ts
packages/apps/job-launcher/server/src/modules/payment/payment.service.ts

NA
- Enable whitelist. Allow only whitelisted users to use crypto payments.
- Fix some UI issues for billing system
- Runing backend and frontend locally
- Unit tests
Add list of whitelisted users
NA

[Job Launcher] Enable whitelist and fix some UI issues for billing system

---

packages/apps/dashboard/ui-2024/src/assets/styles/_header.scss
packages/apps/dashboard/ui-2024/src/assets/styles/_page-wrapper.scss
packages/apps/dashboard/ui-2024/src/assets/styles/_search.scss
packages/apps/dashboard/ui-2024/src/components/Header/Header.tsx
packages/apps/dashboard/ui-2024/src/components/PageWrapper/PageWrapper.tsx
packages/apps/dashboard/ui-2024/src/components/SearchBar/SearchBar.styles.ts
packages/apps/dashboard/ui-2024/src/components/SearchBar/SearchBar.tsx
packages/apps/dashboard/ui-2024/src/pages/Graph/Graph.tsx
packages/apps/dashboard/ui-2024/src/pages/Leaderboard/index.tsx
packages/apps/dashboard/ui-2024/src/pages/SearchResults/SearchResults.tsx

HDM-34
Remove SearchBar component from header and refactor to simplify component
I checked all pages and SearchBar functionality
normal deploy

Hdm 34 remove address search from header

---

packages/apps/job-launcher/client/src/pages/Job/JobDetail/index.tsx

#2877
Show network name instead of ChainId
None
None

[Job Launcher Client] Show network name

---

packages/apps/job-launcher/client/src/components/BillingDetails/BillingDetailsModal.tsx
packages/apps/job-launcher/client/src/components/CreditCard/SelectCardModal.tsx
packages/apps/job-launcher/client/src/components/Jobs/Create/FiatPayForm.tsx
packages/apps/job-launcher/client/src/components/TopUpAccount/FiatTopUpForm.tsx
packages/apps/job-launcher/client/src/pages/Profile/Settings/index.tsx
packages/apps/job-launcher/server/src/modules/payment/payment.service.ts

#2882
- Add circular progress when loading card and billing data 
- Refactor billing details to fix some errors with null values
- Fix errors when getting fee data from KVStore contract
None
None

Add circular progress when loading card data and refactor billing details modal

---

packages/apps/dashboard/ui-2024/src/features/Leaderboard/components/ChainCell.tsx
packages/apps/dashboard/ui-2024/src/features/Leaderboard/hooks/useDataGrid.tsx

HDM-36
Simple CSS edit for mobile 
manually tested table to check if it displays correctly
normal deploy

HDM-36: wrap white space for network column (mobile)

---

packages/examples/cvat/exchange-oracle/poetry.lock
packages/examples/cvat/exchange-oracle/pyproject.toml
packages/examples/cvat/recording-oracle/poetry.lock
packages/examples/cvat/recording-oracle/pyproject.toml

- Updated uvicorn to avoid https://github.com/encode/uvicorn/discussions/2450
- Updated cvat_sdk to a more recent version
Local testing for multithreaded deployment, parallel request processing in 10 workers / 20 request threads.

Upgrade uvicorn dep

---

packages/core/scripts/deploy-proxies.ts
packages/core/scripts/deploy.ts

None
Remove some old configuration for proxies scripts and update variables
Launched locally
None
None

[CVAT] Fix CVAT tests not running

---

packages/examples/cvat/exchange-oracle/src/core/config.py
packages/examples/cvat/exchange-oracle/src/handlers/completed_escrows.py
packages/examples/cvat/exchange-oracle/src/services/cvat.py
packages/examples/cvat/exchange-oracle/tests/integration/cron/state_trackers/test_track_completed_escrows.py

- Fixed handling of escrow validations in the case of multiple parallel processes

[CVAT] Fix parallel escrow validations

---

packages/apps/dashboard/server/src/modules/details/details.service.ts
packages/apps/dashboard/server/src/modules/details/dto/transaction.dto.ts
packages/apps/dashboard/ui-2024/src/assets/styles/color-palette.ts
packages/apps/dashboard/ui-2024/src/components/SearchResults/AbbreviateClipboard.tsx
packages/apps/dashboard/ui-2024/src/pages/SearchResults/WalletAddress/WalletAddressTransactions/cells/TransactionTableCellMethod.tsx
packages/apps/dashboard/ui-2024/src/pages/SearchResults/WalletAddress/WalletAddressTransactions/tableComponents/TransactionsTableBody.tsx
packages/apps/dashboard/ui-2024/src/pages/SearchResults/WalletAddress/WalletAddressTransactions/tableComponents/TransactionsTableHead.tsx
packages/apps/dashboard/ui-2024/src/services/api/use-transaction-details.tsx

#2898
Update transaction table format to the new transaction schema
Update server to include new internalTransaction field
None
None

[Dashboard] Transactions table

---

packages/apps/dashboard/server/src/common/config/env-config.service.ts

NA
Use networks avialable TTL in seconds
Locally
NA
NA

[Dashboard] Use networks avialable TTL in seconds

---

packages/apps/fortune/exchange-oracle/server/src/common/guards/strategy/jwt.http.ts

#2923
Refactor  JwtHttpStrategy to query RPC instead of Subgraph to reduce the amount of request sent
None
None

[Exchange Oracle] Refactor JwtHttpStrategy

---

packages/apps/dashboard/ui-2024/src/pages/Graph/Graph.tsx

HDM-35
I removed tabs implementation
manually check if everything renders as expected
normal deploy

HDM-35: remove tabs implementation from charts page 

---

packages/apps/job-launcher/server/src/modules/job/job.controller.spec.ts
packages/apps/job-launcher/server/src/modules/job/job.controller.ts

#2936
Disable fortune jobs creation for production
Deployed locally and launched tests
None
None

[Job Launcher] Disable fortune jobs creation in mainnets

---

packages/apps/job-launcher/client/src/components/Jobs/Table.tsx
packages/apps/job-launcher/client/src/services/job.ts

#2938
Show the most recent jobs first for all statuses
None
None

[Job Launcher] Show most recent jobs first

---

packages/apps/job-launcher/client/src/App.tsx
packages/apps/job-launcher/client/src/components/Jobs/Create/FundingMethod.tsx
packages/apps/job-launcher/client/src/components/TopUpAccount/TopUpMethod.tsx
packages/apps/job-launcher/server/src/modules/payment/payment.controller.ts
packages/apps/job-launcher/server/src/modules/whitelist/whitelist.service.spec.ts
packages/apps/job-launcher/server/src/modules/whitelist/whitelist.service.ts

None
Disable billing system until we have a Stripe account ready
None
If crypto payments are wanted to be shown in STG, Whitelist should be disabled

Disable billing system

---

packages/apps/reputation-oracle/server/src/common/constants/errors.ts
packages/apps/reputation-oracle/server/src/common/pipes/validation.ts
packages/apps/reputation-oracle/server/src/modules/kyc/kyc.error.filter.ts
packages/apps/reputation-oracle/server/src/modules/qualification/qualification.controller.spec.ts
packages/apps/reputation-oracle/server/src/modules/qualification/qualification.controller.ts
packages/apps/reputation-oracle/server/src/modules/qualification/qualification.dto.ts
packages/apps/reputation-oracle/server/src/modules/qualification/qualification.error.filter.ts
packages/apps/reputation-oracle/server/src/modules/qualification/qualification.error.ts
packages/apps/reputation-oracle/server/src/modules/qualification/qualification.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/qualification/qualification.service.ts

Part of the #2928 
1. Refactored error handling and partially logging for `qualification` module.
2. `/assign` and `/unassign` endpoints are now work only with wallet addresses (prev: emails & addresses)
3. Minor fixes in business logic
4. Removed unused imports from `kyc` module.
Also added a couple TODOs for the future refactoring.
Locally:
1. Setup a local postgres database, apply migrations.
2. Deploy reputation oracle locally.
3. Create a user, grant admin privileges to it.
4. Create another user, it should be a worker.
6. Use swagger to test `/qualification` endpoints.
Double check that `/qualification` is not being used in other services. 
N/A

[Reputation Oracle] refactoring: error handling for `qualification` module

---

packages/examples/cvat/recording-oracle/src/handlers/process_intermediate_results.py

- Fixed invalid source of total jobs count during validation
- Improved number formatting in logs

[CVAT] Fix invalid total job count computation

---

packages/apps/dashboard/ui-2024/src/features/Leaderboard/components/RoleCell.tsx
packages/apps/dashboard/ui-2024/src/features/Leaderboard/hooks/useDataGrid.tsx

#2623
Reenable website url removed after leaders table refactor
Deployed and checked locally
Add website url by oracle per network
None

[Dashboard] Hyperlink role to oracle website

---

packages/apps/human-app/frontend/src/modules/worker/components/jobs/my-jobs-table-actions.tsx

HUM-84
simple css change
manually
normal deployment
N/A

HUM-84 - fix solve button width (mobile)

---

packages/apps/human-app/frontend/.eslintrc.cjs
packages/apps/human-app/frontend/src/api/hooks/use-prepare-signature.ts
packages/apps/human-app/frontend/src/modules/auth-web3/context/web3-auth-context.tsx
packages/apps/human-app/frontend/src/modules/auth/context/auth-context.tsx
packages/apps/human-app/frontend/src/modules/homepage/hooks/use-operator-signin.tsx
packages/apps/human-app/frontend/src/modules/operator/components/profile/profile-disable-button.tsx
packages/apps/human-app/frontend/src/modules/operator/components/sign-up/add-keys/edit-existing-keys-form.tsx
packages/apps/human-app/frontend/src/modules/operator/components/sign-up/add-keys/edit-pending-keys-form.tsx
packages/apps/human-app/frontend/src/modules/operator/views/sign-up/connect-wallet.page.tsx
packages/apps/human-app/frontend/src/modules/operator/views/sign-up/edit-existing-keys-success.page.tsx
packages/apps/human-app/frontend/src/modules/smart-contracts/EthKVStore/config.ts
packages/apps/human-app/frontend/src/modules/worker/hooks/use-register-address.ts
packages/apps/human-app/frontend/src/shared/components/ui/modal/display-modal.tsx
packages/apps/human-app/frontend/src/shared/components/ui/modal/modal-content.tsx
packages/apps/human-app/frontend/src/shared/components/ui/modal/modal-type.enum.ts
packages/apps/human-app/frontend/src/shared/components/ui/modal/modal.store.ts
packages/apps/human-app/frontend/src/shared/components/ui/ui-example.tsx

HUM-126
First step of refactoring modal UI code
manually opened each modal
normal deploy
N/A

[HUM-126]: chore: split modal ui

---

packages/examples/cvat/recording-oracle/src/cvat/api_calls.py
packages/examples/cvat/recording-oracle/src/handlers/process_intermediate_results.py
packages/examples/cvat/recording-oracle/tests/integration/services/test_validation_service.py

- Removed uses of `disabled_frames` from CVAT validation layout update calls in Recording Oracle

[CVAT] Fix validation layout update calls

---

packages/sdk/typescript/subgraph/src/mapping/KVStore.ts
packages/sdk/typescript/subgraph/tests/kvstore/kvstore.test.ts

None
An error was thrown in subgraph when 
modified and run tests for checking new conditional
Deploy new Subgraph version

[Subgraph] Clean KVStore fee values

---

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/constants.py
packages/sdk/typescript/human-protocol-sdk/src/constants.ts

Deploy these subgraph changes https://github.com/humanprotocol/human-protocol/pull/3043
Update subgraph ids 
Data indexed 
NA
NA

Update subgraph ids

---

packages/apps/job-launcher/client/src/components/Jobs/Create/FiatPayForm.tsx
packages/apps/job-launcher/client/src/components/Jobs/Create/LaunchJobProgress.tsx
packages/apps/job-launcher/client/src/components/Jobs/Create/PayJob.tsx
packages/apps/job-launcher/client/src/pages/Profile/Settings/index.tsx

None
- Improve addBillingDetails modal usage
- Fix some styles in LaunchJobProgress page
Launched JL Client locally
Deploy JL Client
Check if Add Billing Details modal is open in a loop when adding card and billing details for the first time

[Job Launcher Client] Improve usability 

---

packages/apps/human-app/frontend/src/shared/hooks/use-notification.tsx
packages/apps/human-app/frontend/src/shared/styles/breakpoints.ts

HUM-171
Reverted changes that broke the view. 
Checked if pages on provided screenshots display properly.
normal
N/A

fix: layout media queries fix 

---

packages/apps/staking/src/components/modals/KVStoreModal.tsx

#3091
Update KVStoreModal to display key values in snake_case
None
None

[Staking] Dropdowns not using snake_case

---

packages/apps/reputation-oracle/server/src/modules/email/sendgrid.service.spec.ts

N/A
`beforeAll` instead of `beforeEach` to speed up tests.
yarn test
N/A
N/A

fix: use `beforeAll` instead of `beforeEach`

---

packages/apps/human-app/frontend/.env.example
packages/apps/human-app/frontend/src/modules/governance-banner/components/governance-banner.tsx
packages/apps/human-app/frontend/src/modules/governance-banner/hooks/use-active-proposal-query.ts
packages/apps/human-app/frontend/src/modules/smart-contracts/abi/MetaHumanGovernor.json
packages/apps/human-app/frontend/src/shared/components/layout/protected/layout.tsx
packages/apps/human-app/frontend/src/shared/env.ts
packages/apps/human-app/frontend/src/shared/styles/color-palette.ts
packages/apps/human-app/frontend/src/shared/styles/dark-color-palette.ts

N/A
Add a new Banner for Governance with active proposal display
Launched locally
Add `VITE_GOVERNOR_ADDRESS` and `VITE_GOVERNANCE_URL`
None

[Human app] Governance banner

---

packages/apps/human-app/frontend/src/modules/signin/worker/sign-in-form.tsx
packages/apps/human-app/frontend/src/modules/signup/worker/views/sign-up-worker.page.tsx
packages/apps/human-app/frontend/src/modules/worker/oracle-registration/registration-form.tsx
packages/apps/human-app/frontend/src/modules/worker/views/email-verification/verify-email.page.tsx
packages/apps/human-app/frontend/src/modules/worker/views/reset-password/reset-password.page.tsx
packages/apps/human-app/frontend/src/modules/worker/views/send-reset-link/send-reset-link-success.page.tsx
packages/apps/human-app/frontend/src/modules/worker/views/send-reset-link/send-reset-link.page.tsx
packages/apps/human-app/frontend/src/shared/components/hcaptcha/h-captcha-form.tsx
packages/apps/human-app/frontend/src/shared/components/hcaptcha/h-captcha.tsx
packages/apps/human-app/frontend/src/shared/components/hcaptcha/index.ts
packages/apps/human-app/frontend/src/shared/components/hcaptcha/types.ts

HUM-86
- moved hcaptcha type 
- added index.ts
- checked if hcaptcha works as before
standard
N/A

[HUM-86]: chore: cleanup hcaptcha module

---

packages/apps/human-app/frontend/src/router/router.tsx

N/A
Move the authentication wrappers to ensure that ProtectedLayout is included and can use the context within it.
Deployed locally and logged in
None
Check whether ProtectedLayout is processed correctly

[Human App] Optimisation of authentication wrappers in the router component

---

packages/apps/human-app/server/src/app.module.ts
packages/apps/human-app/server/src/common/config/gateway-config.service.ts
packages/apps/human-app/server/src/common/enums/reputation-oracle-endpoints.ts
packages/apps/human-app/server/src/integrations/reputation-oracle/reputation-oracle.gateway.ts
packages/apps/human-app/server/src/integrations/reputation-oracle/reputation-oracle.mapper.profile.ts
packages/apps/human-app/server/src/modules/nda/model/nda.model.ts
packages/apps/human-app/server/src/modules/nda/nda.controller.ts
packages/apps/human-app/server/src/modules/nda/nda.mapper.profile.ts
packages/apps/human-app/server/src/modules/nda/nda.module.ts
packages/apps/human-app/server/src/modules/nda/nda.service.ts
packages/apps/human-app/server/src/modules/nda/spec/nda.controller.spec.ts
packages/apps/human-app/server/src/modules/nda/spec/nda.fixtures.ts
packages/apps/human-app/server/src/modules/nda/spec/nda.service.mock.ts
packages/apps/reputation-oracle/server/src/modules/nda/nda.service.spec.ts

#3105
Add NDA module and related functionality
Launched locally. Created a new user and. signed the NDA.
None
None

[Human App] NDA

---

packages/core/README.md
packages/core/test/MetaHumanGovernor.ts
packages/sdk/python/human-protocol-sdk/human_protocol_sdk/legacy_encryption.py

This pull request contains changes to improve clarity, correctness and structure.

fix: typos in documentation files

---

packages/apps/job-launcher/client/src/App.tsx
packages/apps/job-launcher/client/src/components/Jobs/Create/FundingMethod.tsx
packages/apps/job-launcher/client/src/components/TopUpAccount/TopUpMethod.tsx
packages/apps/job-launcher/server/ENV.md
packages/apps/job-launcher/server/src/modules/payment/payment.controller.ts

NA
Remove mainnet checks for fiat payments
Tested locally and created a payment in production
Set valid stripe keys
Create a test payment in prod.
Rollback plan: disable endpoints

[Job Launcher] Remove mainnet checks for fiat payments

---

packages/apps/job-launcher/server/src/common/constants/tokens.ts

N/A
Remove token addresses in constants
Ran tests
None
None

[Job Launcher] remove token addresses in constants

---

packages/apps/reputation-oracle/server/src/config/auth-config.service.ts
packages/apps/reputation-oracle/server/src/config/config.module.ts
packages/apps/reputation-oracle/server/src/config/env-schema.ts
packages/apps/reputation-oracle/server/src/config/nda-config.service.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts
packages/apps/reputation-oracle/server/src/modules/nda/nda.controller.ts
packages/apps/reputation-oracle/server/src/modules/nda/nda.error.filter.ts
packages/apps/reputation-oracle/server/src/modules/nda/nda.error.ts
packages/apps/reputation-oracle/server/src/modules/nda/nda.module.ts
packages/apps/reputation-oracle/server/src/modules/nda/nda.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/nda/nda.service.ts

Part of #3084 
- added `NDAConfigService` to maintain consistency
- added validation for `NDA_URL` env
- minor stylistic refactoring
N/A
N/A

[Reputation Oracle] `NDA` module refactoring

---

packages/apps/reputation-oracle/server/src/config/env-schema.ts
packages/apps/reputation-oracle/server/src/config/pgp-config.service.ts

Part of #3084
Added some rules to the `Joi` env validation
Locally with .env
N/A
N/A

[Reputation Oracle] refactor: added rules to the `Joi` env validation

---

packages/apps/human-app/frontend/src/modules/worker/jobs/components/index.ts
packages/apps/human-app/frontend/src/modules/worker/jobs/components/my-jobs-table-actions.tsx
packages/apps/human-app/frontend/src/modules/worker/jobs/hooks/index.ts
packages/apps/human-app/frontend/src/modules/worker/jobs/hooks/use-get-my-jobs-data.ts
packages/apps/human-app/frontend/src/modules/worker/jobs/jobs.page.tsx
packages/apps/human-app/frontend/src/modules/worker/jobs/my-jobs/components/desktop/columns.tsx
packages/apps/human-app/frontend/src/modules/worker/jobs/my-jobs/components/desktop/my-jobs-table.tsx
packages/apps/human-app/frontend/src/modules/worker/jobs/my-jobs/components/desktop/status-chip.tsx
packages/apps/human-app/frontend/src/modules/worker/jobs/my-jobs/components/mobile/my-jobs-list-mobile.tsx
packages/apps/human-app/frontend/src/modules/worker/jobs/my-jobs/schemas.ts

HUM-88
- restructured code related to my-jobs
- checked if my jobs work on mobile/desktop
- checked if filtering my jobs work on mobile/desktop
normal
n/a

[HUM-88]: fix: refactor components refactor my jobs table

---

packages/apps/job-launcher/client/src/components/Jobs/Table.tsx
packages/apps/job-launcher/client/src/pages/Job/JobDetail/index.tsx
packages/apps/job-launcher/client/src/types/index.ts
packages/apps/job-launcher/server/src/modules/job/job.dto.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts

#3189
- Add currency into job details
- Remove harcoded HMT in JL Client and use the new currency parameter
None
Check if currencies are being displayed properly in JL client

[Job Launcher] Remove hardcoded HMT token

---

packages/apps/job-launcher/client/src/components/Jobs/Create/CryptoPayForm.tsx
packages/apps/job-launcher/client/src/components/Jobs/Create/FiatPayForm.tsx
packages/apps/job-launcher/client/src/components/TokenSelect/index.tsx
packages/apps/job-launcher/client/src/components/TopUpAccount/CryptoTopUpForm.tsx
packages/apps/job-launcher/client/src/components/TopUpAccount/FiatTopUpForm.tsx
packages/apps/job-launcher/client/tsconfig.json
packages/apps/job-launcher/server/src/common/constants/tokens.ts
packages/apps/job-launcher/server/src/common/utils/slack.ts
packages/apps/job-launcher/server/src/common/utils/tokens.ts
packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts
packages/apps/job-launcher/server/src/modules/payment/payment.controller.ts
packages/apps/job-launcher/server/src/modules/payment/payment.dto.ts
packages/apps/job-launcher/server/src/modules/payment/payment.service.ts

#3191
Handle different amount of decimals for funding the escrow in JL
Ran all tests 
None
Check all payment amounts are right

refactor: update token decimals handling and improve input validation in payment forms

---

packages/apps/job-launcher/server/src/modules/payment/payment.service.ts

N/A
correct payment source validation logic in PaymentService to let users remove their cards
Ran tests
None
None

[Job Launcher] Remove credit card

---

packages/apps/job-launcher/server/src/modules/payment/payment.service.ts

fix: correct payment source validation logic in PaymentService (#3207)

---

packages/apps/job-launcher/server/src/common/constants/errors.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts
packages/apps/job-launcher/server/src/modules/whitelist/whitelist.service.spec.ts
packages/apps/job-launcher/server/src/modules/whitelist/whitelist.service.ts

NA
Fix payment creation order and enable whitelist check
Run locally
NA
NA

[Job Launcher] Fix payment creation order and enable whitelist check

---

packages/apps/job-launcher/client/src/components/Payment/PaymentTable.tsx
packages/apps/job-launcher/server/src/common/config/env-schema.ts
packages/apps/job-launcher/server/src/common/config/server-config.service.ts
packages/apps/job-launcher/server/src/common/constants/errors.ts
packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.spec.ts
packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.ts
packages/apps/job-launcher/server/src/modules/payment/payment.dto.ts
packages/apps/job-launcher/server/src/modules/payment/payment.service.spec.ts
packages/apps/job-launcher/server/src/modules/payment/payment.service.ts
packages/apps/job-launcher/server/src/modules/webhook/webhook.controller.ts
packages/apps/job-launcher/server/src/modules/webhook/webhook.service.spec.ts
packages/apps/job-launcher/server/src/modules/webhook/webhook.service.ts

#1757
Enable slash method and cron job. 
Refactor createSlash method to allow invoice creation. 
- Deployed locally
- Ran tests
In case we want a different value to be charged the user, add `ABUSE_AMOUNT` env var.
Check if abused jobs are properly canceled and the payment is created to the user

[Job Launcher] Abuse system integration

---

packages/examples/cvat/exchange-oracle/src/handlers/job_creation.py
packages/examples/cvat/exchange-oracle/src/services/cloud/types.py
packages/examples/cvat/exchange-oracle/src/services/cloud/utils.py
packages/examples/cvat/recording-oracle/src/handlers/process_intermediate_results.py

- Fixed invalid project data URL stored in the Exchange Oracle DB (currently not used, though)
- Fixed input GT annotation merging into final output results
- Fixed GT annotation positions in RoI cut images for `boxes_from_points` task

[CVAT] Oracle fixes

---

packages/apps/dashboard/client/package.json
packages/apps/faucet/client/package.json
packages/apps/fortune/exchange-oracle/client/package.json
packages/apps/human-app/frontend/package.json
packages/apps/job-launcher/client/package.json
packages/apps/staking/package.json
yarn.lock

N/A
Dependency Review fails due to vite version
PR checks
Just merge
N/A

deps: bump vite

---

packages/examples/cvat/exchange-oracle/src/cvat/api_calls.py

- Extended task data uploading status checks to be more reliable

[CVAT] Extend task creation status checks

---

packages/apps/staking/src/constants/chains.ts

N/A
Add support for additional mainnet chain IDs
None
None

[Staking] Add support for additional mainnet chain IDs

---

packages/apps/fortune/exchange-oracle/server/src/common/constant/errors.ts
packages/apps/fortune/exchange-oracle/server/src/common/enums/job.ts
packages/apps/fortune/exchange-oracle/server/src/common/enums/webhook.ts
packages/apps/fortune/exchange-oracle/server/src/database/migrations/1742310067718-pauseJobs.ts
packages/apps/fortune/exchange-oracle/server/src/database/migrations/1743412274647-handleAbuse.ts
packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.service.spec.ts
packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.service.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.spec.ts
packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts
packages/apps/fortune/exchange-oracle/server/src/modules/webhook/webhook.controller.ts
packages/apps/fortune/exchange-oracle/server/src/modules/webhook/webhook.service.spec.ts
packages/apps/fortune/exchange-oracle/server/src/modules/webhook/webhook.service.ts

#3181
Add paused job status and handle abuse webhooks for pausing and resuming jobs
Launched locally
None
None

[Fortune Exchange Oracle] Abuse system

---

packages/apps/job-launcher/client/src/components/Jobs/Create/CryptoPayForm.tsx
packages/apps/job-launcher/client/src/components/TopUpAccount/CryptoTopUpForm.tsx
packages/apps/job-launcher/client/src/providers/WagmiProvider.tsx

N/A
- Add retry logic for crypto payment and top-up forms
- Enhance Wagmi provider configuration
Deployed locally and create some payments
None
Check if the blockchain values are being displayed and if transfers are being made and don't throw a timeout

[Job Launcher] Fix transfers failures

---

packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.spec.ts

N/A
Cron job service test was failing due to wrong date check
Ran tests
None
None

Fix date check in cron job service

---

packages/apps/job-launcher/server/src/common/constants/errors.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts

NA
Escrows in partial status could not be updated to completed when a webhook notification is received from reputation oracle
Locally
No unit tests implemented because of future refactor of job service
NA
NA

[Job Launcher] Add partial status as valid status for completion

---

packages/apps/human-app/frontend/src/modules/worker/jobs/available-jobs/hooks/use-get-available-jobs-columns.tsx
packages/apps/human-app/frontend/src/modules/worker/jobs/my-jobs/components/desktop/columns.tsx
packages/apps/human-app/frontend/src/shared/components/ui/table/table-header-cell.tsx

HUM-175
- modified table header cell component
- adjusted column definitions
- checked if filters work and look the same (only desktop)
normal
n/a

[HUM-175]: fix: fix table header props ref warning

---

packages/examples/cvat/exchange-oracle/README.md
packages/examples/cvat/exchange-oracle/docker-compose.test.yml
packages/examples/cvat/exchange-oracle/src/crons/webhooks/job_launcher.py
packages/examples/cvat/exchange-oracle/src/crons/webhooks/reputation_oracle.py
packages/examples/cvat/exchange-oracle/src/handlers/escrow_cleanup.py
packages/examples/cvat/exchange-oracle/src/services/cvat.py
packages/examples/cvat/exchange-oracle/tests/integration/cron/test_process_job_launcher_webhooks.py

- Added image info cleanup in escrow cleanup handling 
- Updated docker compose file for tests and launch readme

[CVAT] Clean escrow image info after removal on storage

---

packages/apps/human-app/server/src/app.module.ts
packages/apps/human-app/server/src/common/config/gateway-config.service.ts
packages/apps/human-app/server/src/common/enums/reputation-oracle-endpoints.ts
packages/apps/human-app/server/src/integrations/reputation-oracle/reputation-oracle.gateway.ts
packages/apps/human-app/server/src/integrations/reputation-oracle/reputation-oracle.mapper.profile.ts
packages/apps/human-app/server/src/modules/abuse/abuse.controller.ts
packages/apps/human-app/server/src/modules/abuse/abuse.mapper.profile.ts
packages/apps/human-app/server/src/modules/abuse/abuse.module.ts
packages/apps/human-app/server/src/modules/abuse/abuse.service.ts
packages/apps/human-app/server/src/modules/abuse/model/abuse.model.ts
packages/apps/human-app/server/src/modules/abuse/spec/abuse.controller.spec.ts
packages/apps/human-app/server/src/modules/abuse/spec/abuse.fixtures.ts
packages/apps/human-app/server/src/modules/abuse/spec/abuse.service.mock.ts

#3183
Added abuse reporting module with service and endpoints
Ran locally, also ran tests
Release after #3217 to make sure Reputation endpoints are available
None

[Human App] Abuse module

---

packages/apps/reputation-oracle/server/package.json
packages/apps/reputation-oracle/server/src/common/errors/database.ts
packages/apps/reputation-oracle/server/src/config/server-config.service.ts
packages/apps/reputation-oracle/server/src/database/migrations/1744201451282-qualificationAdjustments.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts
packages/apps/reputation-oracle/server/src/modules/qualification/qualification.controller.ts
packages/apps/reputation-oracle/server/src/modules/qualification/qualification.dto.ts
packages/apps/reputation-oracle/server/src/modules/qualification/qualification.entity.ts
packages/apps/reputation-oracle/server/src/modules/qualification/qualification.error.filter.ts
packages/apps/reputation-oracle/server/src/modules/qualification/qualification.error.ts
packages/apps/reputation-oracle/server/src/modules/qualification/qualification.module.ts
packages/apps/reputation-oracle/server/src/modules/qualification/qualification.repository.ts
packages/apps/reputation-oracle/server/src/modules/qualification/qualification.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/qualification/qualification.service.ts
packages/apps/reputation-oracle/server/src/modules/qualification/user-qualification.entity.ts
packages/apps/reputation-oracle/server/src/modules/qualification/user-qualification.repository.ts
yarn.lock

Part of #3084 
- Added a migration for new index + `timestamptz` usage in qualifications table + restraints for text fields
- Reworked service + added a new repository (`UserQualificationRepository`)
- New unit tests
N/A
N/A

[Reputation Oracle] `Qualification` module refactoring

---

packages/apps/human-app/frontend/src/api/hooks/use-access-token-refresh.ts
packages/apps/human-app/frontend/src/main.tsx
packages/apps/human-app/frontend/src/modules/auth-web3/context/web3-auth-context.tsx
packages/apps/human-app/frontend/src/modules/auth-web3/providers/require-web3-auth.tsx
packages/apps/human-app/frontend/src/modules/auth/context/auth-context.tsx
packages/apps/human-app/frontend/src/modules/auth/providers/require-auth.tsx
packages/apps/human-app/frontend/src/shared/contexts/generic-auth-context.tsx

HUM-142
- reduced boilerplate from contexts
- logged in both ways and clicked around
normal
n/a

chore: remove boilerplate for auth contexts

---

packages/apps/human-app/frontend/src/shared/providers/notifications-provider.tsx

HUM-179
- removed stack that overflowed buttons, added snackbars width relative to viewport
- checked displayed snackbars (mobile/desktop)
normal
n/a

[HUM-179]: fix: change notistack styles

---

packages/apps/human-app/frontend/src/modules/worker/jobs/components/escrow-address-search-form.tsx
packages/apps/human-app/frontend/src/modules/worker/jobs/hooks/use-my-jobs-filter-store.tsx

HUM-180
- fixed a bug when escrow address search form freezed up the page
- checked if search form works
normal
n/a

[HUM-180]: fix: memoize debounce, move validation trigger

---

packages/apps/job-launcher/client/src/pages/Job/JobDetail/index.tsx
packages/apps/job-launcher/server/src/common/constants/tokens.ts
packages/apps/job-launcher/server/src/common/validators/token-decimals.ts
packages/apps/job-launcher/server/src/modules/job/job.dto.ts
packages/apps/job-launcher/server/src/modules/job/job.interface.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts

N/A
Fix some bugs found in JL regarding currencies in lower case and some bad usage of decimals when calculating job bounties for CVAT and Audino
Created some escrows in JL to see if everything works
None
Check if JobBounty is calculated properly

[Job Launcher] Fix some bugs with multitokens

---

packages/apps/reputation-oracle/server/src/database/migrations/1747219638888-cascadeDeletion.ts
packages/apps/reputation-oracle/server/src/modules/abuse/abuse.entity.ts
packages/apps/reputation-oracle/server/src/modules/auth/jwt-http-strategy.ts
packages/apps/reputation-oracle/server/src/modules/auth/token.entity.ts
packages/apps/reputation-oracle/server/src/modules/kyc/kyc.entity.ts
packages/apps/reputation-oracle/server/src/modules/qualification/qualification.error-filter.ts
packages/apps/reputation-oracle/server/src/modules/qualification/qualification.error.ts
packages/apps/reputation-oracle/server/src/modules/qualification/qualification.service.spec.ts
packages/apps/reputation-oracle/server/src/modules/qualification/qualification.service.ts
packages/apps/reputation-oracle/server/src/modules/qualification/user-qualification.entity.ts
packages/apps/reputation-oracle/server/src/modules/user/site-key.entity.ts

Part of #2803 
Added cascade deletion:
If user is deleted:
- Remove tokens
- Remove user qualifications
- Remove sitekeys
- Remove KYC
Also, removed constrain on qualification deletion if there users with this qualification assigned.
Fixed bug introduced in #3322.
N/A
N/A

[Reputation Oracle] Added cascade deletion

---

packages/apps/job-launcher/server/src/modules/payment/payment.service.ts

N/A
Added a check when creating the card to be the default if there is no other default method for the user
Deployed on vercel and created some cards 
None
None

[Job Launcher] Default card

---

packages/core/package.json
packages/sdk/python/human-protocol-sdk/setup.py
packages/sdk/typescript/human-protocol-sdk/package.json

NA
Update sdk & core version to 4.1.3
Merge and release packages
NA

Update sdk & core version to 4.1.3

---

packages/apps/job-launcher/server/src/modules/job/job.controller.ts

N/A
Enabling Audino on production

[Job Launcher][Server] Enable audino on production

---

packages/apps/job-launcher/server/src/modules/job/job.controller.ts

Release 2025-07-08

---

packages/examples/cvat/exchange-oracle/poetry.lock
packages/examples/cvat/exchange-oracle/pyproject.toml
packages/examples/cvat/recording-oracle/poetry.lock
packages/examples/cvat/recording-oracle/pyproject.toml

Updated Human Protocol SDK to 4.1.4

[CVAT] update human sdk

---

packages/apps/dashboard/client/src/features/searchResults/model/addressDetailsSchema.ts
packages/apps/dashboard/client/src/features/searchResults/ui/EscrowAddress.tsx
packages/apps/dashboard/client/src/features/searchResults/ui/HmtBalance.tsx
packages/apps/dashboard/client/src/features/searchResults/ui/StakeInfo.tsx
packages/apps/dashboard/client/src/features/searchResults/ui/TokenAmount.tsx

Not ticketed
Noticed there's a wrong calculation of balance (redundant *1e18)
locally with different escrows
regular
not found

[Dashboard] - Fix HMT balance and token amount

---

packages/apps/human-app/server/src/integrations/exchange-oracle/exchange-oracle.gateway.ts

N/A
After the release we noticed that too many 4xx errors are logged from CVAT ExcO. Silence these and log only 5xx.
N/A
Just merge
No

[HUMAN App] chore: silence useless errors

---

packages/apps/human-app/server/src/app.module.ts
packages/apps/human-app/server/src/common/config/environment-config.service.ts
packages/apps/human-app/server/src/modules/governance/governance.controller.ts
packages/apps/human-app/server/src/modules/governance/governance.service.ts

N/A
- Add caching for proposals endpoint 
- Increase cache duration
None
None

 [Human App] Add caching for proposals endpoint and increase cache duration

---

packages/apps/job-launcher/client/src/components/Jobs/Create/AudinoJobRequestForm.tsx
packages/apps/job-launcher/client/src/components/Jobs/Create/helpers.ts
packages/apps/job-launcher/client/src/types/index.ts
packages/apps/job-launcher/server/src/common/enums/job.ts
packages/apps/job-launcher/server/src/common/utils/storage.ts
packages/apps/job-launcher/server/src/database/migrations/1756902190591-addAudioAttributeAnnotation.ts
packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.spec.ts
packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
packages/apps/job-launcher/server/src/modules/job/job.service.ts
packages/apps/job-launcher/server/src/modules/manifest/manifest.dto.ts
packages/apps/job-launcher/server/src/modules/manifest/manifest.service.spec.ts
packages/apps/job-launcher/server/src/modules/manifest/manifest.service.ts
packages/apps/job-launcher/server/src/modules/routing-protocol/routing-protocol.service.ts

Closes #3536 
Add the new job type to AUDINO job types
- Launched a job 
- Fetched job details in UI
- Migration
NA

[Job Launcher] Job type audio attribute annotation

---

packages/examples/cvat/exchange-oracle/src/endpoints/exchange.py
packages/examples/cvat/exchange-oracle/tests/api/test_exchange_api.py

- `GET /job?status=active` will not return jobs without free assignments anymore

[Dependent] [CVAT] Improve active job filter

---

packages/examples/cvat/exchange-oracle/src/chain/kvstore.py
packages/examples/cvat/recording-oracle/src/chain/kvstore.py

Release 2025-09-18 [2]

---

packages/examples/cvat/exchange-oracle/src/core/manifest.py
packages/examples/cvat/exchange-oracle/src/endpoints/serializers.py
packages/examples/cvat/exchange-oracle/src/services/exchange.py
packages/examples/cvat/exchange-oracle/tests/integration/services/test_exchange.py
packages/examples/cvat/exchange-oracle/tests/utils/manifest.json

Release 2025-09-19 [2]

---

packages/apps/job-launcher/server/package.json
packages/apps/job-launcher/server/src/common/utils/gcstorage.ts
packages/apps/job-launcher/server/src/modules/storage/storage.service.spec.ts
packages/apps/job-launcher/server/src/modules/storage/storage.service.ts
packages/apps/reputation-oracle/server/package.json
packages/apps/reputation-oracle/server/src/utils/http.spec.ts
packages/apps/reputation-oracle/server/src/utils/http.ts
packages/sdk/typescript/human-protocol-sdk/package.json
packages/sdk/typescript/human-protocol-sdk/src/utils.ts
packages/sdk/typescript/human-protocol-sdk/test/storage.test.ts
packages/sdk/typescript/human-protocol-sdk/test/utils.test.ts
yarn.lock

Closes #3275
Add validator package and enhance URL validation logic for JL, Reputation Oracle and SDK
Ran unit tests with different url test cases to check if everything worked as expected
- Create new minor change for SDK
- Deploy services
Check that the URLs that we're currently using are not failing with new validations.

Enhance validation for HTTP urls

---

packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.spec.ts
packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.ts

NA
Use the right decimals for the token in refunds
Locally
NA
NA

[Job Launcher] Use the right decimals for the token in refunds
