humanprotocol/human-protocol

packages/apps/escrow-dashboard/src/components/Token/TokenView.tsx, packages/apps/escrow-dashboard/src/state/token/hooks.ts
Display specific token stats (transfer amounts, holders, total supply) when one of the mainnets is selected. If All networks or testnet is selected, token stats view will show aggregated data.
=> fix mainnet token view

packages/core/contracts/EscrowFactory.sol, packages/core/test/EscrowFactory.ts, packages/core/test/RewardPool.ts, packages/core/test/Staking.ts
Changes to `Launched` event of EscrowFactory contract is unnecessary, which ends up with breaking subgraph.
So, reverting those changes to make original subgraph work.
=> Remove counter from Launched event

packages/examples/fortune/README.md
Update old deployed playground fortune readme
Switch from an old deleted ec2 instance to the new vercel deployment
=> Update old deployed playground fortune readme

CONTRACTS_LIST.md, packages/apps/escrow-dashboard/src/constants/index.ts, packages/core/README.md, packages/core/hardhat.config.ts, packages/core/package.json, packages/core/scripts/deploy-proxies.ts, packages/examples/fortune/launcher/server/src/constants/networks.ts, packages/sdk/typescript/subgraph/README.md, packages/sdk/typescript/subgraph/config/mumbai-v1.json
Deploy contracts from #87 feat/staking-slashing on mumbai
Go to https://mumbai.polygonscan.com/ an check these contracts are verified:
Staking Proxy Address:  0x7Fd3dF914E7b6Bd96B4c744Df32183b51368Bfac
Staking Implementation Address:  0x19Fc3e859C1813ac9427a7a78BeB9ae102CE96d3
Escrow Factory Proxy Address:  0xA8D927C4DA17A6b71675d2D49dFda4E9eBE58f2d
Escrow Factory Implementation Address:  0xd319e761b632E39234E68247D307818a20158890
KVStore Address:  0xD7F61E812e139a5a02eDae9Dfec146E1b8eA3807
Reward Pool Proxy Address:  0xf0145eD99AC3c4f877aDa7dA4D1E059ec9116BAE
Reward Pool Implementation Address:  0x295514FC4C812Db24C3277d6D3175956AdEA273C
Reputation Proxy Address:  0xC522463d36f76b881bE66484e3068F11e7038Ace
Reputation Implementation Address:  0x7B9f9Dc6c157899C1Eb1c6B86f94855cC2F537dF …
=> Deploy contracts with proxies on Mumbai

packages/apps/escrow-dashboard/src/constants/index.ts
Subgraphs urls for Avalanche are wrong
Change subgraphs urls for Avalanche
Run dashboard
=> Fix subgraphs url for avalanche

packages/core/contracts/Escrow.sol, packages/core/contracts/HMToken.sol, packages/core/contracts/RewardPool.sol, packages/core/contracts/Staking.sol, packages/core/package.json, packages/core/test/EscrowFactory.ts, packages/core/test/RewardPool.ts, packages/core/test/Staking.ts, packages/sdk/typescript/human-protocol-sdk/package.json, packages/sdk/typescript/subgraph/.eslintignore, yarn.lock
Fix issues reported by Certik.
Fixed issues:
ESC-01 | Potential Logical Issue In `bulkPayout`.
ESC-02 | External Call Inside Loop
HMT-03 | Check Effect Interaction Pattern Violated
HMT-04 | Misleading Function Name
HMT-05 | Missing Zero Address Validation
HMT-06 | Function 'transferFrom' Of Contract HMToken Does Not Prevent Transfers From The Zero Address
HMT-07 | Unoptimized Code
HMT-09 | Redundant Check
HMT-10 | Improper Usage Of `public` And `external` Type
HMT-11 | Missing Emit Events
HMT-12 | Too Many Digits
HMT-13 | `bulkPayout` Can Still Be Called When Status Is `Complete` Or `Cancelled`
HMT-14 | Logic Issue In Function `increaseApproval`
HMT-15 | Inconsistency Between Comment And Code
HMT-16 | Unclear Purpose Of `storeResults`
[Keywords for linking …
=> Fix audit report

packages/examples/fortune/launcher/server/src/routes/escrow.ts, packages/examples/fortune/launcher/server/tests/routes/escrow.test.ts
Add ex oracle url to create job response
Add exchangeUrl to response, example:
{
escrowAddress: '0xddEA3d67503164326F90F53CFD1705b90Ed1312D',
exchangeUrl: 'http://localhost:3001/?address=0xddEA3d67503164326F90F53CFD1705b90Ed1312D'
}
`yarn fortune:test`
=> Add ex oracle url to create job response

packages/core/contracts/Escrow.sol, packages/core/package.json, packages/core/test/Escrow.ts, packages/examples/eth-kvstore-gui/package.json, packages/examples/eth-kvstore-gui/src/components/Decrypt.tsx, packages/examples/eth-kvstore-gui/src/components/GeneratePGP.tsx, packages/examples/eth-kvstore-gui/src/components/ImportButton.tsx, packages/examples/eth-kvstore-gui/src/components/KeyValue.tsx, packages/examples/eth-kvstore-gui/src/components/YourPublicKey.tsx, packages/examples/eth-kvstore-gui/src/index.tsx, packages/sdk/typescript/subgraph/config/bsc-v1.json, packages/sdk/typescript/subgraph/config/bsctest-v1.json, packages/sdk/typescript/subgraph/config/goerli-v1.json, packages/sdk/typescript/subgraph/config/moonbase-alpha-v1.json, packages/sdk/typescript/subgraph/config/moonbeam-v1.json, packages/sdk/typescript/subgraph/config/mumbai-v1.json, packages/sdk/typescript/subgraph/config/polygon-v1.json, packages/sdk/typescript/subgraph/schema.graphql, packages/sdk/typescript/subgraph/src/mapping/Escrow.ts, packages/sdk/typescript/subgraph/src/mapping/EscrowFactory.ts, packages/sdk/typescript/subgraph/src/mapping/KVStore.ts, packages/sdk/typescript/subgraph/src/mapping/RewardPool.ts, packages/sdk/typescript/subgraph/src/mapping/Staking.ts, packages/sdk/typescript/subgraph/template.yaml, packages/sdk/typescript/subgraph/tests/escrow/escrow.test.ts, packages/sdk/typescript/subgraph/tests/escrow/fixtures.ts, packages/sdk/typescript/subgraph/tests/reward-pool/fixtures.ts, packages/sdk/typescript/subgraph/tests/reward-pool/reward-pool.test.ts, packages/sdk/typescript/subgraph/tests/staking/staking.test.ts, yarn.lock
Update subgraph for escrow tracking.
We want to display escrow data for each leader on dashboard with its allocation, payment, and status.
- Smart contract change
`Escrow` contract is updated to emit `BulkTransfer` event with more data. Added two fields `amountPaid`, and `isPartial`.
- Subgraph change
Handlers for Escrow, EscrowFactory, Staking, and RewardPool are updated to properly track LaunchedEscrow entity on subgraph.
=> feat: update subgraph for escrow

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/eth_bridge.py, packages/sdk/typescript/human-protocol-sdk/src/job.ts
Fix `get_pub_key_from_addr` to get value of `wallet_addr`.
First parameter `wallet_addr` provided to function `get_pub_key_from_addr` was unused. `get_pub_key_from_addr` always returned `hmt_pub_key` of main `GAS_PAYER`. Now `get_pub_key_from_addr` retrieves `hmt_pub_key` for `wallet_addr` provided as first parameter.
call set_pub_key_at_addr(pub_key, hmt_server_addr)
call get_pub_key_from_addr(wallet_addr)
value `pub_key` and value returned by `get_pub_key_from_addr` should be equal
=> Fix get_pub_key_from_addr to get value of wallet_addr

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/job.py
Adjust sdk syntax code for python less than 3.10
Symbol `|` is supported starting from python 3.10, so `|` replaced with `Union[]`
=> Adjust sdk syntax code for python less than 3.10

packages/examples/cvat/exchange-oracle/.gitignore, packages/examples/cvat/exchange-oracle/poetry.lock, packages/examples/cvat/exchange-oracle/pyproject.toml, packages/examples/cvat/exchange-oracle/src/modules/webhook/api.py, packages/examples/cvat/exchange-oracle/src/modules/webhook/api_schema.py
Python version downgraded from 3.11 to 3.9 due to the web3 package incompatabilty.
=> Python version downgraded from 3.11 to 3.9

package.json, packages/apps/escrow-dashboard/package.json, packages/core/package.json, yarn.lock
`qrcode@1.4.4` is using old version of `yargs`, which causes dependabot alert for `yargs-parser`.
- Updated module resolution for `qrcode`, and `gluegun` dependency.
- Removed `@mui/styles` from escrow-dashboard since it's deprecated in MUIv5.
- Updated `tenderly` version to later version in core package.
=> remove unused dependency and update qrcode module resolution

packages/examples/fortune-v2/exchange-oracle/server/src/app.module.ts, packages/examples/fortune-v2/exchange-oracle/server/src/common/decorators/webhook.ts, packages/examples/fortune-v2/exchange-oracle/server/src/common/helpers/encryption.ts, packages/examples/fortune-v2/exchange-oracle/server/src/common/helpers/index.ts, packages/examples/fortune-v2/exchange-oracle/server/src/common/helpers/json.ts, packages/examples/fortune-v2/exchange-oracle/server/src/common/interfaces/encryption.ts, packages/examples/fortune-v2/exchange-oracle/server/src/common/interfaces/signature.ts, packages/examples/fortune-v2/exchange-oracle/server/src/webhook/dto/create.ts, packages/examples/fortune-v2/exchange-oracle/server/src/webhook/dto/update.ts, packages/examples/fortune-v2/exchange-oracle/server/src/webhook/interfaces/create.ts, packages/examples/fortune-v2/exchange-oracle/server/src/webhook/interfaces/update.ts, packages/examples/fortune-v2/exchange-oracle/server/src/webhook/webhook-outgoing.entity.ts, packages/examples/fortune-v2/exchange-oracle/server/src/webhook/webhook.module.ts, packages/examples/fortune-v2/exchange-oracle/server/src/webhook/webhook.service.ts, packages/examples/fortune-v2/job-launcher/server/src/currency/currency.service.ts, packages/examples/fortune-v2/job-launcher/server/src/payment/dto/confirm.ts, packages/examples/fortune-v2/recording-oracle/server/src/common/decorators/webhook.ts, packages/examples/fortune-v2/recording-oracle/server/src/common/enums/errors.ts, packages/examples/fortune-v2/recording-oracle/server/src/common/interfaces/signature.ts, packages/examples/fortune-v2/recording-oracle/server/src/migrations/1677750428969-addWebhookOutgoingTable.ts, packages/examples/fortune-v2/recording-oracle/server/src/webhook/dto/create.ts, packages/examples/fortune-v2/recording-oracle/server/src/webhook/dto/update.ts, packages/examples/fortune-v2/recording-oracle/server/src/webhook/interfaces/create.ts, packages/examples/fortune-v2/recording-oracle/server/src/webhook/interfaces/update.ts, packages/examples/fortune-v2/recording-oracle/server/src/webhook/webhook-outgoing.entity.ts, packages/examples/fortune-v2/recording-oracle/server/src/webhook/webhook.controller.ts, packages/examples/fortune-v2/recording-oracle/server/src/webhook/webhook.service.ts
Client for communication with Reputation Oracle.
The Recording Oracle should be able to send a webhook to Reputation Oracle, in case of an error, write the result to a table `webhooks_outgoing_table` with the `FAILED` status.
[Detailed spec in notion](https://www.notion.so/human-protocol/Recording-Oracle-84ebf2e52e5a4c1087cea216f2bafa04?pvs=4#5b9ae1b7f30b42c78c925b1c9c0db1de)
[Fortune | Recording Oracle - Develop Reputation Oracle client#307](https://github.com/humanprotocol/human-protocol/issues/307)
[Fortune | Recording Oracle - Implement common Webhook module with processing details#300](https://github.com/humanprotocol/human-protocol/issues/300)
=> Recording oracle/webhook

packages/core/contracts/KVStore.sol, packages/core/contracts/libs/Stakes.sol, packages/core/test/KVStore.ts, packages/core/test/Staking.ts
- Added `setBulk` function to KVStore. Set 20 as maximum bulk count.
- Remove duplicated code from staking contract.
=> add bulk set function to kvstore and remove duplicate code from staking

packages/core/contracts/RewardPool.sol, packages/core/contracts/Staking.sol, packages/core/test/RewardPool.ts, packages/core/test/Staking.ts
Fixed Staking/RewardPool contracts.
Some of the validations were wrong/missing.
Closes #389 
Closes #390 
Closes #391 
Closes #394
=> Fix: Staking/RewardPool contracts

.github/workflows/cd-core.yaml, .github/workflows/cd-deploy-contracts.yaml, .github/workflows/cd-node-basemodels.yaml, .github/workflows/cd-node-sdk.yaml, .github/workflows/cd-subgraph.yaml, .github/workflows/ci-lint.yaml, .github/workflows/ci-test-core.yaml, .github/workflows/ci-test-escrow-dashboard.yaml, .github/workflows/ci-test-faucet-server.yaml, .github/workflows/ci-test-fortune.yaml, .github/workflows/ci-test-meta-code-verify.yml, .github/workflows/ci-test-node-basemodels.yaml, .github/workflows/ci-test-node-sdk.yaml, .github/workflows/ci-test-python-sdk.yaml, .github/workflows/ci-test-subgraph.yaml
Github actions are failing randomly when trying to compile contracts.
Sometimes it just downloads compiler and doesn't actually compile the contracts.
Specify node version in workflow
https://github.com/NomicFoundation/hardhat/issues/3877
Check workflows in this PR
=> fix contracts compile failing randomly in workflow

.github/workflows/cd-deploy-contracts.yaml, .github/workflows/cd-subgraph.yaml, packages/core/.openzeppelin/polygon-mumbai.json, packages/core/hardhat.config.ts, packages/core/package.json, yarn.lock
Merge fix for workflows on contracts and subgraph deployment
=> Release 20220428

packages/apps/escrow-dashboard/src/components/Escrow/EscrowContainer.tsx, packages/apps/escrow-dashboard/src/state/token/hooks.ts, packages/apps/escrow-dashboard/src/state/token/reducer.ts
Token view shows sum of mainnet chains when testnets are selected from tab control. So sometimes it doesn't make sense to users.
Show selected chain data on token metrics, and only show sum of all chain data if `All Network` tab is selected.
=> fix token view on escrow dashboard

packages/core/contracts/Escrow.sol, packages/core/contracts/HMToken.sol, packages/core/test/Escrow.ts
Certik v3 report is asking to write more comprehensive documentation about `bulkPayout` function for clarity.
- Fix unnecessary usage of `SafeMath` utils in `HMToken.sol`.
- Add meaningful comments to `bulkPayout` function of `Escrow.sol`.
Closes #438
=> Resolve Certik v3 Reports

packages/sdk/json-schema/manifest.json, packages/sdk/python/human-protocol-basemodels/basemodels/manifest/restricted_audience.py, packages/sdk/python/human-protocol-basemodels/test/test_manifest.py, packages/sdk/typescript/human-protocol-sdk/src/types.ts
=> basemodels: manifest: include content preferences

packages/apps/escrow-dashboard/vercel.json
Prevent clickjacking on escrow dashboard by adding some security options in the header.
Fix vercel.json to include X-Frame-Options and Content-Security-Policy in the header.
This will close #279
=> [Escrow Dashboard] - Fix vercel config to prevent clickjacking

packages/core/contracts/RewardPool.sol, packages/core/contracts/Staking.sol, packages/core/contracts/interfaces/IRewardPool.sol, packages/core/test/RewardPool.ts, packages/sdk/typescript/subgraph/schema.graphql, packages/sdk/typescript/subgraph/src/mapping/RewardPool.ts, packages/sdk/typescript/subgraph/template.yaml, packages/sdk/typescript/subgraph/tests/reward-pool/fixtures.ts, packages/sdk/typescript/subgraph/tests/reward-pool/reward-pool.test.ts
Fix RewardPool contract to have staker information, and subgraph to properly index it.
- Fixed `RewardPool` contract.
- Add `_staker` to `addReward` function.
- Updated `RewardAdded` event to emit `staker` info as well.
- Fixed `Staking` contract, for `addReward` function change.
- Fixed subgraph to properly index `RewardAdded` event.
Closes #450 .
=> fix reward pool event and subgraph

packages/core/contracts/Escrow.sol, packages/core/contracts/interfaces/IEscrow.sol, packages/core/test/Escrow.ts, packages/examples/fortune/tests/e2e-backend/contracts/InvalidEscrowAbi.json, packages/sdk/typescript/human-protocol-sdk/src/job.ts, packages/tools/data-recovery-tool/src/abis/Escrow_rinkeby_0x925B24444511c86F4d4E63141D8Be0A025E2dca4.json
Update escrow contract.
- Change data type from `uint256` to `uint8` for fee percentage variables.
- Renamed `recordingOracleStake`, and `reputationOracleStake` to `recordingOracleFeePercentage`, and `reputationOracleFeePercentage`.
Closes #447
=> update variable name and datatype in escrow contract

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/constants.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/staking.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/utils.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_staking.py
Add subgraph calls to get rewards information for python staking module.
- Added a new utility function `get_data_from_subgraph`.
- Implemented `get_rewards_info` function, to get `rewardAddedEvents` data from the subgraph.
Closes #448
=> `get_rewards_info` implementation using subgraph

packages/core/contracts/Escrow.sol, packages/core/contracts/interfaces/IEscrow.sol, packages/core/test/Escrow.ts, packages/examples/fortune/recording-oracle/src/plugins/escrow.ts, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/job.py, packages/sdk/typescript/human-protocol-sdk/src/job.ts, packages/sdk/typescript/subgraph/src/mapping/Escrow.ts, packages/sdk/typescript/subgraph/template.yaml, packages/sdk/typescript/subgraph/tests/escrow/escrow.test.ts, packages/sdk/typescript/subgraph/tests/escrow/fixtures.ts
Remove `sender` in `storeResults` function of `Escrow` contract, because it's unnecessary.
- Removed `sender` param in `storeResults` function.
- Updated fortune, and SDKs accordingly for the function change.
- Updated subgraph to handle `IntermediateStorage` event properly.
Closes #453
=> remove sender in storeResults

packages/core/contracts/Staking.sol, packages/core/test/Staking.ts
Couple fixes in Staking contract.
- Removed `onlyStaker` modifier, since it's unnecessary.
- Fixed validation of the `closeAllocation`, so that only the allocator can close the allocation.
Closes #464
=> fix: remove onlyStaker modifier and validation for allocation close

packages/core/.openzeppelin/mainnet.json, packages/core/.openzeppelin/unknown-1284.json, packages/core/.openzeppelin/unknown-1287.json, packages/core/hardhat.config.ts, packages/examples/fortune/launcher/client/src/constants/index.ts, packages/examples/fortune/launcher/server/src/constants/networks.ts, packages/examples/fortune/launcher/server/src/plugins/escrow.ts, packages/examples/fortune/launcher/server/src/routes/escrow.ts, packages/examples/fortune/recording-oracle/src/constants/networks.ts, packages/examples/fortune/reputation-oracle/src/constants/constants.ts, packages/sdk/typescript/subgraph/config/moonbase-alpha-v1.json, packages/sdk/typescript/subgraph/config/moonbeam-v1.json, packages/sdk/typescript/subgraph/schema.graphql
Deploy contracts upgrade to ethereum, moonbase and moonbeam
update addreses and push subgraph
Check dashboard and test in fortune
=> Deploy contracts upgrade to ethereum, moonbase and moonbeam

packages/sdk/typescript/subgraph/schema.graphql, packages/sdk/typescript/subgraph/src/mapping/Escrow.ts, packages/sdk/typescript/subgraph/tests/escrow/escrow.test.ts
At the moment, there's no way to get manifest urls from the LaunchedEscrow entites.
Added the manifestUrl property to LaunchedEscrow entity and set value in the PendingEvent handler.
This will close #525
=> [Subgraph] Amend LaunchedEscrow entity

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/storage.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_storage.py, packages/sdk/typescript/human-protocol-sdk/src/storage.ts, packages/sdk/typescript/human-protocol-sdk/src/types.ts, packages/sdk/typescript/human-protocol-sdk/test/storage.test.ts
Fix SDK storage module
- Modified `upload_files` function to return `url` as part of upload result.
- Fixed file `key` on python sdk storage module to match ts sdk.
closes #540
=> fix: sdk storage module to return url after upload

packages/sdk/python/human-protocol-basemodels/Makefile, packages/sdk/python/human-protocol-basemodels/Pipfile, packages/sdk/python/human-protocol-basemodels/setup.py, packages/sdk/python/human-protocol-sdk/Makefile, packages/sdk/python/human-protocol-sdk/Pipfile, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/utils/manifest.py
Python SDK fix
- Remove `hmt-basemodels` dependency, and use `human-protocol-basemodels`
- Fix dependency install of `human-protocol-basemodels` package.
Closes #551
=> fix python basemodels dependency and sdk

packages/apps/escrow-dashboard/src/components/Token/TokenView.tsx, packages/apps/escrow-dashboard/src/constants/index.ts, packages/apps/escrow-dashboard/src/state/token/hooks.ts, packages/apps/escrow-dashboard/src/state/token/reducer.ts
Update token section on the escrow-dashboard
-  Displayed aggregated data for mainnet chains when `All Networks` and testnet chains are selected.
-  Displayed `1B - Sum of other mainnets' total supply` for Total Supply when `Ethereum` is selected.
=> Escrow dashboard fix token view

packages/core/contracts/Escrow.sol, packages/core/test/Escrow.ts, packages/examples/fortune/reputation-oracle/src/services/escrow.test.ts, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_escrow.py, packages/sdk/typescript/human-protocol-sdk/package.json, packages/sdk/typescript/human-protocol-sdk/src/escrow.ts, packages/sdk/typescript/human-protocol-sdk/test/escrow.test.ts
Escrow functions `bulkPayout`, `storeResult`, and `complete` needs more restricted permission.
And reputation/recording oracle should not be considered super user, in general.
- Added two more modifiers. `trustedOrReputationOracle`, `trustedOrRecordingOracle`.
- Changed modifier of three functions `bulkPayout`, `storeResult`, and `complete` of escrow contract.
- Removed `recordingOracle`, and `reputationOracle` from trusted handlers list.
Closes #558
=> fix: [Core] update escrow function permissions

packages/examples/fortune-v2/reputation-oracle/server/src/modules/webhook/webhook.dto.ts, packages/examples/fortune-v2/reputation-oracle/server/src/modules/webhook/webhook.repository.ts, packages/examples/fortune-v2/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts, packages/examples/fortune-v2/reputation-oracle/server/src/modules/webhook/webhook.service.ts, packages/examples/fortune-v2/reputation-oracle/server/test/constants.ts
The reputation oracle determines the task type, and if the task type is IMAGE_LABEL_BINARY (CVAT), then to take [the file object and make payouts to all successful workers](https://www.notion.so/human-protocol/Recording-Oracle-a09af42ed54749999154c0c8ea3b4d4c?pvs=4#0799bed0321b436bba57aff9bc79172d). In this version, reputation is not taken into account.
`yarn test`
[Reputation Oracle - Add CVAT worker payout logic#609](https://github.com/humanprotocol/human-protocol/issues/609)
=> Added logic for image binary label job type

packages/apps/job-launcher/server/src/common/constants/errors.ts, packages/apps/job-launcher/server/src/modules/job/job.dto.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts
Validate the manifest before launching the escrow.
- Added manifest validation
- Manifest DTO was divided for 2 types: FortuneManifestDto and ImageLabelBinaryManifestDto
- Added additional test cases
- Updated existing test cases
`yarn test`
[Job Launcher - Validate manifest before creating escrow#600](https://github.com/humanprotocol/human-protocol/issues/600)
=> Added manifest validation, added additional dto classes, added unit tests

packages/apps/fortune/recording-oracle/.env.sample, packages/apps/fortune/recording-oracle/src/common/config/server.config.ts, packages/apps/fortune/recording-oracle/src/modules/job/job.controller.spec.ts, packages/apps/fortune/recording-oracle/src/modules/job/job.module.ts, packages/apps/fortune/recording-oracle/src/modules/job/job.service.spec.ts, packages/apps/fortune/recording-oracle/src/modules/job/job.service.ts
Ideally, reputation Oracle should be read from KVStore. But as of now, KVStore is not used yet. Therefore, as a workaround, we should read it from env variable. In the near future, we'll remove env variable, and read reputation oracle URL from KVStore.
- Read reputation oracle URL from env variable.
- Reading reputation oracle URL from KVStore is coded, but commented. Will uncomment in the future.
Closes #629
=> [Fortune] [Recording Oracle] Change the way reading reputation oracle URL

packages/examples/cvat/recording-oracle/.gitignore, packages/examples/cvat/recording-oracle/README.MD, packages/examples/cvat/recording-oracle/bin/start_test.sh, packages/examples/cvat/recording-oracle/docker-compose.test.yml, packages/examples/cvat/recording-oracle/src/db/__init__.py, packages/examples/cvat/recording-oracle/tests/conftest.py, packages/examples/cvat/recording-oracle/tests/integration/service/test_webhook_service.py
Added setup for testing CVAT Recording Oracle
1. Added service tests for `webhook` module.
2. Added missing `db/` folder (wasn't here because of the `.gitignore` file in a root folder of `human-protocol` repo.
```
poetry install
poetry shell
docker-compose -f docker-compose.test.yml up -d
./bin/start_test.sh
```
To close https://github.com/humanprotocol/human-protocol/issues/640
=> Init tests

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/staking.py, packages/sdk/python/human-protocol-sdk/test/e2e/test_staking.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_staking.py, packages/sdk/typescript/human-protocol-sdk/src/interfaces.ts, packages/sdk/typescript/human-protocol-sdk/src/staking.ts, packages/sdk/typescript/human-protocol-sdk/test/staking.test.ts
Fix Node.js/Python SDK `StakingClient` module. It's missing address in the staker info, which is necessary.
- Updated return value schema of `getAllStakers`, and `getStaker` function of Node.js SDK, to include `address` of the staker.
- Updated `get_staker_info` function of Python SDK to include `address` of the staker.
- Renamed `staker` to `address` of the return value of `get_all_stakers_info` function, to unify the response schema with Node.js SDK.
- Updated relevant tests.
Closes #648
=> fix: sdk staking client to add staker address when getting staker info

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/legacy_encryption.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_encryption.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_legacy_encryption.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/utils/encryption.py
Add legacy encryption to Python SDK
https://www.notion.so/human-protocol/Legacy-Encryption-da50df3190684e8782bc92b8be2d9b91
Added legacy-encryption file inside Python SDK with ECIES encryption and its tests
Run make run-tests inside Python SDK folder
=> Add legacy encryption to Python SDK

packages/apps/reputation-oracle/server/src/app.module.ts, packages/apps/reputation-oracle/server/src/common/interfaces/manifest.ts, packages/apps/reputation-oracle/server/src/modules/manifest/manifest.controller.spec.ts, packages/apps/reputation-oracle/server/src/modules/manifest/manifest.controller.ts, packages/apps/reputation-oracle/server/src/modules/manifest/manifest.dto.ts, packages/apps/reputation-oracle/server/src/modules/manifest/manifest.module.ts, packages/apps/reputation-oracle/server/src/modules/manifest/manifest.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/manifest/manifest.service.ts, packages/apps/reputation-oracle/server/test/constants.ts, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/legacy_encryption.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_encryption.py
Exchange oracle needs to call reputation oracle manifest endpoint to get manifest data.
- New module `Manifest` is added to the reputation oracle.
- Relevant test cases are added.
Closes #655
=> [Fortune] [Reputation Oracle] Add manifest endpoint

packages/apps/job-launcher/server/src/modules/job/job.service.ts, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/legacy_encryption.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_encryption.py
When the job was launched, the manifest validated Fortune type tasks, but did not correctly validate IMAGE_LABEL_BINARY type tasks.
- Updated `validateManifest` method.
`POST /job/fortune`- Wait a launch stage
`POST /job/cvat` - Wait a launch stage
`yarn test`
[[Job Launcher] - Fix manifest validation for CVAT type#689](https://github.com/humanprotocol/human-protocol/issues/689)
=> [Job Launcher] - Fix manifest validation for CVAT type

packages/apps/reputation-oracle/server/src/common/enums/job.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.dto.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/legacy_encryption.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_encryption.py
Deprecated [JobMode enum type](https://github.com/humanprotocol/human-protocol/blob/0dc320f95b5d96227e198c9fe3e620a3c548c9d2/packages/apps/reputation-oracle/server/src/common/enums/job.ts#L1) and related data because It is no longer up to date and used.
- Removed JobMode enum type
- Updated manifest 
- Updated tests
`yarn test`
[[Reputation Oracle] - Deprecate JobMode enum type and related data#685](https://github.com/humanprotocol/human-protocol/issues/685)
=> [Reputation Oracle] Removed job mode type

packages/apps/job-launcher/server/src/modules/job/job.dto.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts
Suggest a fee management in job launcher
- Fee saved in job launcher database is only the fee charged by the job launcher itself
- Remove fee value from manifest, it is not a relevant value during the escrow process
- The payment stored in the database is fundAmount + jobLauncherFee
=> suggest fee management in job launcher

packages/apps/fortune/exchange-oracle/server/src/common/config/env.ts, packages/apps/fortune/exchange-oracle/server/src/modules/job/job.controller.spec.ts, packages/apps/fortune/exchange-oracle/server/src/modules/job/job.module.ts, packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.spec.ts, packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts, packages/sdk/typescript/human-protocol-sdk/src/constants.ts
Exchange Oracle should get the manifest from Reputation Oracle instead of pulling it from s3 bucket directly.
- Reputation Oracle URL is loaded from env variable.
- Added a http request to reputation endpoint to get manifest.
- Updated test cases.
Closes #656
=> [Fortune] [Exchange oracle] Get manifest data from reputation oracle

.husky/pre-commit
Now, pre-commit runs black formatting of python files, even if they are not changed in the commit. This needs to be fixed, so that it should be called, only when python file is changed in the commit.
- Fixed `pre-commit` bash script, to check if python file is changed before running black formatting.
=> [Monorepo] Fix: Husky pre-commit to run black formatting when python file is changed

.github/workflows/ci-test-cvat.yaml, packages/examples/cvat/exchange-oracle/poetry.lock, packages/examples/cvat/exchange-oracle/pyproject.toml, packages/examples/cvat/exchange-oracle/src/modules/api.py, packages/examples/cvat/exchange-oracle/src/modules/chain/escrow.py, packages/examples/cvat/exchange-oracle/src/modules/chain/web3.py, packages/examples/cvat/exchange-oracle/src/validators/signature.py, packages/examples/cvat/exchange-oracle/tests/api/modules/oracle_webhook/test_jl_webhook.py, packages/examples/cvat/exchange-oracle/tests/integration/modules/chain/test_escrow.py, packages/examples/cvat/exchange-oracle/tests/utils/constants.py
Signature verification for incoming webhooks in Exchange Oracle
Add new method to retrieve the Job Launcher address from the escrow and verify if it is the signer of the incoming webhook
#646
=> Exchange Oracle webhooks signature verification

packages/examples/cvat/exchange-oracle/poetry.lock
Update cryptography vulnerable version
Update `cryptography@41.0.1` to `cryptography@41.0.2`
`docker-compose -f docker-compose.test.yml up --build test --attach test`
=> Update Exchange Oracle dependencies

packages/apps/job-launcher/server/src/modules/payment/payment.controller.ts, packages/apps/job-launcher/server/src/modules/payment/payment.dto.ts
**Describe the bug**
Fixed behaviour, when we send request to `/payment/rates` endpoint we receive a rate for a pair, we got a 404 response, now we receive correct rate value.
`GET /payment/rates` - hmt:usd
[[Job Launcher] Fix 404 for /payment/rates endpoint#717](https://github.com/humanprotocol/human-protocol/issues/717)
=> [Job Launcher] Added fix for get rate route

packages/apps/job-launcher/server/src/common/interfaces/user.ts, packages/apps/job-launcher/server/src/modules/auth/auth.service.spec.ts, packages/apps/job-launcher/server/src/modules/payment/payment.service.spec.ts, packages/apps/job-launcher/server/src/modules/payment/payment.service.ts, packages/apps/job-launcher/server/src/modules/user/user.controller.ts, packages/apps/job-launcher/server/src/modules/user/user.module.ts, packages/apps/job-launcher/server/src/modules/user/user.service.spec.ts, packages/apps/job-launcher/server/src/modules/user/user.service.ts
Added the ability to get a custom balance by calling an `GET user/balance` endpoint.
- Added new `GET user/balance` endpoint
- Added get balance service method
- Added payment service unit tests
- Added user service unit tests
- Added request to update documentation
`GET /user/balance`
`yarn test`
[[Job Launcher] Create GET /user/balance endpoint#719](https://github.com/humanprotocol/human-protocol/issues/719)
=> Added get user balance with tests

packages/sdk/typescript/human-protocol-sdk/src/kvstore.ts
In the constructor, the address of the EscrowFactory was specified, and not the address of the KVStore storage, for this reason, requests to the contract fell with an Ethereum error. 
Correct contract address in the constructor was set.
`yarn test`
[[SDK] Fix contract address in KVStoreClient constructor#722](https://github.com/humanprotocol/human-protocol/issues/722)
=> [SDK] Fixed contract address in KVStoreClient

packages/sdk/python/human-protocol-sdk/Pipfile, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/kvstore.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/utils.py, packages/sdk/python/human-protocol-sdk/setup.py, packages/sdk/python/human-protocol-sdk/test/e2e/test_staking.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_kvstore.py
Fully support python 3.10 & 3.11
Updated web3 package to the latest
from web3 == 6.0.0 they started to use pythonic naming. so isAddress  is now is_address.
As far as I checked changelog there were no changes that affected SDK logic-wise
=> Update web3 to support python 3.10 & 3.11

packages/apps/job-launcher/server/src/common/constants/errors.ts, packages/apps/job-launcher/server/src/modules/job/job.controller.ts, packages/apps/job-launcher/server/src/modules/job/job.dto.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts
We need `/result` endpoint in job launcher to download result details.
- Added an endpoint to job controller.
- Added a new service function that uses StorageClient to download result.
- Added unit tests for service function.
Closes #106
=> [Fortune] [Job Launcher] download result endpoint

packages/apps/job-launcher/server/src/common/constants/errors.ts, packages/apps/job-launcher/server/src/common/enums/payment.ts, packages/apps/job-launcher/server/src/database/migrations/1691485394906-InitialMigration.ts, packages/apps/job-launcher/server/src/modules/payment/payment.controller.ts, packages/apps/job-launcher/server/src/modules/payment/payment.dto.ts, packages/apps/job-launcher/server/src/modules/payment/payment.entity.ts, packages/apps/job-launcher/server/src/modules/payment/payment.service.spec.ts, packages/apps/job-launcher/server/src/modules/payment/payment.service.ts
Save payment when calling createFiatPayment and link it to user, otherwise if someone has a paymentId from another user that was not confirmed yet, he could add it to his balance.
- Updated migrations
- Added new payment status enum
- Updated payment entity
- Updated payment service
- Updated unit tests
`yarn test`
[Job Launcher - Link payment with user#748](https://github.com/humanprotocol/human-protocol/issues/748)
=> [Job Launcher] Added payment link logic

packages/examples/cvat/recording-oracle/poetry.lock, packages/examples/cvat/recording-oracle/pyproject.toml, packages/examples/cvat/recording-oracle/src/modules/agreement/__init__.py, packages/examples/cvat/recording-oracle/src/modules/agreement/measures.py, packages/examples/cvat/recording-oracle/src/modules/agreement/utils.py, packages/examples/cvat/recording-oracle/src/modules/agreement/validations.py, packages/examples/cvat/recording-oracle/src/modules/webhook/api_schema.py, packages/examples/cvat/recording-oracle/src/modules/webhook/process_intermediate_results.py, packages/examples/cvat/recording-oracle/tests/testresources/recording_oracle_dummy_input.json, packages/examples/cvat/recording-oracle/tests/unit/modules/agreement/conftest.py, packages/examples/cvat/recording-oracle/tests/unit/modules/agreement/test_measures.py, packages/examples/cvat/recording-oracle/tests/unit/modules/agreement/test_utils.py, packages/examples/cvat/recording-oracle/tests/unit/modules/webhook/conftest.py, packages/examples/cvat/recording-oracle/tests/unit/modules/webhook/test_process_intermediate_results.py
This PR adds Agreement Measures to the results of the CVAT Recording Oracle and changes the output format.
Closes #761.
- Minor refactoring of module structure.
- Validation functions moved to new file (`validations.py`).
- `utils.py` file added.
- Added new convenience function (`./utils/confusion_matrix_from_sequence` to convert sequences of data into an incidence matrix. Needed in recording oracle.
- Relaxed some validations, as the constraints were harsher than intended.
- Rewrote existing processing of results of `process_image_label_binary_intermediate_results` using pandas. Should be more flexible for additions / changes in the future. The output format now looks like [this](https://www.notion.so/human-protocol/Inter-Rater-Agreement-Example-73a9b00590a742fe8219816c09f1adab?pvs=4#9a1 …
=> [CVAT][Recording Oracle] Add Inter Rater Agreement Measures to Recording Oracle Output

packages/sdk/python/human-protocol-sdk/Pipfile, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/storage.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_escrow.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_storage.py
Added ability to upload encrypted file using `StorageClient.upload_files` function.
Added possibility to skip `manifest_url` validation when `EscrowConfig` is creating. For docker containers URL is tracked as invalid.
Example: `http://bucket:8888`
Fix bug inside `EscrowClient.create_escrow` function: `processLog` call replaced on `process_log` call.
Upload encrypted file.
Possibility to skip `manifest_url` validation.
Fix `EscrowClient.create_escrow` function.
=> Upload encrypted file

packages/apps/job-launcher/server/src/common/constants/payment.ts, packages/apps/job-launcher/server/src/common/enums/payment.ts, packages/apps/job-launcher/server/src/common/utils/decimal.ts, packages/apps/job-launcher/server/src/common/utils/index.ts, packages/apps/job-launcher/server/src/database/migrations/1691485394906-InitialMigration.ts, packages/apps/job-launcher/server/src/modules/auth/auth.service.spec.ts, packages/apps/job-launcher/server/src/modules/auth/auth.service.ts, packages/apps/job-launcher/server/src/modules/job/job.controller.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts, packages/apps/job-launcher/server/src/modules/payment/payment.controller.ts, packages/apps/job-launcher/server/src/modules/payment/payment.dto.ts, packages/apps/job-launcher/server/src/modules/payment/payment.service.spec.ts, packages/apps/job-launcher/server/src/modules/payment/payment.service.ts, packages/apps/job-launcher/server/src/modules/user/user.service.ts, packages/apps/job-launcher/server/test/constants.ts
Erros fixed after manual testing
1. Fix in getrates for cases where from and to are the same. For example for usd to usd coingecko return 0.9... instead of 1.
2. Don't send verification email to users that are not in pending status.
3. Fix getResult endpoint. Previous implementation didn't make sense.
4. Fix math round in create fiat payment. Cannot round "randomly". Use decimals library and Math.Ceil to round up.
5. Save payment id instead of payment secret when creating a fiat payment.
6. In createCryptoPayment and chainId to findOne call, since we might have the same transaction hash in different chains.
7. Create job endpoint is considering that the fundAmount is HMT, but it should be USD.
yarn test
=> Job Launcher - fix bugs of job launcher

packages/apps/reputation-oracle/server/src/modules/reputation/reputation.service.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.dto.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts, packages/apps/reputation-oracle/server/test/constants.ts
This PR makes the Reputation Oracle compatible with the new CVAT output format.
- New Classes were added to `webservice.dto.ts`
- `webhook.service.ts` was adjusted to work with new classes.
- Mock Object for new Output Format was added.
- Tests were adjusted to use new data format.
`yarn run test`
closes #811
=> [CVAT] [Reputation Oracle] Align with CVAT example's new recording oracle output format.

packages/apps/job-launcher/server/src/database/migrations/1691485394906-InitialMigration.ts, packages/apps/job-launcher/server/src/modules/auth/auth.entity.ts, packages/apps/job-launcher/server/src/modules/job/job.entity.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts, packages/apps/job-launcher/server/src/modules/payment/payment.dto.ts, packages/apps/job-launcher/server/src/modules/payment/payment.entity.ts
For ensure job cancelation correct, withdrawal payment related with the particular job id need to be failed, for this purpose job id field was added to payment entity.
- Added job id property to the payment entity 
- Updated migration
- Updated dto
- Updated unit tests 
**The assumption (for simplicity) that one job has one payment works. The solution implements a one-to-one relationship.**
[[Job Launcher] Add job id property to payment entity#834](https://github.com/humanprotocol/human-protocol/issues/834)
=> [Job Launcher] Added job id relation to the payment

packages/core/README.md, packages/core/contracts/EscrowFactory.sol, packages/core/contracts/test/EscrowFactoryV0.sol, packages/core/test/EscrowFactory.ts, packages/core/test/RewardPool.ts, packages/core/test/Staking.ts, packages/examples/fortune/launcher/server/src/plugins/escrow.ts, packages/examples/fortune/reputation-oracle/src/services/escrow.test.ts, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py, packages/sdk/python/human-protocol-sdk/test/e2e/test_staking.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_escrow.py, packages/sdk/typescript/human-protocol-sdk/src/escrow.ts, packages/sdk/typescript/human-protocol-sdk/test/escrow.test.ts, packages/sdk/typescript/subgraph/schema.graphql, packages/sdk/typescript/subgraph/src/mapping/EscrowFactory.ts, packages/sdk/typescript/subgraph/template.yaml
We need to add JobRequesterId to createEscrow function of EscrowFactory.
- Added jobRequesterId to createEscrow function.
- Emit new event `LaunchedV2` with additional param.
- Added handler in subgraph
- Updated SDK function & doc
Closes #842
=> Feat: Add JobRequesterId to createEscrow function

packages/apps/fortune/recording-oracle/src/modules/job/job.service.ts, packages/apps/job-launcher/server/src/common/constants/errors.ts, packages/apps/job-launcher/server/src/common/constants/index.ts, packages/apps/job-launcher/server/src/common/enums/webhook.ts, packages/apps/job-launcher/server/src/common/guards/index.ts, packages/apps/job-launcher/server/src/common/guards/signature.auth.spec.ts, packages/apps/job-launcher/server/src/common/guards/signature.auth.ts, packages/apps/job-launcher/server/src/common/types/request.ts, packages/apps/job-launcher/server/src/common/utils/signature.ts, packages/apps/job-launcher/server/src/modules/job/job.controller.ts, packages/apps/job-launcher/server/src/modules/job/job.dto.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
There may be a case where [CVAT] Exchange Oracle fails to create a task on the CVAT side and throws an error, and it should be able to notify the job launcher of this. Now, the job launcher will be notified about errors and performing the necessary actions with the escrow.
- Implemented new endpoint to controller.
- Implemented webhook logic to the service.
- Created and updated unit tests.
**POST /cvat/escrow-failed-webhook**
```
Payload:
{
"escrow_address": "0x60C5185b06CEa5cA7d3BDE8f1292Bfb8729E24d5", 
"chain_id": 80001, 
"event_type": "task_creation_failed", 
"reason": "invalid manifest"
}
Signature:
0x5c89bb473d912ec0299a3577f8ed73216f6647227b1de2dc45911b895944937300ec62c152eca353be21e3043437e1fb03d1f057abc0a7e24acc484df19004ff1b
Address:
0x93DcC58cDDCB026984821DF7bbef46400E20394C …
```
=> [Job Launcher] Exchange Oracle webhook

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/storage.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/utils.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_escrow.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_utils.py, packages/sdk/typescript/human-protocol-sdk/src/escrow.ts, packages/sdk/typescript/human-protocol-sdk/test/escrow.test.ts
1. Add `get_manifest_hash` function to escrow that returns stored `manifestHash` for python sdk.
2. Add `getManifestHash` for typescript sdk.
3. Extend `validators.url` to track docker network urls as valid.
`get_manifest_hash` function
1. Create and setup escrow
4. Try to get hash, e.g. `escrow_client.get_manifest_hash("escrow_address")`
=> Add getManifestHash function for python/typescript sdk. Allow docker-network URLs.

.github/dependabot.yml, .github/workflows/ci-test-cvat-exchange-oracle.yaml, .github/workflows/ci-test-cvat-recording-oracle.yaml
Dependabot alert needs to be targeting `develop` branch.
CVAT CI test should be running upon python SDK change.
- Updated CVAT CI workflow configuration for the action to be triggered upon SDK change
- Added `dependabot.yml` to use `develop` as target branch for PRs.
=> Fix: cvat ci test run trigger condition and add dependabot config

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/statistics.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/statistics.py, packages/sdk/typescript/human-protocol-sdk/src/graphql/queries/statistics.ts, packages/sdk/typescript/human-protocol-sdk/src/interfaces.ts
- Updated GraphQL query to use orderBy timestamp desc, and then support limit param, which is 1000 by default.
Closes #874
=> fix: [SDK] statistics - add limit param and order by timestamp in descending order

packages/sdk/python/human-protocol-sdk/Pipfile, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/agreement/__init__.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/agreement/bootstrap.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/agreement/measures.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/agreement/utils.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/agreement/validations.py, packages/sdk/python/human-protocol-sdk/setup.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/agreement/conftest.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/agreement/test_bootstrap.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/agreement/test_measures.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/agreement/test_utils.py
This PR adds a submodule to the the python sdk for calculating Interrater Agreement.
- Copied source code from CVAT example to python sdk.
- Copied tests from CVAT example to python sdk tests.
- Added dependencies `hypothesis` (dev) and `pyerf` and `numpy`.
`make unit-test`
Closes #777.
=> [SDK][Agreement] Add agreement package to sdk.

packages/apps/job-launcher/server/src/common/guards/signature.auth.spec.ts, packages/apps/job-launcher/server/src/common/guards/signature.auth.ts, packages/apps/job-launcher/server/src/common/utils/signature.spec.ts, packages/apps/job-launcher/server/src/common/utils/signature.ts, packages/apps/job-launcher/server/src/modules/job/job.controller.ts, packages/apps/job-launcher/server/src/modules/job/job.dto.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts, packages/apps/reputation-oracle/server/src/common/guards/signature.auth.spec.ts, packages/apps/reputation-oracle/server/src/common/guards/signature.auth.ts, packages/apps/reputation-oracle/server/src/common/utils/signature.spec.ts, packages/apps/reputation-oracle/server/src/common/utils/signature.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.controller.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.dto.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
Removed `oracleType` verification during webhook call on Job Launcher and Reputation oracle side.
[[Common] Remove verification oracleType during webhook call#888](https://github.com/humanprotocol/human-protocol/issues/888)
=> [Common] Removed `oracleType` verification

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/storage.py, packages/sdk/typescript/human-protocol-sdk/src/storage.ts, packages/sdk/typescript/human-protocol-sdk/src/types.ts
We are deprecating the storage module. Now we just want to mark as deprecated, since we have some old code base which needs migration.
- Added deprecated note for Python/Node SDK.
Closes #886
=> feat: Mark storage module as deprecated

packages/sdk/typescript/human-protocol-sdk/src/escrow.ts, packages/sdk/typescript/human-protocol-sdk/test/escrow.test.ts
Returned the hash of the transaction as the result of the cancel method.
The transaction hash is required when we process a refund to the user. The idea is to wait for a transaction to receive a certain number of confirmations before we receive logs of the last transfer.
Updated `cancel method to SDK
Updated unit tests to SDK
`yarn test`
[SDK] [Typescript] Return transaction hash as result of cancel method#916
=> [SDK] [Typescript] Return transaction hash as result of cancel method

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/escrow.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_escrow.py, packages/sdk/typescript/human-protocol-sdk/src/graphql/queries/escrow.ts, packages/sdk/typescript/human-protocol-sdk/src/interfaces.ts, packages/sdk/typescript/human-protocol-sdk/test/escrow.test.ts
Add the jobRequesterId filter to retrieve all escrows created by a specific user
Use Subgraph to get filter by jobRequesterId in both SDK
`yarn test` in typescript and `make run-test' in python
#929
=> [SDK] Add jobRequesterId to escrows filter

packages/apps/job-launcher/server/src/common/enums/job.ts, packages/apps/job-launcher/server/src/common/utils/status.ts, packages/apps/job-launcher/server/src/modules/job/job.controller.ts, packages/apps/job-launcher/server/src/modules/job/job.dto.ts, packages/apps/job-launcher/server/src/modules/job/job.repository.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts
Modify the old getJobByStatus to request the information on chain and check it against the information we have in the database to show all the escrows with their current statuses
Use the new getEscrows SDK method to request the information from Subgraph. Once we have all the escrows, we have to check them against the TO_CANCEL escrows we have in the database to update them because the TO_CANCEL status does not exist in blockchain
`yarn test`
#936
=> [Job Launcher] Modify getJobByStatus to query Subgraph

packages/examples/cvat/recording-oracle/tests/utils/setup_escrow.py, packages/sdk/python/human-protocol-sdk/example.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/constants.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/kvstore.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/utils.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/agreement/test_measures.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_escrow.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_kvstore.py
To increase percentage of successfully handled transactions we need to provide custom gas limit to it to avoid `out of gas` errors.
Add gas limit to transaction.
Define gas limit and deploy a job. Check gas limit of handled transaction.
=> Implement GAS_LIMIT usage for python sdk

packages/apps/job-launcher/server/src/common/interfaces/job.ts, packages/apps/job-launcher/server/src/database/migrations/1696331060184-AddFailedReasonToJobs.ts, packages/apps/job-launcher/server/src/modules/job/job.entity.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts
Added reason property to escrow failed webhook payload
- Updated job service `escrowFailedWebhook` method.
- Updated unit tests.
- Added new migration.
`yarn test`
[[Job Launcher] Add reason property to escrow failed webhook payload#978](https://github.com/humanprotocol/human-protocol/issues/978)
=> [Job Launcher] Added reason property to escrow failed webhook payload

packages/apps/job-launcher/server/src/common/constants/errors.ts, packages/apps/job-launcher/server/src/common/constants/index.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts
Fixed a bug in which escrow can be canceled at any status.
- Updated `requestToCancelJob` method.
- Updated tests
`yarn test`
[[Job Launcher] Completed or canceled jobs cannot be cancelled#990](https://github.com/humanprotocol/human-protocol/issues/990)
=> [Job Launcher] Fixed job cancellation statuses

packages/apps/job-launcher/server/src/common/constants/errors.ts, packages/apps/job-launcher/server/src/modules/auth/auth.service.spec.ts, packages/apps/job-launcher/server/src/modules/auth/auth.service.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
Generated a new token to restore the password if there was a pending token existing, the old one has to be removed first. 
- Removed existing token
- Generated new token
- Updated unit tests
`yarn test`
[[Job Launcher] Restore password improvement#854](https://github.com/humanprotocol/human-protocol/issues/854)
=> [Job Launcher] Improved restore password logic

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/agreement/bootstrap.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/agreement/measures.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/agreement/conftest.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/agreement/test_measures.py
This PR fixes the value range for `fleiss_kappa`, `cohens_kappa` and `percentage` to stay within, even in edge cases.  
- Measures do not return `np.nan` anymore, when all annotations have the same label or annotation data contains only a single annotator. Instead 1.0 is returned and a warning is raised. This is done to ensure measures will be more robust to degenerate cases yet still inform the users about potential problems in their data. This also helps with bootstrapping, as the confidence intervals cannot be `nan` anymore.
- Extended tests to ensure value range.
pytest PYTHON_SDK_DIR/test/agreement
=> [SDK][Agreement] Fix value range for measures.

packages/apps/job-launcher/server/src/common/guards/signature.auth.ts, packages/apps/job-launcher/server/src/common/utils/signature.ts, packages/apps/job-launcher/server/src/modules/payment/payment.controller.ts, packages/apps/job-launcher/server/src/modules/payment/payment.service.spec.ts, packages/apps/job-launcher/server/src/modules/payment/payment.service.ts, packages/apps/job-launcher/server/test/constants.ts
Add a signature to `payment/crypto` payload and verify that the message has been signed by the same address that sent the transaction hash
Add the signature to the `createCryptoPayment` method
Update tests
`yarn test`
Close #953
=> [Job Launcher] Verify sender of crypto payment

packages/apps/job-launcher/server/src/common/enums/role.ts, packages/apps/job-launcher/server/src/common/guards/signature.auth.spec.ts, packages/apps/job-launcher/server/src/common/guards/signature.auth.ts, packages/apps/job-launcher/server/src/modules/job/job.controller.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts
Add signature to all webhook endpoints in Job Launcher
- Improve signature guard
- Add signature verification to all webhook endpoints
- Format code
`yarn test`
Close #1027
=> [Job Launcher] Add signature to all webhook calls

packages/apps/job-launcher/server/src/common/constants/index.ts, packages/apps/job-launcher/server/src/modules/auth/auth.service.spec.ts, packages/apps/job-launcher/server/src/modules/auth/auth.service.ts, packages/apps/job-launcher/server/src/modules/sendgrid/sendgrid.service.ts, packages/apps/reputation-oracle/server/src/common/constants/index.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts, packages/apps/reputation-oracle/server/src/modules/sendgrid/sendgrid.service.ts
Set up email templates in Job Launcher and Reputation Oracle
Add email templates
Update tests
`yarn test`
Close #1015 #1002
=> [Job Launcher][Reputation Oracle] Add Sendgrid email templates

packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.spec.ts, packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts
We don't necessarily need to make a contract call to get webhook url from KVStore.
We have StakingClient that provides getLeader function, which returns all the data of the oracles.
We need to use this function to get Webhook URL of job launcher & recording oracle.
- Removed KVStore contract call.
- Used `getLeader` function of  `StakingClient` for webhook URL.
- Updated relevant tests.
Closes #1031
=> [Fortune] [Exchange Oracle] fix: use StakingClient getLeader to get webhook url for oracles

packages/apps/fortune/exchange-oracle/server/src/common/interfaces/job.ts, packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.spec.ts, packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts, packages/apps/fortune/exchange-oracle/server/src/modules/storage/storage.service.spec.ts, packages/apps/fortune/exchange-oracle/server/src/modules/storage/storage.service.ts, packages/apps/fortune/recording-oracle/src/common/enums/job.ts, packages/apps/fortune/recording-oracle/src/common/interfaces/job.ts, packages/apps/fortune/recording-oracle/src/modules/job/job.service.spec.ts, packages/apps/fortune/recording-oracle/src/modules/job/job.service.ts, packages/apps/job-launcher/server/src/modules/job/job.controller.ts
The intermediate results file should include invalid answers so the Reputation Oracle knows which workers submitted a bad solution an the reputation can be decreased
Remove ISolutionsFile interface
Add invalid answers to intermediate results
Fix tests
`yarn test`
Close #1088
=> [Recording Oracle] Include invalid solutions in intermediate results

packages/apps/job-launcher/server/src/common/utils/status.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts
Fix problem when job launcher is not returning the list of Launched escrow properly and get the escrows with status Partial or Paid when user request Launched jobs in getJobList
Add case comparison between database and subgraph data and obtain partial and paid escrows lists
`yarn test`
Closes #1108 #1118
=> [Job Launcher] Fix case comparison and obtain partial and paid escrows

packages/sdk/python/human-protocol-sdk/example.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/escrow.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/filter.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/staking.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/statistics.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_escrow.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_staking.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/test_statistics.py
For our getter functions in Python SDK, we need more strict typing than dict.
- Changed couple field types on `EscrowData` class.
- Used `get` function for the dict values returned from subgraph call.
- Moved `getLeader`, `getLeaders`, and `getReward` function to `StakingUtils` class as static methods.
- `StatisticsClient` does not accept `Web3` instance, but just `chain_id`, since it's not supposed to do any write operations.
- GitBook changed (https://app.gitbook.com/o/gVcp9m9Bobj6V368GNOW/s/FFmrUy0ymWxdSjtXZkJe/~/changes/76/)
Closes #662
=> [SDK] feat: add more typing to getter functions of python sdk

packages/apps/reputation-oracle/server/src/common/constants/errors.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
Remove getBalance after bulkpayout because the escrow balance is not updated instantaneously
Check number of solutions in Reputation Oracle before uploading final results
Remove getBalance check
Check if the number of valid solutions match with the number of solutions requested
Closes #1151
=> [Reputation Oracle] Remove getBalance check and check number of solutions received

packages/apps/job-launcher/server/src/common/constants/index.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts
Failed jobs should also be allowed to cancel.
Add failed jobs to the list of statuses that can be cancelled
Add a test for status
`yarn test`
=> Job Luancher - fix allowed status to cancel job

packages/examples/cvat/exchange-oracle/src/cvat/api_calls.py, packages/examples/cvat/exchange-oracle/src/endpoints/exchange.py, packages/examples/cvat/exchange-oracle/src/services/cvat.py
During account binding exchange oracle was throwing an error due to the incomplete api call to CVAT
- Now all CVAT work is done within an organization
- Now admin rights are not required for the CVAT user
- Now annotators will be members of the CVAT organization
- Added cleanup of the user with the previous email on user email change in the `/register` endpoint
- Added `cvat_org_slug` to `memberships_api.list()` api call to avoid empty response
To close #1153
=> [CVAT][Exchange oracle] Fix `/register` endpoint

packages/apps/reputation-oracle/server/src/common/config/index.ts, packages/apps/reputation-oracle/server/src/common/config/s3.ts, packages/apps/reputation-oracle/server/src/common/interfaces/s3.ts, packages/apps/reputation-oracle/server/src/common/utils/index.ts, packages/apps/reputation-oracle/server/src/modules/storage/storage.module.ts, packages/apps/reputation-oracle/server/src/modules/storage/storage.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/storage/storage.service.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.module.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts, packages/apps/reputation-oracle/server/test/constants.ts
Add storage module on Reputation Oracle to remove dependency on deprecated SDK storage module
- Create a new Storage module
- Remove dependencies to SDK storage module
`yarn test`
#1158
=> [Reputation Oracle] Storage module

packages/apps/job-launcher/server/src/common/constants/errors.ts, packages/apps/job-launcher/server/src/common/utils/index.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts
Added new regular expressions to the URL parser. The URL parser must be able to work with the link type provided by AWS.
- Added new regex.
- Added error handling
Send `POST http://127.0.0.1:5001/job/cvat`
with `dataUrl` param `https://cvat-test-dataset.s3.eu-west-1.amazonaws.com` or `https://s3.eu-west-1.amazonaws.com/cvat-test-dataset`
[[Job Launcher] Add AWS regex to url parser#1176](https://github.com/humanprotocol/human-protocol/issues/1176)
=> Added new regex to parse url util

packages/apps/job-launcher/server/README.md
This pull request addresses an issue with outdated information in the project's README file. The previous version of the README provided instructions for setting up a PostgreSQL database with the name "reputation-oracle", which is no longer relevant to the current state of the project. The instructions have been updated to reflect the correct database name, "job-launcher", ensuring that new developers or contributors can set up their development environment accurately and efficiently.
Updated the PostgreSQL setup instructions in the README file to change the database name from "reputation-oracle" to "job-launcher".
Updated the user permissions instructions to ensure consistency with the new database name.
Follow the updated instructions in the README to set up the PostgreSQL database. …
=> Fix readme job launcher server

packages/apps/job-launcher/client/src/hooks/useJobDetails.ts, packages/apps/job-launcher/client/src/pages/Job/JobDetail/index.tsx, packages/apps/job-launcher/client/src/services/job.ts, packages/apps/job-launcher/client/src/types/index.ts
Show job results when exist
Make a request to the getResults endpoint to get solutions. In the Fortune case, display a table with the value and status. Otherwise, display the results URL.
#1219
=> [Job Launcher] Show job results in job details

docs/sdk/typescript/classes/base.BaseEthersClient.md, docs/sdk/typescript/classes/encryption.Encryption.md, docs/sdk/typescript/classes/encryption.EncryptionUtils.md, docs/sdk/typescript/classes/escrow.EscrowClient.md, docs/sdk/typescript/classes/escrow.EscrowUtils.md, docs/sdk/typescript/classes/kvstore.KVStoreClient.md, docs/sdk/typescript/classes/staking.StakingClient.md, docs/sdk/typescript/classes/statistics.StatisticsClient.md, docs/sdk/typescript/classes/storage.StorageClient.md, docs/sdk/typescript/modules.md, docs/sdk/typescript/modules/base.md, packages/sdk/typescript/human-protocol-sdk/package.json, packages/sdk/typescript/human-protocol-sdk/src/base.ts, packages/sdk/typescript/human-protocol-sdk/src/error.ts, packages/sdk/typescript/human-protocol-sdk/src/escrow.ts, packages/sdk/typescript/human-protocol-sdk/src/kvstore.ts, packages/sdk/typescript/human-protocol-sdk/src/staking.ts, packages/sdk/typescript/human-protocol-sdk/src/statistics.ts, packages/sdk/typescript/human-protocol-sdk/src/utils.ts, packages/sdk/typescript/human-protocol-sdk/test/escrow.test.ts, packages/sdk/typescript/human-protocol-sdk/test/kvstore.test.ts, packages/sdk/typescript/human-protocol-sdk/test/staking.test.ts
Sometimes, gas estimation is too low, and on-chain txn are stuck from Typescript SDK.
Adding gas price multiplier to SDK build, so that it can increase/decrease gas price accordingly.
- Implemented new class `BaseEthersClient`, which has common functions of other clients.
- Modified on-chain write calls to override gas price, if multiplier is specified.
- Updated docs, and test cases.
Close #1250
=> [SDK] [Typescript] Implement gas price multiplier

packages/apps/job-launcher/server/src/modules/job/job.controller.ts
This pull request introduces an important update to the Job Launcher module for our Discord app server. The main focus of this change is to integrate an apiKey decorator for the getResult API endpoint. 
Implemented an apiKey decorator in the getResult API endpoint.
- Launch a Job: Use the updated Job Launcher to initiate a new job.
- Attempt Unauthorized Access: Try to access the getResult endpoint without the API key to verify that access is denied.
- Authorized Access Testing: Access the getResult endpoint with the correct API key and validate that the job results are correctly retrieved.
=> [JobLauncher Server] Added ApiKey decorator on getResult endpoint

packages/apps/fortune/exchange-oracle/server/src/modules/job/job.controller.ts, packages/apps/job-launcher/server/src/modules/job/job.controller.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.controller.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
Make cron jobs compatible with Vercel and GCP
- Add await to cron job endpoints for Vercel
- Add cron expression to functions for GCP
`yarn test`
=> Job Launcher - Reputation Oracle - Make cron jobs compatible with Vercel and GCP

packages/apps/reputation-oracle/server/src/common/config/env.ts, packages/apps/reputation-oracle/server/src/modules/storage/storage.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/storage/storage.service.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts, packages/apps/reputation-oracle/server/test/constants.ts
All those intermediate results, final results, and manifests are encrypted, so we need to decrypt it before we access it.
- Add decryption after downloading content from storage.
- Updated test cases.
Closes #1039
=> [Reputation Oracle] Decrypt Intermediate/Final Results/Manifest

packages/apps/faucet-server/package.json, yarn.lock
Adding `@types/cors` dev dependency to the faucet server. The build is failing because of missing type definition.
Closes #1341
=> fix: faucet server build failing

.github/workflows/cd-node-sdk.yaml, .github/workflows/cd-python-sdk.yaml
Use `setuptools == 68.2.2`, since v69 has breaking changes.
=> [Monorepo] [CD] Python SDK - use setuptools==68.2.2

packages/apps/reputation-oracle/server/src/modules/storage/storage.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/storage/storage.service.ts
Fix for an empty file being uploaded to reputation oracle bucket
Using two separate streams for calculating file hash and uploading to s3 bucket
To close #1387
=> [Reputation Oracle] Separate streams for hashing and uploading a file

packages/apps/job-launcher/server/src/common/utils/storage.spec.ts, packages/apps/job-launcher/server/src/common/utils/storage.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts, packages/apps/job-launcher/server/src/modules/storage/storage.service.spec.ts, packages/apps/job-launcher/server/src/modules/storage/storage.service.ts
The method was not properly listing if there were more than 1000 files in the bucket and/or the files were in a nested folder
- Add nested folder fix
- Include pagination in the listing method
- Move the function to utils (no dependency on a service initialization)
- Modify and add tests
`yarn test
`
=> Job Launcher - Fix list objects in bucket function

packages/sdk/typescript/human-protocol-sdk/src/utils.ts
With the new version of Ethers, the way the library displays error messages has changed and we are currently returning a null error
Remove the previous error handling 
Return directly the revert reason from the library
=> [SDK] Fix error messages when reverting transactions

packages/apps/job-launcher/client/src/components/Jobs/Create/schema.ts
Bucket path was required before but it is not always necessary and if you write for example `/` the backend doesn't read the number of objects properly.
Make paths optional
=> Job Launcher Client - Error in Job bounty calculation

packages/apps/job-launcher/server/src/modules/web3/web3.controller.ts, packages/apps/job-launcher/server/src/modules/web3/web3.service.spec.ts, packages/apps/job-launcher/server/src/modules/web3/web3.service.ts
Create an endpoint to retrieve the job launcher address
Create a new endpoint inside web3 controller
Create a new method to return the address in web3 service
`yarn test`
#1484
=> [Job Launcher] Get operator address

packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts
Refactor uploadManifest function to be more generic
Modify input parameters to be like `uploadManifest(requestType: JobRequestType, chainId: ChainId, data: any)`
`yarn test`
#1493
=> [Job Launcher] Refactor uploadManifest

packages/apps/reputation-oracle/server/src/modules/cron-job/cron-job.entity.ts
StartedAt from CronJobEntity cannot be null and needs to be initialized before inserting it.
=> Reputation Oracle - Fix cron jobs

packages/apps/reputation-oracle/server/src/common/config/env.ts, packages/apps/reputation-oracle/server/src/common/guards/cron.auth.ts, packages/apps/reputation-oracle/server/src/modules/cron-job/cron.job.controller.ts, packages/apps/reputation-oracle/server/vercel.json
We need to secure cron jobs triggered by Vercel by adding `CRON_SECRET` env variable.
- Added new `CronAuthGuard` to cron job endpoints.
- Fixed `vercel.json` to trigger correct endpoint for cron jobs.
- Tested triggering cron endpoints on local environment with bearer auth header. This auth header will be set by Vercel automatically on production.
Closes #1663
=> [Reputation Oracle] feat: secure cron job [#1663]

packages/apps/job-launcher/server/src/common/constants/errors.ts, packages/apps/job-launcher/server/src/common/utils/index.ts, packages/apps/job-launcher/server/src/modules/job/job.controller.ts, packages/apps/job-launcher/server/src/modules/job/job.dto.ts, packages/apps/job-launcher/server/src/modules/job/job.interface.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts
Implemented a generic method to JL that can **create/fund/setup** an escrow using the provided manifest. The result of the call will be the escrow address.
**POST** `/job/quick-launch`
```
{
"chain_id": 80001,
"request_type": "FORTUNE",
"manifest_url": <URL>,
"fund_amount": 1
}
```
`yarn test`
[[Job Launcher] Integrate quick-launch feature #1660](https://github.com/humanprotocol/human-protocol/issues/1660)
=> [Job Launcher] Quick launch

packages/core/test/GovernanceUtils.ts
This change speeds up hardhat tests execution in `packages/core` by around 100x times.
On my local machine, it went from `712.65s` to `7.32s`
Used a more efficient way to mine blocks.
`yarn run test`
=> Changed mineNBlocks function to use more efficient way to mine blocks

packages/apps/fortune/exchange-oracle/server/src/app.module.ts, packages/apps/fortune/exchange-oracle/server/src/common/enums/job.ts, packages/apps/fortune/exchange-oracle/server/src/database/migrations/1710760785464-initialMigration.ts, packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.controller.ts, packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.dto.ts, packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.entity.ts, packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.interface.ts, packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.module.ts, packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.repository.ts, packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.service.ts, packages/apps/fortune/exchange-oracle/server/src/modules/job/job.repository.ts, packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts
Create a new assignment in the database when a user requests it
Also create an endpoint to retrieve all assignments
Create assignment module and everything related to it
#1723 #1724
=> Add create assignment and get assignments endpoints in Exchange Oracle

packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.spec.ts, packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.ts, packages/apps/job-launcher/server/src/modules/job/job.module.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts
Send escrow_created webhook when the escrow is completed also in Fortune
Remove the restriction of the webhook only for CVAT 
Move the webhook from cron-job.service.ts to job.service.ts
`yarn test`
#1741
=> [Job Launcher] escrow_created webhook

packages/apps/job-launcher/server/src/modules/job/job.service.ts
The value of the hash was saved as url and the other way around
=> Job Launcher - Fix crossed value

packages/apps/job-launcher/server/src/common/exceptions/auth.filter.ts, packages/apps/job-launcher/server/src/common/guards/apikey.auth.ts, packages/apps/job-launcher/server/src/common/guards/jwt.auth.ts
Fix returned status code when auth token has expired: 403 -> 401.
1. `POST /auth/signin`
2. Wait for the authorization token to expire.
3. Send any auth request
[Job Launcher] Fix returned status code when auth token has expired: 403 -> 401
[#1715](https://github.com/humanprotocol/human-protocol/issues/1715)
=> [Job Launcher] Improved JwtAuthGuard

packages/apps/job-launcher/server/src/modules/webhook/webhook.service.spec.ts, packages/apps/job-launcher/server/src/modules/webhook/webhook.service.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
Oracles webhooks callings are waiting for a 200 response, but the endpoint returns a 201
Switch the expected status code from 200 to 201
yarn test
=> Fix oracles webhook

packages/apps/job-launcher/server/src/modules/job/job.service.ts
Fixed the getDetails method to be able to return job data correctly.
Added handlers for nested properties.
Creates a new job using the `/job/quick-launch` endpoint with a request type other than IMAGE_POINTS or IMAGE_BOXES and invalid manifest, and call `/job/details/:jobId`, it will return data without 500 error.
[Job Launcher] Fix the getDetails method to be able to return job data correctly
[#1714](https://github.com/humanprotocol/human-protocol/issues/1714)
=> [Job Launcher] Fix get details

packages/apps/job-launcher/server/src/database/migrations/1711705135695-updateWebhookIndex.ts, packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts, packages/apps/job-launcher/server/src/modules/webhook/webhook.entity.ts, packages/apps/job-launcher/server/src/modules/webhook/webhook.service.ts
Fixes unique index in webhook schema.
Minor updates.
1. Added `eventType` to unique index in Webhook schema to avoid getting DB duplication errors upon escrow cancellation.
2. Enabled webhook signature for CVAT oracles
3. Check not only for 201 status but for 200 too when webhook is being sent
To close #1785
=> [Job Launcher] Fix unique index in Webhook table

packages/apps/job-launcher/server/src/modules/job/job.service.ts
Fixing a bug when Job Launcher throws an error in case of a `task_creation_failed` event type.
Changed incorrect if statement in `escrowFailedWebhook` method
To close #1794
=> [Job Launcher] Fixed incorrect if statement in `escrowFailedWebhook` method

packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
The webhook was not created after the call. Method `this.webhookRepository.create(...)` did not work as expected.
`this.webhookRepository.create(...)` has been changed to `this.webhookRepository.createUnique(...)`
[Reputation Oracle] Fix create incoming webgook method
[#1799](https://github.com/humanprotocol/human-protocol/issues/1799)
=> [Reputation Oracle] Fixed create incoming webhook method

packages/apps/job-launcher/server/src/modules/job/job.interface.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts, packages/apps/job-launcher/server/test/constants.ts
Changed the get elements count logic for `IMAGE_BOXES_FROM_POINTS` and `IMAGE_SKELETONS_FROM_BOXES`.
- Improved `getCvatElementsCount` method.
- Implemented `generateUrls` method
- Refactored `calculateJobBounty` method
- Implemented unit tests.
`yarn test`
[Job Launcher] Implement new logic for calculate job bounty
[#1807](https://github.com/humanprotocol/human-protocol/issues/1807)
=> [Job Launcher] Updated `getCvatElementsCount` method

packages/apps/fortune/recording-oracle/src/modules/storage/storage.service.ts, packages/sdk/typescript/human-protocol-sdk/package.json, yarn.lock
`crypto` NPM package is deprecated, and is moved to built-in module of Node.js.
- Removed `crypto` dependency from SDK.
=> remove crypto package dependency

packages/apps/reputation-oracle/server/api/app.ts, packages/apps/reputation-oracle/server/src/app-init.ts, packages/apps/reputation-oracle/server/src/main.ts, packages/apps/reputation-oracle/server/vercel.json
Make Reputation Oracle a serverless on Vercel
- Init app as serverless
- Vercel.json update
Test deployment on Vercel
=> Reputation Oracle - Vercel serverless

packages/apps/reputation-oracle/server/src/database/migrations/1712220998800-removeOracleAddress.ts, packages/apps/reputation-oracle/server/src/modules/cron-job/cron-job.service.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook-incoming.entity.ts
Removes an unused field from `WebhookIncomingEntity` 
Removed `oracleAddress` field from `WebhookIncomingEntity`
Temporarily disabled notification to Recording Oracle
=> [Reputation Oracle] Remove unused field from webhook entity

packages/apps/job-launcher/client/src/components/Jobs/StatusToggleButtons.tsx, packages/apps/job-launcher/client/src/layouts/AuthLayout.tsx, packages/apps/job-launcher/client/src/pages/Job/JobList/index.tsx, packages/apps/job-launcher/client/src/types/index.ts, packages/apps/job-launcher/server/src/common/enums/job.ts, packages/apps/job-launcher/server/src/common/utils/status.ts, packages/apps/job-launcher/server/src/database/migrations/1712826368303-addPartialStatus.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts, packages/sdk/typescript/subgraph/src/mapping/Escrow.ts, packages/sdk/typescript/subgraph/tests/escrow/escrow.test.ts
Display escrows with Partially paid status because now in case payouts were triggered but escrow balance is not 0, escrow won't be visible in any of the existing tabs
Job Launcher Server:
- Add Partial status to database
- Add new Partial status to filter and query subgraph
- Update Launched status in DB in case of Partial on chain
Job Launcher Client:
- Add new Partial tab in sidebar and dashboard
Subgraph:
- Update partial escrow status from `Partially Paid` to `Partial`
`yarn test`
#1842
=> [Job Launcher] Display partially paid escrows

packages/examples/cvat/exchange-oracle/src/services/cvat.py, packages/examples/cvat/exchange-oracle/src/services/exchange.py, packages/examples/cvat/exchange-oracle/tests/integration/services/test_cvat.py
- Return only tasks with active assignments in `/tasks?wallet_address=XXX` of Exchange Oracle
This helps to avoid situations where older inactive assignments bloat all the top projects in the response. This problem exists before the #1649 is merged, where it's avoided by pagination and filters.
=> [CVAT-M2] Return only tasks with active assignments in Exchange Oracle

packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts, packages/apps/reputation-oracle/server/src/modules/user/user.controller.ts, packages/apps/reputation-oracle/server/src/modules/user/user.dto.ts, packages/apps/reputation-oracle/server/src/modules/user/user.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/user/user.service.ts
Register address has the public decorator but jwtAuth is required
Disable operator marked as public in swagger but jwtAuth is also required
Check also the string body
Improve decorators usage in `user.controller.ts`
Create a new dto for `disableOperator` endpoint
Fix the status sent to blockchain in `disableOperator`
`yarn test`
#1882
=> [Reputation Oracle] Fix `user.controller.ts`

packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.controller.spec.ts, packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.controller.ts
Requests from other services don't contain the referer property and the server throws an error.
Use host property to avoid the error
`yarn test`
=> Fix serverUrl in getAssignments

packages/apps/job-launcher/server/src/common/utils/storage.ts
Cvat bounties were failing because the url of the bucket was wrong
Replace the first / if the pathname of the bucket start with /
`yarn test`
=> [Job Launcher] Cvat url pathname 

packages/examples/cvat/exchange-oracle/src/core/tasks/simple.py, packages/examples/cvat/exchange-oracle/src/crons/process_recording_oracle_webhooks.py, packages/examples/cvat/exchange-oracle/src/handlers/job_creation.py, packages/examples/cvat/exchange-oracle/tests/integration/cron/test_process_job_launcher_webhooks.py, packages/examples/cvat/exchange-oracle/tests/utils/dataset_helpers.py, packages/examples/cvat/recording-oracle/src/core/config.py, packages/examples/cvat/recording-oracle/src/core/tasks/simple.py, packages/examples/cvat/recording-oracle/src/handlers/process_intermediate_results.py
Prior this PR, Exchange Oracle would create tasks using the full image paths in the input bucket. Recording oracle would validate using the original GT. If the input data has some prefix and the original GT contains paths relative to the input data path (e.g. just the file names), the validation fails, as GT images matching the current validated job file names (which are full) can't be found in the GT dataset.
This PR fixes this by saving an updated GT during task creation in the private Exchange Oracle bucket.
- Added saving of the updated GT during task creation for IMAGE_POINTS and IMAGE_BOXES task types
- Added logging on project return to the annotation state after the validation was rejected
- Increased the default point validity radius to 0.9 (from 0.8). This value seems to be …
=> [CVAT-M2] Fix gt paths in points and bbox annotation tasks

packages/examples/cvat/exchange-oracle/src/handlers/job_creation.py
Before the PR, during GT selection, ambiguous input annotations were excluded, but their matching GT annotations stood in place, and this could lead to incorrect GT-input matches after the exclusion (these matches should have been ambiguous without the first exclusion). In the end, this could result in incorrect GT, that could not be annotated correctly.
This PR changes the approach so that the all initially ambiguous annotations (both GT and input) are excluded simultaneously.
- Fixed GT preparation in the case of multiple overlapping annotations in GT and input points/boxes
- Improved logging
- Fully invisible skeletons with all the points **absent** will be excluded as errors now. Fully invisible, but with at least 1 occluded point will be kept, but excluded from GT till we figure out …
=> [CVAT-M2] Fix GT preparation for boxes from points and skeletons from boxes

packages/examples/cvat/exchange-oracle/src/utils/annotations.py, packages/examples/cvat/recording-oracle/src/handlers/process_intermediate_results.py
This PR allows to use the final exported annotations without additional actions from the user.
- Added removal of common filename prefix in the exported annotations (only the task data path is removed)
- Skeleton is renamed into the point name (so that the skeleton and the point have the same label) in the IMAGE_POINTS task
- Fixed export of GT annotations in the final annotations of the IMAGE_POINTS task. GT annotations were missing or could have incorrect label or position
=> [CVAT-M2] Improve export of merged annotation results

packages/examples/cvat/exchange-oracle/src/handlers/completed_escrows.py
This PR tries to address occasional project export failures in CVAT by moving the export request right before the downloading.
=> [CVAT-M2] Move project annotations request closer to downloading

packages/apps/job-launcher/server/src/common/constants/errors.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts
Change the way of getting elements count for `IMAGE_BOXES` and `IMAGE_POINTS` job types
- Get all elements from dataUrl
- Get elements from gtUrl ("images")
- Make sure that all filenames enlisted in gtUrl ("images") exist in dataset. If not, throw an error.
- Count all elements in dataset and subtract amount of elements in gt ("images")
`yarn test`
#1937
=> [Job Launcher server] Change the way of getting elements count

packages/apps/reputation-oracle/server/src/app.module.ts, packages/apps/reputation-oracle/server/src/common/exceptions/database.filter.ts, packages/apps/reputation-oracle/server/src/common/exceptions/kyc.filter.ts, packages/apps/reputation-oracle/server/src/modules/kyc/kyc.controller.ts, packages/apps/reputation-oracle/server/src/modules/kyc/kyc.error.ts, packages/apps/reputation-oracle/server/src/modules/kyc/kyc.repository.ts, packages/apps/reputation-oracle/server/src/modules/kyc/kyc.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/kyc/kyc.service.ts
Rework kyc.repository to use base repository.
Stop throwing http exceptions on a service level.
- Create a new error to be thrown in Kyc service.
- Replace all http exceptions with the new error.
- Rework DB to use baseRepository.
`yarn test`
#1894
=> [Reputation Oracle] Rework kyc module

packages/apps/reputation-oracle/server/src/common/dto/result.ts, packages/apps/reputation-oracle/server/src/modules/payout/payout.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/payout/payout.service.ts
Rework CVAT payouts calculation to avoid situations where 1 task can be paid twice.
- Modify objects to match:
`{
"jobs": [
{
"job_id": int,
"final_result_id": int,
}, ...
],
"results": [
{
"id": int,
"job_id": int,
"annotator_wallet_address": Address,
"annotation_quality": number,
}, ...
]
}`
- Replace the iteration over `results` with a loop over `jobs`
`yarn test`
#1901
=> [Reputation Oracle] Rework CVAT payouts

packages/apps/job-launcher/client/src/state/auth/reducer.ts, packages/apps/job-launcher/client/src/utils/api.ts
The change fixes the saving of the refresh token in the localstorage and when beckend response is 401, it sends a request that retrieves and saves the new access token 
Added a new interceptor to axios that creates a query queue if we got a 401. Sends a query for a new token with the current refresh token. Refreshes the query queue with the new access token
Make any request, wait 10 minutes for the access token to expire. Execute another request and check if everything works correctly, ie:
1. a request for a new access token has been executed
2. the requests that failed were executed again
3. we were not logged out of the application when we got a 401 error 
[#1845](https://github.com/humanprotocol/human-protocol/issues/1845)
=> Fix: Job-Launcher Ui- Refresh token

packages/apps/reputation-oracle/server/src/common/exceptions/reputation.filter.ts, packages/apps/reputation-oracle/server/src/modules/cron-job/cron-job.service.ts, packages/apps/reputation-oracle/server/src/modules/reputation/reputation.controller.ts, packages/apps/reputation-oracle/server/src/modules/reputation/reputation.error.ts, packages/apps/reputation-oracle/server/src/modules/reputation/reputation.repository.ts, packages/apps/reputation-oracle/server/src/modules/reputation/reputation.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/reputation/reputation.service.ts
Rework reputation.repository to use base repository.
Stop throwing http exceptions on a service level.
- Create a new error to be thrown in reputation service.
- Replace all http exceptions with the new error.
- Rework DB to use baseRepository.
`yarn test`
#1895
=> [Reputation Oracle] Rework reputation module

packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.dto.ts, packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.interface.ts, packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.repository.ts
Adding `assignment_id` to query param list to `/assignments` endpoint.
- Added new query param, and updated the assignment repository to support this filtering param.
Closes #1974
=> [Fortune Exchange Oracle] feat: Add assignment_id to query param

packages/core/contracts/governance/DAOSpokeContract.sol, packages/core/test/DAOSpokeContract.ts
-  There is a missing Access Control to `sendVoteResultToHub` on `DAOSpokeContract.sol `
- Modify the function `sendVoteResultToHub` for more security. 
Closes #1994
=> [Governance] Fix Missing Access Control 

packages/apps/job-launcher/server/src/app.module.ts, packages/apps/job-launcher/server/src/modules/cron-job/cron-job.module.ts, packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.ts, yarn.lock
Render allows to run cron jobs as background processes so we do not need the endpoints any more.
- Disable endpoints
- Add cron expression to cron job functions
- Remove the limitation of processing only 3 jobs per cron job execution
yarn test
=> [Job Launcher] Updates in cron jobs for render 

packages/apps/reputation-oracle/server/src/common/config/sendgrid-config.service.ts, packages/apps/reputation-oracle/server/src/common/constants/index.ts, packages/apps/reputation-oracle/server/src/modules/sendgrid/sendgrid.service.spec.ts
Modify from name used in Sendgrid templates
Update Sendgrid constants to show HUMAN App instead of Reputation Oracle
`yarn test`
#2010
=> [Reputation Oracle] Sendgrid app name

packages/apps/job-launcher/client/src/components/Auth/ValidateEmailForm.tsx, packages/apps/job-launcher/server/src/common/constants/index.ts, packages/apps/job-launcher/server/src/modules/auth/auth.service.ts, packages/apps/job-launcher/server/src/modules/auth/strategy/jwt.http.ts
Enhancement of the logout flow to ensure secure and efficient user session management.
- Implemented a check for LOGOUT_PATH to enable inactive users to logout securely.
- Introduced a refresh token check to prevent logged out users from accessing authorized routes.
**Case 1: Inactive user logout**
1. Sign Up as a user.
2. Attempt to logout as an inactive user.
Expected result:
Logout operation should be successful without triggering Unauthorized errors.
**Case 2: Restricted access after logout**
1. Sign Up as a user.
2. Activate the account.
3. Sign In.
4. Verify access to authorized routes (e.g., receive a 200 OK response).
5. Logout.
6. Attempt to access authorized routes again.
Expected result:
After logout, attempting to access authorized routes should result in a 401 Unauthorized …
=> [Job Launcher] Fixed login/logout

packages/apps/reputation-oracle/server/src/common/constants/index.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts, packages/apps/reputation-oracle/server/src/modules/auth/strategy/jwt.http.ts, render.yaml
Enhancement of the logout flow to ensure secure and efficient user session management.
- Implemented a check for LOGOUT_PATH to enable inactive users to logout securely.
- Introduced a refresh token check to prevent logged out users from accessing authorized routes.
**Case 1: Inactive user logout**
1. Sign Up as a user.
2. Attempt to logout as an inactive user.
Expected result:
Logout operation should be successful without triggering Unauthorized errors.
**Case 2: Restricted access after logout**
1. Sign Up as a user.
2. Activate the account.
3. Sign In.
4. Verify access to authorized routes (e.g., receive a 200 OK response).
5. Logout.
6. Attempt to access authorized routes again.
Expected result:
After logout, attempting to access authorized routes should result in a 401 Unauthorized …
=> [Reputation Oracle] Fixed login/logout

packages/apps/reputation-oracle/server/src/modules/credentials/credential.controller.ts, packages/apps/reputation-oracle/server/src/modules/credentials/credential.dto.ts, packages/apps/reputation-oracle/server/src/modules/credentials/credential.entity.ts, packages/apps/reputation-oracle/server/src/modules/credentials/credential.module.ts, packages/apps/reputation-oracle/server/src/modules/credentials/credential.repository.ts, packages/apps/reputation-oracle/server/src/modules/credentials/credential.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/credentials/credential.service.ts
- Implement `POST /credential/validate` endpoint for validating credentials linked to users.
- Added `ValidateCredentialDto`.
- Created `CredentialValidationEntity`.
- Updated `CredentialController` and `CredentialService`.
- Extended `CredentialRepository`.
- Added unit tests.
Closes [#2046](https://github.com/humanprotocol/human-protocol/issues/2046)
=> [Credentialing] Validate Endpoint 

packages/examples/cvat/exchange-oracle/src/crons/state_trackers.py, packages/examples/cvat/exchange-oracle/src/db/errors.py, packages/examples/cvat/exchange-oracle/src/handlers/completed_escrows.py, packages/examples/cvat/exchange-oracle/src/handlers/cvat_events.py, packages/examples/cvat/exchange-oracle/src/services/cvat.py, packages/examples/cvat/exchange-oracle/tests/integration/cron/state_trackers/test_track_completed_escrows.py
Problems:
1. In escrows with skeletons, it is possible that some projects are in the completed state, and some are in the validation state. During escrow completion checks, it wasn't checked that there's at least 1 completed project, so multiple validation requests could be sent successively, if the validation has not been completed between the escrow completion checks.
2. In escrows with skeletons, during escrow completion checks, it was possible to repeatedly fail on acquiring a locked project, aborting validation for other completed escrows in the batch.
3. In escrows with skeletons, during escrow completion, there were unnecessary calls to escrow validation
This PR fixes them by following:
- Escrow validation is now independent for each escrow in the batch, errors from 1 escrow should …
=> [CVAT] Fix escrow status checks

packages/apps/reputation-oracle/server/package.json, packages/apps/reputation-oracle/server/src/common/config/database-config.service.ts, packages/apps/reputation-oracle/server/src/database/database.module.ts, packages/apps/reputation-oracle/server/src/modules/cron-job/cron-job.module.ts, packages/apps/reputation-oracle/server/src/modules/cron-job/cron-job.service.ts, packages/apps/reputation-oracle/server/typeorm.config.ts, render.yaml
Fixes related to deployment of Reputation Oracle on Render
- Add POSTGRES_URL support to Reputation Oracle
- Disable cron job endpoints and set scheduler
- Fix start:prod script
- Add SENDGRID_API_KEY var to render.yaml
=> [Reputation Oracle] Fixes for Render deployment

scripts/Makefile, scripts/web3/.gitignore, scripts/web3/docker-compose.yml
To make it easier for other applications run on human protocol ecosystem locally, we need to prepare web3 components of human protocol.
- Added script to run local hardhat node, deploy contracts, and run subgraph node.
Run `make web3` inside `/scripts` folder, and make sure local hardhat node is running, contracts are deployed, subgraph node is up and running, and subgraphs are deployed properly.
=> feat: add scripts for web3 components only

packages/apps/reputation-oracle/server/src/common/constants/errors.ts, packages/apps/reputation-oracle/server/src/integrations/hcaptcha/hcaptcha.service.ts, packages/apps/reputation-oracle/server/src/modules/user/user.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/user/user.service.ts
Enhanced error handling in the registerLabeler function to prevent the erroneous return of HTTP 500 status codes.
- Refined error processing in the registerLabeler function.
- Added evm address check
- Added new error type NoWalletAddresRegistered
- Updated unit tests.
`yarn test`
[Reputation Oracle] Fix 500 error during register-labeler request
[#2113](https://github.com/humanprotocol/human-protocol/issues/2113)
=> [Reputation Oracle] Handle 500 error code correctly

packages/apps/job-launcher/client/src/components/Jobs/Create/CvatJobRequestForm.tsx
Make add labels when requesting a new CVAT job more intuitive. At this moment user needs to write the label and press intro but it is not intuitive and do not give any hint to the user
Add a message showing that you're going to add a new label
`yarn test`
#1433
=> [Job Launcher Client] - Make add labels for CVAT jobs intuitive

packages/apps/reputation-oracle/server/src/integrations/hcaptcha/hcaptcha.service.spec.ts, packages/apps/reputation-oracle/server/src/integrations/hcaptcha/hcaptcha.service.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.dto.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.module.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts, packages/apps/reputation-oracle/server/src/modules/cron-job/cron-job.module.ts
hCaptcha auth guard is enabled for some `/auth` endpoints
1. hCaptcha re-enabled for `/auth/signup`, `/auth/signin` and `/auth/restore-password`
2. hCaptcha added to `/auth/resend-email-verification` and `/auth/forgot-password`
3. Slightly changed the way of handling response for hCaptcha token verification and added a logline with a detailed error code.
4. Removed unused vars.
5. `/auth/forgot-password` endpoint now doesn't require user to be in `ACTIVE` status to avoid dead ends when user forgot password and also forgot to verify his email. In this case he won't be able to log in and ask for a new verification email.
**_Once merged, `HCAPTCHA_SECRET` and `HCAPTCHA_SITE_KEY` needs to be set_**
To close #2163
=> [Reputation Oracle] hCaptcha auth guard

packages/apps/fortune/exchange-oracle/server/src/common/decorators/role.ts, packages/apps/fortune/exchange-oracle/server/src/common/enums/role.ts, packages/apps/fortune/exchange-oracle/server/src/common/guards/jwt.auth.ts, packages/apps/fortune/exchange-oracle/server/src/common/guards/signature.auth.spec.ts, packages/apps/fortune/exchange-oracle/server/src/common/guards/signature.auth.ts, packages/apps/fortune/exchange-oracle/server/src/common/guards/strategy/jwt.http.ts, packages/apps/fortune/exchange-oracle/server/src/common/types/jwt.ts, packages/apps/fortune/exchange-oracle/server/src/modules/job/job.controller.ts, packages/apps/fortune/exchange-oracle/server/src/modules/webhook/webhook.controller.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts
Authorize HUMAN App to fetch jobs list using JWT generated by Reputation Oracle
Modify JWT strategy to substract role from JWT
Check roles in jwt auth
Add `human_app` to allowed roles in `getJobs` endpoint
`yarn test`
#2176
=> [Fortune Exchange Oracle] Add roles to JWT

packages/sdk/typescript/subgraph/src/mapping/legacy/Escrow.ts, packages/sdk/typescript/subgraph/src/mapping/legacy/EscrowFactory.ts, packages/sdk/typescript/subgraph/tests/legacy/escrow-factory/escrow-factory.test.ts, packages/sdk/typescript/subgraph/tests/legacy/escrow/escrow.test.ts
Remove EscrowStatusEvent from legacy escrow contracts
Remove EscrowStatusEvent from legacy escrow contracts
Fix tests
`yarn test`
#2195
=> [Subgraph] Remove EscrowStatusEvent from legacy contracts

packages/apps/reputation-oracle/server/src/modules/auth/token.repository.ts
JWT token generated in refresh token endpoint doesn't contain `site_key`
Add user sitekey to token relations
`yarn test`
#2208
=> [Reputation Oracle] Fix JWT site_key

packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts
Add status to jwt so that in the frontend of HUMAN APP is possible to know if the user verified his email.
Add status to jwt
yarn test
=> [Reputation Oracle] Add user status to jwt

packages/apps/reputation-oracle/server/src/common/constants/errors.ts, packages/apps/reputation-oracle/server/src/modules/kyc/kyc.controller.spec.ts, packages/apps/reputation-oracle/server/src/modules/kyc/kyc.controller.ts, packages/apps/reputation-oracle/server/src/modules/kyc/kyc.dto.ts, packages/apps/reputation-oracle/server/src/modules/kyc/kyc.module.ts, packages/apps/reputation-oracle/server/src/modules/user/user.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/user/user.service.ts
Create a new endpoint that returns the data that users need to save in kvstore to save their kyc verification on chain
Create a new endpoint in kyc.controller.ts that signs the address of the user
`yarn test`
#2226
=> [Reputation Oracle] Get kyc on chain endpoint

packages/apps/reputation-oracle/server/src/modules/kyc/kyc.dto.ts, packages/apps/reputation-oracle/server/src/modules/kyc/kyc.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/kyc/kyc.service.ts, packages/apps/reputation-oracle/server/src/modules/user/user.controller.ts, packages/apps/reputation-oracle/server/src/modules/user/user.dto.ts, packages/apps/reputation-oracle/server/src/modules/user/user.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/user/user.service.ts
Change returned value of user/register-address and fix kyc on chain endpoint in Reputation Oracle
Change returned value of user/register-address and fix kyc on chain endpoint in Reputation Oracle
#2242 #2243
=> [Reputation Oracle] Fix kyc on chain and change returned value of user/register-address

packages/apps/fortune/exchange-oracle/server/src/common/constant/errors.ts, packages/apps/fortune/exchange-oracle/server/src/common/enums/webhook.ts, packages/apps/fortune/exchange-oracle/server/src/database/migrations/1720453476309-AddEscrowCompletedEventTypeToWebhookTable.ts, packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.spec.ts, packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts, packages/apps/fortune/exchange-oracle/server/src/modules/webhook/webhook.controller.ts, packages/apps/fortune/exchange-oracle/server/src/modules/webhook/webhook.service.ts, packages/apps/reputation-oracle/server/src/modules/cron-job/cron-job.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/cron-job/cron-job.service.ts
Implemented completed webhook from Reputation Oracle to Exchange Oracle.
- Updated cron service in Reputation Oracle.
- Updated webhook service in Fortune.
- Added new event type in Fortune.
**Reputation Oracle:**
1. Create web hook entity with `PAID` status.
2. It will automatically be called `processPaidWebhooks`. 
**Fortune Exchange Oracle:** 
`POST /webhook`
```json
{
"chain_id": 80002,
"escrow_address": "test_escrow_address",
"event_type": "escrow_completed",
"event_data": {}
}
```
[Fortune Exchange Oracle | Reputation Oracle] Completed escrow webhook
[#2234](https://github.com/humanprotocol/human-protocol/issues/2234)
=> [Fortune Exchange Oracle | Reputation Oracle] Completed escrow webhook

packages/apps/fortune/exchange-oracle/server/src/modules/job/job.controller.spec.ts, packages/apps/fortune/exchange-oracle/server/src/modules/job/job.repository.ts, packages/apps/fortune/exchange-oracle/server/src/modules/stats/stats.dto.ts, packages/apps/fortune/exchange-oracle/server/src/modules/stats/stats.module.ts, packages/apps/fortune/exchange-oracle/server/src/modules/stats/stats.service.spec.ts, packages/apps/fortune/exchange-oracle/server/src/modules/stats/stats.service.ts
Extended stats.
Added the following properties to the response of /stats endpoint:
- completed_escrows
- active_escrows
- canceled_escrows
- workers_count*
* Was implemented before, and has the name: `workers_total`.
`yarn test`
`GET /stats`
[Fortune Exchange Oracle] Extend stats #2235
=> [Fortune Exchange Oracle] Extend stats

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/operator/__init__.py, packages/sdk/typescript/human-protocol-sdk/src/operator.ts
When using .getLeader() method and the address is not an oracle, This error is returned:
An error occurred while interacting with Ethereum: Cannot read properties of null (reading 'jobTypes')
return invalid address when the address is not an oracle
`yarn test` in Typescript
`make run-test` in Python
#2258
=> [SDK] Get leader error for non leader address

packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts, packages/sdk/typescript/human-protocol-sdk/src/index.ts
`TransactionUtils` cannot be imported
Add `TransactionUtils` to Typescript `index.ts`
#2273
=> [SDK] Fix TransactionUtils import

packages/apps/reputation-oracle/server/src/common/enums/index.ts, packages/apps/reputation-oracle/server/src/common/enums/site-key.ts, packages/apps/reputation-oracle/server/src/database/migrations/1721292675362-AddNewTypeAndRemoveUniqueKeyToSiteKey.ts, packages/apps/reputation-oracle/server/src/database/migrations/1721361395971-AddNewTypeAndUpdatedUniqueKeysToSiteKey.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts, packages/apps/reputation-oracle/server/src/modules/user/site-key.entity.ts, packages/apps/reputation-oracle/server/src/modules/user/site-key.repository.ts, packages/apps/reputation-oracle/server/src/modules/user/user.controller.ts, packages/apps/reputation-oracle/server/src/modules/user/user.dto.ts, packages/apps/reputation-oracle/server/src/modules/user/user.entity.ts, packages/apps/reputation-oracle/server/src/modules/user/user.repository.ts, packages/apps/reputation-oracle/server/src/modules/user/user.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/user/user.service.ts
Implemented registration.
**Description**
Create two new endpoints in Reputation oracle: 
- `POST user/registration`: save a registration process completed.
- `GET user/registration`: fetch the list of exchange oracles where the user completed a registration process.
**Implementation details** 
1. Created a new site key type: Registration
2. Removed uniqueness of site_key field from site_keys table 
3. `POST user/registration` : Implemented new endpoint. it create a new site key entity setting the oracle address as site_key value.
`Authorization: Bearer token`
Response 200:
```
{
"oracle_address": string(42)
}
```
4. `GET user/registration`: Implemented new endpoint. it return the list of registrations from site_keys table
`Authorization: Bearer token`
Response 200:
```
{ …
```
=> [Reputation Oracle] Implemented registration

packages/apps/dashboard/server/src/modules/details/dto/transaction.dto.ts
hash` is replaced with `txHash` in `TransactionPaginationDto`
hash` is replaced with `txHash` in `TransactionPaginationDto` to allow automapping due to the fact that SDK method `.getTransactions()` returns `txHash`
=> [Dashboard][Server] `hash` is replaced with `txHash` in `TransactionPaginationDto`

docs/sdk/python/human_protocol_sdk.transaction.transaction_utils.md, docs/sdk/typescript/base/classes/BaseEthersClient.md, docs/sdk/typescript/encryption/classes/Encryption.md, docs/sdk/typescript/encryption/classes/EncryptionUtils.md, docs/sdk/typescript/escrow/classes/EscrowClient.md, docs/sdk/typescript/escrow/classes/EscrowUtils.md, docs/sdk/typescript/kvstore/classes/KVStoreClient.md, docs/sdk/typescript/kvstore/classes/KVStoreUtils.md, docs/sdk/typescript/operator/classes/OperatorUtils.md, docs/sdk/typescript/staking/classes/StakingClient.md, docs/sdk/typescript/statistics/classes/StatisticsClient.md, docs/sdk/typescript/storage/classes/StorageClient.md, docs/sdk/typescript/transaction/classes/TransactionUtils.md, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/transaction/transaction_utils.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/transaction/test_transaction_utils.py, packages/sdk/typescript/human-protocol-sdk/package.json, packages/sdk/typescript/human-protocol-sdk/src/interfaces.ts, yarn.lock
`ITransaction` interface has an inaccuracy.
Instead of `hash` field, `.getTransactions()` returns `txHash`. Should be the same for all methods where return type is `ITransaction`. Same for python version.
Changed property name `hash` -> `txHash` for TS and Python SDK.
**Typescript:**
```typescript
const filter: ITransactionsFilter = {
chainId: ChainId.POLYGON,
startDate: new Date('2022-01-01'),
endDate: new Date('2022-12-31'),
first: 10,
skip: 0,
orderDirection: OrderDirection.DESC,
};
const transactions = await TransactionUtils.getTransactions(filter);
```
**Python:**
```python
from human_protocol_sdk.constants import ChainId
from human_protocol_sdk.transaction import TransactionUtils, TransactionFilter
print(
TransactionUtils.get_transactions(
TransactionFilter( …
```
=> [SDK] ITransaction interface wrong configuration

packages/apps/job-launcher/server/src/modules/job/job.dto.ts
Fixed swagger dto for `/job/cvat`.
Updated:
```
@ApiProperty({ type: [Label] })
@IsArray()
@ArrayMinSize(1)
public labels: Label[];
```
```
"labels": [
{
"name": "label1"
},
{
"name": "label2"
}
],
```
`POST /job/cvat`
[Job Launcher] Fix swagger dto for /job/cvat
[#2327](https://github.com/humanprotocol/human-protocol/issues/2327)
=> [Job Launcher] Fixed swagger dto for `/job/cvat`

packages/apps/dashboard/server/src/common/config/redis-config.service.ts, packages/apps/dashboard/server/src/modules/stats/dto/hmt-general-stats.dto.ts, packages/apps/dashboard/server/src/modules/stats/stats.controller.ts, packages/apps/dashboard/server/src/modules/stats/stats.service.ts, packages/apps/dashboard/server/src/modules/stats/utils/constants.ts
Added `/stats/general` endpoint for retrieving HMT general stats
1. Added `/stats/general` endpoint for retrieving HMT general stats
2. Added cron job which will run every 15 minutes to update stats
=> [Dashboard][Server] Added `/stats/general` endpoint for retrieving HMT general stats

packages/apps/human-app/frontend/.env.example, packages/apps/human-app/frontend/README.md, packages/apps/human-app/frontend/package.json, packages/apps/human-app/frontend/src/shared/env.ts, packages/apps/human-app/frontend/src/smart-contracts/contracts.ts, yarn.lock
Removed `.env` variables and read from sdk.
Removed these env variables:
```
VITE_TESTNET_AMOY_STAKING_CONTRACT
VITE_TESTNET_AMOY_HMTOKEN_CONTRACT
VITE_TESTNET_AMOY_ETH_KV_STORE_CONTRACT
VITE_MAINNET_POLYGON_STAKING_CONTRACT
VITE_MAINNET_POLYGON_HMTOKEN_CONTRACT
VITE_MAINNET_POLYGON_ETH_KV_STORE_CONTRACT
```
[HUMAN APP] Read contract addresses from sdk
[#2334](https://github.com/humanprotocol/human-protocol/issues/2334)
=> [HUMAN App] Import contract addresses from sdk

packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.ts
Some escrows have PARTIAL status in database while in the blockcahin the status is CANCELED. 
This error might happen bacause the subgraph has not indexed it yet so the status is still PARTIAL in subgraph when the update status cron job is run.
Add a condition to don't update CANCELED jobs
=> do not change status of canceled escrows

packages/apps/human-app/frontend/vite.config.mjs
Fixed `yarn build`.
```
error during build:
src/smart-contracts/contracts.ts (4:18): "NETWORKS" is not exported by "../../../sdk/typescript/human-protocol-sdk/dist/index.js", imported by "src/smart-contracts/contracts.ts".
```
Updated vite config:
```
optimizeDeps: {
include: ['@human-protocol/sdk'],
},
build: {
target: 'esnext',
commonjsOptions: {
include: [/human-protocol-sdk/, /node_modules/],
},
},
```
`yarn install` 
`yarn build`
[Human App] Fix yarn build
[#2374](https://github.com/humanprotocol/human-protocol/issues/2374)
[HUMAN App] Import contract addresses from sdk #2339
=> [Human App] Fixed `yarn build`

packages/apps/human-app/frontend/src/api/services/operator/get-stats.ts, packages/apps/human-app/frontend/src/pages/operator/profile/profile.page.tsx
Show response values for escrow stats in operator profile.
Before a `-` was shown.
- Show response in profile page
yarn test
=> [HUMAN App] Show escrow stats in operator profile

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/kvstore/kvstore_utils.py, packages/sdk/typescript/human-protocol-sdk/src/kvstore.ts, packages/sdk/typescript/human-protocol-sdk/test/kvstore.test.ts
Fix KvstoreUtils.get for compatibility with old versions.
Return an empty string instead of an exception in case the key is not found
`yarn test`
=> [SDK] Fix KvstoreUtils.get for compatibility with old versions

packages/apps/reputation-oracle/server/src/common/constants/errors.ts, packages/apps/reputation-oracle/server/src/modules/qualification/qualification.controller.spec.ts, packages/apps/reputation-oracle/server/src/modules/qualification/qualification.repository.ts, packages/apps/reputation-oracle/server/src/modules/qualification/qualification.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/qualification/qualification.service.ts
Fixed nullable `expiresAt` bugs
`yarn test`
[Reputation Oracle] Qualifications bugs
[#2361](https://github.com/humanprotocol/human-protocol/issues/2361)
=> [Reputation Oracle] Fixed nullable `expiresAt` bugs

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/constants.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/operator.py, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/operator/operator_utils.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/operator/test_operator_utils.py, packages/sdk/typescript/human-protocol-sdk/src/constants.ts, packages/sdk/typescript/human-protocol-sdk/src/graphql/queries/operator.ts, packages/sdk/typescript/human-protocol-sdk/src/interfaces.ts, packages/sdk/typescript/human-protocol-sdk/test/operator.test.ts, packages/sdk/typescript/subgraph/schema.graphql, packages/sdk/typescript/subgraph/src/mapping/KVStore.ts, packages/sdk/typescript/subgraph/tests/kvstore/kvstore.test.ts
Add information about registration in exchange oracle/annotation tool to the leader entity
1. Add two new properties to the entity:
- registrationNeeded: boolean based on value of the kvstore for the key registration_needed
- registrationInstructions: value of the kvstore for the key registration_instructions
2. Update SDK get leaders and get reputation network
`yarn test` in Typescript
`make run-test` in python
#2410
=> [Subgraph][SDK] Add registration data to leaders entity

packages/core/contracts/Escrow.sol, packages/core/test/Escrow.ts, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/statistics.py, packages/sdk/typescript/human-protocol-sdk/src/graphql/queries/statistics.ts, packages/sdk/typescript/human-protocol-sdk/src/graphql/types.ts, packages/sdk/typescript/subgraph/schema.graphql, packages/sdk/typescript/subgraph/src/mapping/Escrow.ts, packages/sdk/typescript/subgraph/src/mapping/legacy/Escrow.ts, packages/sdk/typescript/subgraph/src/mapping/utils/dayUpdates.ts, packages/sdk/typescript/subgraph/template.yaml, packages/sdk/typescript/subgraph/tests/escrow/escrow.test.ts, packages/sdk/typescript/subgraph/tests/escrow/fixtures.ts, packages/sdk/typescript/subgraph/tests/hmt/hmt.test.ts, packages/sdk/typescript/subgraph/tests/legacy/escrow/escrow.test.ts
Add events for data being read with eth_calls in subgraph
Add data read from eth_call in subgraph to contract events
Read new contract events
`yarn test`
#2382
=> [Subgraph] Remove eth_calls

packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.spec.ts, packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts
Allow canceling failed jobs
- Implemented `isEscrowFunded` in Job Service.
- Implemented checks in `cancelCronJob`.
- Updated unit tests.
**Tested Scenarios:**
- **Job PAID**: Job fails after being paid without an escrowAddress, with a zero escrow balance. Funds are returned to the user.
- **Job CREATED**: Job fails after being created with an escrowAddress. The escrow balance is zero, and funds are returned to the user.
- **Job SETUP**: Job fails after setup with an escrowAddress, but the escrow is not funded yet (balance is zero), and funds are returned to the user.
- **Job LAUNCHED**: Job fails after being launched with an escrowAddress. The escrow balance is non-zero, the escrow is canceled, and funds are returned to the user.
Major changes was implemented in `cancelCronJob`, because …
=> [Job Launcher] Allowed canceling failed jobs

packages/apps/reputation-oracle/server/src/modules/reputation/reputation.repository.ts, packages/apps/reputation-oracle/server/src/modules/reputation/reputation.service.ts
Fixed get reputation endpoint with lowercase address
- Added a checksum check to the incoming address, assuming that the address is stored in the database as a checksum.
⚠️ The address gets into the database during the reputation init, and it is not validated there, should we store the address as a checksum or in lowercase? Considering that we store addresses in lowercase in KVStore, this should be fixed here too.
```bash
curl -X 'GET' \
'http://localhost:5001/reputation/0x54f964b34852695c4896e4f065630034ea9e35b5?chain_id=80002' \
-H 'accept: application/json'
```
[Reputation Oracle] Get reputation endpoint with lowercase address - "Reputation not found"
[#2470](https://github.com/humanprotocol/human-protocol/issues/2470)
=> [Reputation Oracle] Fixed get reputation endpoint with lowercase address

packages/apps/human-app/frontend/src/api/services/worker/hcaptcha-user-stats.ts, packages/apps/human-app/frontend/src/pages/worker/hcaptcha-labeling/hcaptcha-labeling/hcaptcha-labeling.page.tsx, packages/apps/human-app/server/src/integrations/h-captcha-labeling/h-captcha-statistics.gateway.ts, packages/apps/human-app/server/src/modules/h-captcha/model/user-stats.model.ts, packages/apps/human-app/server/src/modules/h-captcha/spec/h-captcha.fixtures.ts
Fixed incorrect way of handling hcaptcha daily user stats
Process `dropoff_data` and `earnings_data` as objects not arrays.
Also, use today's stats for comparing with `VITE_DAILY_SOLVED_CAPTCHA_LIMIT`
=> [Human APP][Server][Client] Fixed incorrect way of handling hcaptcha daily user stats

packages/examples/cvat/exchange-oracle/src/endpoints/exchange.py, packages/examples/cvat/exchange-oracle/src/services/cvat.py, packages/examples/cvat/exchange-oracle/src/services/exchange.py, packages/examples/cvat/exchange-oracle/tests/integration/services/test_cvat.py, packages/examples/cvat/exchange-oracle/tests/integration/services/test_exchange.py
> In the current implementation a job can be annotated by the same worker multiple times. It is especially bad, because it could be siently rejected previously and now the worker has to annotate the job one more time.
> Delivery: A job can be annotated by an annotator only once. If it is rejected, it should not be visible again by the same annotator.
- Updated the `create_assignment` endpoint to check for existing assignments for a given `wallet_address` and return a relevant message if none are available.
- Modified `get_free_job` to exclude jobs already assigned to the specified `wallet_address`.
- Run integration tests in `test_cvat.py` and `test_exchange.py` to validate new behavior.
- Manually test the `create_assignment` endpoint by attempting to assign jobs to the same wallet …
=> [CVAT][Exchange Oracle] Avoid reassigning a job to the same wallet address

packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts
Fixed sign up as operator with Job Launcher role
- Converted the role to lowercase.
Follow sing up process in human app using role Job Launcher
[Reputation Oracle] Cannot sign up as operator with Job Launcher role
[#2492](https://github.com/humanprotocol/human-protocol/issues/2492)
=> [Reputation Oracle] Fixed sign up as operator with Job Launcher role

packages/apps/fortune/exchange-oracle/server/src/common/constant/errors.ts, packages/apps/fortune/exchange-oracle/server/src/common/guards/strategy/jwt.http.ts, packages/apps/fortune/exchange-oracle/server/src/common/types/jwt.ts, packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.service.spec.ts, packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.service.ts, packages/apps/fortune/exchange-oracle/server/src/modules/job/job.dto.ts
Update Exchange Oracle to check users qualifications against the qualifications required for a job when the user attempts to assign themselves to a job
Read user's qualifications from JWT
Read job's qualifications from manifest
Compare the user’s qualifications against the job’s requirements
`yarn test`
#2467
=> [Exchange Oracle] Check qualifications on job assignment

packages/apps/human-app/server/src/integrations/h-captcha-labeling/h-captcha-statistics.gateway.ts
Fix the following issue
currentDateStats or currentEarningsStats are undefined
=> fix when currentDateStats is undefined

packages/apps/job-launcher/client/src/components/Jobs/Create/CvatJobRequestForm.tsx, packages/apps/job-launcher/client/src/components/Jobs/Create/FortuneJobRequestForm.tsx, packages/apps/job-launcher/client/src/components/Jobs/Create/HCaptchaJobRequestForm.tsx, packages/apps/job-launcher/client/src/components/Jobs/Create/schema.ts, packages/apps/job-launcher/client/src/services/job.ts, packages/apps/job-launcher/client/src/services/qualification.ts, packages/apps/job-launcher/client/src/types/index.ts
Include Qualifications in Job Creation
- Fetch the available qualifications from the get qualifications endpoint.
- Add a dropdown menu to the job creation page under the section for qualifications.
- Display the fetched qualifications in a multiselect input, allowing users to select zero, one or more.
- Add the selected qualifications to the job creation request sent to the server.
#2466
=> Add qualifications in Job Launcher Frontend

packages/apps/fortune/exchange-oracle/server/src/common/enums/job.ts, packages/apps/fortune/exchange-oracle/server/src/modules/job/job.dto.ts, packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts, packages/apps/human-app/server/src/common/constants/cache.ts, packages/apps/human-app/server/src/common/enums/global-common.ts, packages/apps/human-app/server/src/common/utils/jwt-token.model.ts, packages/apps/human-app/server/src/modules/cron-job/cron-job.service.ts, packages/apps/human-app/server/src/modules/jobs-discovery/jobs-discovery.controller.ts, packages/apps/human-app/server/src/modules/jobs-discovery/jobs-discovery.service.ts, packages/apps/human-app/server/src/modules/jobs-discovery/model/jobs-discovery.model.ts
Update Human App to filter jobs based on the user’s qualifications. The app receives all jobs from the Exchange Oracle without filtering, so it needs to filter out jobs that the user is not qualified to handle based on their qualifications
Add qualifications filter to Human App getAvailableJobs
Fix extra fields in getAvailableJobs endpoint
`yarn test`
#2469
=> [Human App] Jobs qualifications filter

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/kvstore/kvstore_utils.py, packages/sdk/typescript/human-protocol-sdk/src/kvstore.ts
Issues in hash comparison
Update python and typescript SDKs to remove 0x
`make run-test`
`yarn test`
=> [SDK] Remove 0x from hash comparison

packages/apps/human-app/frontend/src/components/layout/drawer-menu-items/drawer-menu-items-worker.tsx, packages/apps/human-app/frontend/src/router/router-paths.ts, packages/apps/human-app/frontend/src/router/routes.tsx, packages/apps/human-app/frontend/src/shared/env.ts, packages/apps/human-app/server/src/common/config/environment-config.service.ts, packages/apps/human-app/server/src/modules/cron-job/cron-job.service.ts, packages/apps/human-app/server/src/modules/cron-job/spec/cron-job.service.spec.ts, packages/apps/human-app/server/src/modules/jobs-discovery/jobs-discovery.controller.ts, packages/apps/human-app/server/src/modules/jobs-discovery/spec/jobs-discovery.controller.spec.ts, packages/apps/human-app/server/src/modules/oracle-discovery/oracle-discovery.controller.ts, packages/apps/human-app/server/src/modules/oracle-discovery/spec/oracle-discovery.controller.spec.ts
Implement a feature flag for "Jobs Discovery" mechanism
Frontend:
Add FEATURE_FLAG_JOBS_DISCOVERY env variable.
If this env is set to false, don't show Jobs Discovery tab and it's content (just in case someone will try to directly go to /worker/jobs-discovery
Backend:
Add FEATURE_FLAG_JOBS_DISCOVERY env variable.
In case this variable is set to false, all mechanisms related to this feature should be disabled (cron-jobs, endpoints for calling exchnage oracles etc.)
#2532
=> [Human APP][Server / Client] Implement a feature flag for "Jobs Discovery" mechanism

packages/apps/fortune/exchange-oracle/server/tsconfig.build.json, packages/apps/fortune/recording-oracle/tsconfig.build.json, packages/apps/human-app/server/tsconfig.build.json, packages/apps/job-launcher/server/tsconfig.build.json, packages/apps/reputation-oracle/server/tsconfig.build.json
Excluded scripts folder from build
`yarn build`
Excluded scripts folder from build
[#2538](https://github.com/humanprotocol/human-protocol/issues/2538)
=> Excluded scripts folder from build

packages/apps/job-launcher/client/src/components/Jobs/Create/CvatJobRequestForm.tsx, packages/apps/job-launcher/server/src/modules/job/job.service.ts
Show a better message for ground truth errors
Frontend:
- Improve hint
Backend:
- Add a meaninful error when the path provided is wrong.
`yarn test
#2513
=> [Job Launcher] Dataset and ground truth path validation and hint

packages/apps/fortune/recording-oracle/src/common/enums/webhook.ts, packages/apps/fortune/recording-oracle/src/modules/job/job.service.spec.ts, packages/apps/fortune/recording-oracle/src/modules/job/job.service.ts, packages/apps/fortune/recording-oracle/src/modules/webhook/webhook.controller.spec.ts, packages/apps/fortune/recording-oracle/src/modules/webhook/webhook.service.spec.ts, packages/apps/reputation-oracle/server/src/common/enums/webhook.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
Change event type `task_completed` to `job_completed`
Rename `task_completed` to `job_completed`
`yarn test`
#2560 #2561
=> [Reputation Oracle][Recording Oracle] Change event type task_completed to job_completed

packages/examples/cvat/exchange-oracle/src/chain/kvstore.py, packages/examples/cvat/exchange-oracle/tests/integration/chain/test_kvstore.py
Added in #2428, `get_reputation_oracle_url` was mistakenly returning url for recording oracle. 
This PR fixes it and adds previously missing tests.
=> [CVAT][Exchange Oracle] Return correct url from `get_reputation_oracle_url`

packages/apps/human-app/frontend/vercel.json
Vercel  doesn't have server-side routing configured when `window.location.reload()` is called, resulting in a 404.
Add vercel.json to handle it.
Check vercel preview
=> Add vercel config file to allow window.location.reload()

packages/apps/fortune/exchange-oracle/server/src/modules/assignment/assignment.service.ts, packages/apps/human-app/server/src/modules/jobs-discovery/jobs-discovery.service.ts
Allow a user that canceled an assignment be able to get the assignation again
Allow reassignation only when status is `Canceled`
- Create a new assignation
- Cancel it
- Try to assign it again
#2559
=> [Fortune Exchange Oracle] Allow reassignation

packages/apps/job-launcher/server/src/common/constants/errors.ts, packages/apps/job-launcher/server/src/modules/encryption/encryption.module.ts
Nullable value cannot be used as private key
Handle error of possible private key empty when encryption is enabled
=> fix build error in job launcher server

packages/apps/job-launcher/client/src/components/Jobs/Create/CvatJobRequestForm.tsx, packages/apps/job-launcher/client/src/components/Jobs/Create/FortuneJobRequestForm.tsx, packages/apps/job-launcher/client/src/components/Jobs/Create/HCaptchaJobRequestForm.tsx, packages/apps/job-launcher/client/src/services/qualification.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts, packages/apps/job-launcher/server/src/modules/qualification/qualification.controller.spec.ts, packages/apps/job-launcher/server/src/modules/qualification/qualification.controller.ts, packages/apps/job-launcher/server/src/modules/qualification/qualification.dto.ts, packages/apps/job-launcher/server/src/modules/qualification/qualification.service.spec.ts, packages/apps/job-launcher/server/src/modules/qualification/qualification.service.ts
Get the qualifications using the chain id selected to create the escrow.
The endpoint in frontend should be loaded after selecting the network.
Added chainId to getQualifications methods
Modify frontend to load values after selecting the network
Try to create a new job. Qualifications should be loaded after selecting the network
#2593
=> [Job Launcher] Get qualifications issue

packages/apps/job-launcher/server/src/modules/qualification/qualification.module.ts
Add Web3Module to QualificationsModule to inject it properly
=> [Job Launcher] Qualification dependency

.github/PULL_REQUEST_TEMPLATE.md
=> [General] Updated PR template

.husky/pre-commit, package.json, packages/apps/human-app/server/.eslintrc.js, packages/apps/human-app/server/.gitignore, packages/apps/human-app/server/src/app.module.ts, packages/apps/human-app/server/src/common/config/environment-config.service.ts, packages/apps/human-app/server/src/common/config/params-decorators.ts, packages/apps/human-app/server/src/common/middleware/host-check.middleware.ts, packages/apps/human-app/server/src/common/utils/gateway-common.utils.ts, packages/apps/human-app/server/src/integrations/exchange-oracle/exchange-oracle.gateway.ts, packages/apps/human-app/server/src/modules/job-assignment/job-assignment.service.ts, packages/apps/human-app/server/src/modules/job-assignment/spec/job-assignment.fixtures.ts, packages/apps/human-app/server/src/modules/job-assignment/spec/job-assignment.service.spec.ts, packages/apps/human-app/server/src/modules/jobs-discovery/spec/jobs-discovery.controller.spec.ts, packages/apps/human-app/server/src/modules/oracle-discovery/spec/oracle-discovery.controller.spec.ts, packages/apps/human-app/server/src/modules/user-worker/spec/worker.service.spec.ts
Changing the way we store user's job assignments in Redis in order to avoid bloating the cached data up to the limits.
1. Use new format of key, including oracle address as well. This will help us to reduce the amount of stored data per item easily w/ no extra effort. Access pattern for "My Jobs" now always includes oracle address, so no extra manipulation needed.
2. Added retention policy for stored job assignments data
- when updating assignments cache we filter out "expired" assignments and fetch updates from oracle according to retention policy
- when fetching assignments for the first time (when cache is empty) instead of fetching everything we will fetch only "recent" assignments according to retention policy; it should ease cases when cache is invalidated
- retention policy is …
=> [Human App] Change the way assignments stored in Redis

packages/apps/human-app/server/src/modules/cron-job/spec/cron-job.service.spec.ts, packages/apps/human-app/server/src/modules/jobs-discovery/spec/jobs-discovery.controller.spec.ts, packages/apps/human-app/server/src/modules/oracle-discovery/oracle-discovery.controller.ts, packages/apps/human-app/server/src/modules/oracle-discovery/spec/oracle-discovery.controller.spec.ts
Uncomment tests. These tests were commented because the endpoints were disabled. Now it is enable again
- Uncomment `src/modules/jobs-discovery/spec/jobs-discovery.controller.spec.ts``
- Specify jobsDiscoveryFlag to false to disable asyncronous jobs running in tests
`yarn test`
#2609
=> [Human App] Enable JobDiscovery tests

packages/apps/reputation-oracle/server/src/modules/kyc/kyc.service.ts
Verification message updates with every decision sent from Veriff
Previously we didn't change a message with every webhook sent from Veriff so we could have an `approved` status but with message like `Document type is not supported` due to the resubmission.
To close #2599
=> [Reputation Oracle] Verification message updates with every decision

packages/core/package.json, yarn.lock
Reverts humanprotocol/human-protocol#2605
It was causing errors in core contracts build
=> Revert "Bump solidity-coverage from 0.8.12 to 0.8.13"

packages/apps/job-launcher/client/src/pages/Job/JobDetail/index.tsx, packages/apps/job-launcher/server/src/modules/job/job.service.ts
Empty fields while showing manifest details.
Also, Fortune's request should be a thing for CVAT jobs.
Fix empty description for CVAT jobs and change `Fortune's request` to `Task size` for non-fortune jobs
#2643
=> [Job Launcher][Client] Empty fields in escrow details.

packages/apps/fortune/exchange-oracle/client/src/constants/chains.ts, packages/apps/fortune/exchange-oracle/client/src/providers/WagmiProvider.tsx, packages/apps/job-launcher/client/src/constants/chains.ts, packages/apps/job-launcher/client/src/providers/WagmiProvider.tsx
Remove RPC endpoints from frontend apps
Remove RPC_URLS from frontends
Introduce a new env variable to define the supported chainIds
Check if frontend still working without them
#2591
=> Remove RPC endpoints from frontends

packages/examples/cvat/exchange-oracle/alembic.ini, packages/examples/cvat/exchange-oracle/poetry.lock, packages/examples/cvat/exchange-oracle/pyproject.toml, packages/examples/cvat/exchange-oracle/src/models/cvat.py, packages/examples/cvat/exchange-oracle/src/services/cvat.py, packages/examples/cvat/recording-oracle/alembic.ini, packages/examples/cvat/recording-oracle/poetry.lock, packages/examples/cvat/recording-oracle/pyproject.toml
- Updated FastAPI to 0.115.4
- Updated Starlette to above 0.40.0 (fixes DoS via multipart/form-data, https://github.com/advisories/GHSA-f96h-pmfr-66vw)
- Fixed a warning related to invalid db query setup in Exchange Oracle
- Fixed some warnings in the oracle db models
- Fixed an error in db migration generation due to missing postprocessing hook
=> [CVAT] Update deps, fix warnings

packages/apps/human-app/frontend/src/components/layout/protected/drawer-navigation.tsx, packages/apps/human-app/frontend/src/components/layout/protected/navbar.tsx, packages/apps/human-app/frontend/src/components/layout/unprotected/navbar.tsx, packages/apps/human-app/frontend/src/hooks/use-handle-main-nav-icon-click.tsx, packages/apps/human-app/frontend/src/pages/worker/jobs/components/available-jobs/mobile/available-jobs-drawer-mobile.tsx, packages/apps/human-app/frontend/src/pages/worker/jobs/components/my-jobs/mobile/my-jobs-drawer-mobile.tsx
=> Hum 39 click on human app logo should redirect to default page

packages/examples/cvat/exchange-oracle/src/endpoints/authentication.py, packages/examples/cvat/exchange-oracle/tests/api/test_exchange_api.py
`HUMAN_APP` role converted to `human_app`
`HUMAN_APP` role converted to `human_app` to align with changes made in #2610 (https://github.com/humanprotocol/human-protocol/commit/3a6609700373a0157dd0951748281a97df54bb8a#diff-5586d140ecda9fde38cc44918da5e27208e90c6c468162a555e9b0d78387d68eR10)
=> [CVAT][Exchange Oracle] `HUMAN_APP` role converted to `human_app`

packages/examples/cvat/exchange-oracle/src/schemas/exchange.py, packages/examples/cvat/exchange-oracle/tests/api/test_exchange_api.py
hmt abbreviation switched back to upper case
=> [CVAT][Exchange Oracle] fix: hmt abbreviation switched back to upper case

packages/apps/human-app/server/package.json, packages/apps/human-app/server/src/common/config/cache-factory.config.ts, packages/apps/human-app/server/src/common/config/environment-config.service.ts, packages/apps/human-app/server/src/integrations/kv-store/kv-store.gateway.ts, packages/apps/human-app/server/src/integrations/kv-store/spec/kv-store.gateway.spec.ts, packages/apps/human-app/server/src/modules/h-captcha/h-captcha.service.ts, packages/apps/human-app/server/src/modules/h-captcha/spec/h-captcha.service.spec.ts, packages/apps/human-app/server/src/modules/health/health.controller.spec.ts, packages/apps/human-app/server/src/modules/health/health.controller.ts, packages/apps/human-app/server/src/modules/health/health.module.ts, packages/apps/human-app/server/src/modules/health/indicators/cache-manager.health.spec.ts, packages/apps/human-app/server/src/modules/health/indicators/cache-manager.health.ts, packages/apps/human-app/server/src/modules/job-assignment/job-assignment.service.ts, packages/apps/human-app/server/src/modules/job-assignment/spec/job-assignment.service.spec.ts, packages/apps/human-app/server/src/modules/statistics/spec/statistics.service.spec.ts, packages/apps/human-app/server/src/modules/statistics/statistics.service.ts, yarn.lock
Fixing invalid usage of cache-manager `ttl` value.
We use `@nestjs/cache-manager@2.2.1` that under the hood just creates instance of `cache-manager` package ([ref](https://github.com/nestjs/cache-manager/blob/2.2.1/lib/cache.providers.ts#L29-L51)) that is being installed in the project (5.4.0 in our case). When we import `Cache` type for it - we see that `ttl` is just a third argument and is in milliseconds. Under the hood `cache-manager` calls the `set` method of the store ([ref](https://github.com/jaredwray/cacheable/blob/5.1.4/src/caching.ts#L89)) in the same fashion. However, when we register cache module, we create a redis store based on `cache-manager-redis-store`, that accepts ttl in `options` argument ([ref](https://github.com/dabroek/node-cache-manager-redis-store/blob/v3.0.1/inde …
=> [Human App] fix: cache-manager ttl usage

packages/examples/cvat/exchange-oracle/alembic/versions/1728488727_use_uuid_type_for_primar_keys_284adb30d75e.py, packages/examples/cvat/exchange-oracle/alembic/versions/1728488727_use_uuid_type_for_primary_keys_284adb30d75e.py, packages/examples/cvat/exchange-oracle/alembic/versions/1728562245_add_default_for_uuid_primary_keys_4fc740e8c6ff.py, packages/examples/cvat/exchange-oracle/src/db/__init__.py, packages/examples/cvat/exchange-oracle/src/models/cvat.py, packages/examples/cvat/exchange-oracle/src/models/webhook.py, packages/examples/cvat/exchange-oracle/tests/api/test_exchange_api.py, packages/examples/cvat/exchange-oracle/tests/integration/cron/test_process_recording_oracle_webhooks.py, packages/examples/cvat/exchange-oracle/tests/integration/services/test_cvat.py
Currently varchar is used for primary keys. This is very ineficient and prone to errors as well (nothing is stopping the database from accumulating records with primary keys that are invalid UUIDs, making it much harder to adopt these changes in the future).
It make sense to fix this before actual launch to prevent problems in the future.
Reference: https://stackoverflow.com/questions/32189129/performance-difference-between-uuid-char-and-varchar-in-postgresql-table
=> [CVAT][Exchange Oracle] Use UUID type in postgres

packages/apps/human-app/frontend/src/api/services/worker/oracles.ts, packages/apps/human-app/frontend/src/components/layout/drawer-menu-items/drawer-menu-items-worker.tsx, packages/apps/human-app/frontend/src/router/routes.tsx
The issue was generated when hcaptcha was moved into oracles discovery tab.
Since this change VITE_FEATURE_FLAG_JOBS_DISCOVERY is false, tasks tab is not visible.
Tasks menu option will now always be visible and oracles other than hcaptcha will only be shown in case VITE_FEATURE_FLAG_JOBS_DISCOVERY is true
Deployed on render as a hot fix
None
None
=> [HUMAN App client] Fix oracles discovery tab

packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts, packages/apps/fortune/exchange-oracle/server/src/modules/storage/storage.service.ts, packages/apps/fortune/recording-oracle/src/modules/storage/storage.service.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts, packages/apps/job-launcher/server/src/modules/storage/storage.service.ts, packages/apps/reputation-oracle/server/src/modules/storage/storage.service.ts, packages/sdk/typescript/human-protocol-sdk/example/encrypt.ts, packages/sdk/typescript/human-protocol-sdk/src/encryption.ts, packages/sdk/typescript/human-protocol-sdk/test/encryption.test.ts, packages/sdk/typescript/human-protocol-sdk/test/utils/constants.ts
Encryption module now works with binaries
1. Both `signAndEncrypt` and `sign` methods now accept not only `string`, but also `Uint8Array` (or `Buffer`, which is subclass of it), so we can properly works with some small files. In case we need something relatively big (e.g. >10Mb) - we will probably need to start supporting streams. We can see how it goes with performance over time
2. `decrypt` method now always returns `Uint8Array`, so consumer of this API must know what to expect and how to process decrypted value
Part of the https://github.com/humanprotocol/human-protocol/issues/2717
=> [SDK][Typescript] feat!: encryption module now works with binaries

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/encryption/encryption.py, packages/sdk/python/human-protocol-sdk/test/human_protocol_sdk/encryption/test_encryption.py
Encryption module now can work not only with strings
1. Both `sign_and_encrypt` and `sign` methods now can work both with `str` and `bytes` types.
2. `decrypt` method now returns `bytes` instead of `str`
Part of the #2717
**_NOTE:_** Don't merge this PR.
=> [SDK][Python] fix: encryption module now can work not only with strings

packages/apps/faucet/client/package.json, packages/apps/fortune/exchange-oracle/client/package.json, packages/apps/job-launcher/client/package.json, yarn.lock
Serve removed in old dashboard #2757
Install again `serve` in faucet, Job Launcher Client and Exchange Oracle Client
None
Deploy the services again
None
=> [Job Launcher Client] Install serve

packages/examples/cvat/exchange-oracle/src/services/cvat.py, packages/examples/cvat/exchange-oracle/tests/integration/cron/state_trackers/test_track_completed_escrows.py
Use correct function to count all of the projects in completed status. Previously count() was used that just counted all records, however the logic requires use of sum() to ignore cases that evaluate to 0.
Fixed previously non-working test case.
=> [CVAT][Exchange Oracle] Fix handling of projects in validation status

packages/apps/human-app/server/src/common/config/environment-config.service.spec.ts, packages/apps/human-app/server/src/common/config/environment-config.service.ts, packages/apps/human-app/server/src/integrations/kv-store/kv-store.gateway.ts, packages/apps/human-app/server/src/modules/cron-job/cron-job.service.ts, packages/apps/human-app/server/src/modules/cron-job/spec/cron-job.service.spec.ts, packages/apps/human-app/server/src/modules/jobs-discovery/spec/jobs-discovery.controller.spec.ts, packages/apps/human-app/server/src/modules/oracle-discovery/model/oracle-discovery.model.ts, packages/apps/human-app/server/src/modules/oracle-discovery/oracle-discovery.service.ts, packages/apps/human-app/server/src/modules/oracle-discovery/spec/oracle-discovery.controller.spec.ts, packages/apps/human-app/server/src/modules/oracle-discovery/spec/oracle-discovery.fixture.ts, packages/apps/human-app/server/src/modules/oracle-discovery/spec/oracle-discovery.service.spec.ts
[Human App] Convert all chainIds values ​​to type ChainId
[#2725](https://github.com/humanprotocol/human-protocol/issues/2725)
This update aims to improve type safety by changing `chainId` values from `string` to a `ChainId` type. Key updates include modifying the `chainIdsEnabled` method in `environment-config.service.ts` to return `ChainId[]` and updating functions in `KvStoreGateway` to accept a `ChainId` type.
The changes were tested as follows:
1. Updated unit tests to validate the correct type and usage of `ChainId` in affected methods.
2. Verified app functionality in key areas relying on chain ID logic, particularly focusing on `environment-config.service.ts` and `KvStoreGateway`.
3. Conducted unit tests.
If issues arise, revert the `ChainId` type casting changes and roll back to …
=> [Human App] Converted all chainIds values ​​to type ChainId

packages/apps/dashboard/server/package.json, packages/apps/dashboard/server/src/app.module.ts, packages/apps/dashboard/server/src/common/config/cache-factory.config.ts, packages/apps/dashboard/server/src/common/config/redis-config.service.ts, packages/apps/dashboard/server/src/modules/stats/stats.service.ts, packages/apps/dashboard/server/tsconfig.json, yarn.lock
Same as https://github.com/humanprotocol/human-protocol/pull/2742
- refactored to use `cache-manager-redis-yet` for dashboard
- added schema validation for some numeric env vars, so we don't have to cast them in the code
- added `esModuleInterop` option to TS config in order to enabled common imports (it required to change the way we import `dayjs`
Freestyle
=> [Dasbhoard] refactor: use same redis-store as for human app

packages/examples/cvat/exchange-oracle/src/endpoints/exchange.py, packages/examples/cvat/exchange-oracle/src/services/exchange.py, packages/examples/cvat/exchange-oracle/tests/api/test_exchange_api.py
- Escrows in the `creation`, `deleted` statuses will not appear in GET `/job` responses
- Added an explanatory error message for POST /assignment requests, if the user has unfinished assignments
=> [CVAT] Dont show hidden escrows, add error message

packages/apps/human-app/frontend/src/pages/worker/jobs/components/my-jobs/desktop/my-jobs-table.tsx, packages/apps/human-app/frontend/src/pages/worker/jobs/components/my-jobs/mobile/my-jobs-table-mobile.tsx
Closes #2795 
Right now it's possible to keep clicking "Refresh" button many times and spamming with refresh requests to underlying servers. Taking into account that endpoint doesn't have any kind of rate-limiter (and might not need for now) we simply add "loading" state to "refresh" button to avoid spamming with requests.
Simply merge
N/A
=> feat: loading state for refresh tasks

packages/apps/human-app/server/src/common/filter/global-exceptions.filter.ts, packages/apps/human-app/server/src/integrations/exchange-oracle/exchange-oracle.gateway.ts
Closes #2796 
When `exception` is the instance of `AxiosError`. Unfortunately there is no way to export it from `@nestjs/axios` in order to check as `exception instanceof AxiosError`; it can be done from `axios` itself, but then we might lack consistency. However, we we need to respond with meaningful errors we can rely on existence of `exception.response` ([docs ref](https://axios-http.com/docs/handling_errors)) and use what axios provides. It has a `status` property that we should use, not one we might have in response body (e.g. when in Fortune's responses), because if there is no `statusCode` in response body - we assign `undefined` and it will be `500` on the client w/o meaningful error message.
[x] on local, with STG setup: go to Fortune oracle and attempt to assign task twice, it …
=> fix: global handling of axios errors

packages/apps/human-app/frontend/.eslintrc.cjs, packages/apps/human-app/frontend/src/i18n/en.json, packages/apps/human-app/frontend/src/pages/worker/profile/error-label.tsx, packages/apps/human-app/frontend/src/pages/worker/profile/profile-actions.tsx
N/A
It's possible to click on "Complete KYC" button even if status is "declined". Here we simply change that to display to the user their verif is declined.
Simply merge
N/A
=> feat: handle kyc declined status

packages/apps/human-app/frontend/src/api/services/worker/oracles.ts, packages/apps/human-app/frontend/src/hooks/use-my-jobs-filter-store.tsx, packages/apps/human-app/frontend/src/pages/worker/jobs-discovery/components/oracles-table/oracles-table-mobile.tsx, packages/apps/human-app/frontend/src/pages/worker/jobs-discovery/components/oracles-table/oracles-table.tsx, packages/apps/human-app/frontend/src/pages/worker/jobs/jobs.page.tsx
Closes #2805 
Adding hardcoded mapping from oracle url to human readable-names. There are three options:
1) Do it on UI
2) Do it in response with oracles
3) Do it when we fetch data by chain id
2 & 3 will also affect swagger documentation and that might be confusing for now, so chose first option.
Merge & deploy
N/A
=> [Human App] feat: add hardcoded oracles name mapping

packages/apps/job-launcher/client/package.json, packages/apps/job-launcher/client/src/pages/Job/JobDetail/index.tsx, packages/apps/job-launcher/client/src/services/job.ts, packages/apps/job-launcher/client/src/utils/api.ts, packages/apps/job-launcher/client/src/utils/string.ts, packages/apps/job-launcher/server/src/main.ts, packages/apps/job-launcher/server/src/modules/job/job.controller.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts, yarn.lock
Closes #2642 
Right now there is no way to easily download job results in case they are encrypted, so adding this functionality both on BE & FE. Fortune results are displayed on UI from JSON, so no need to do it for them.
Access to download results in decrypted format (if encrypted) should be possible only for auth'ed users, so we had two options:
1. create some sort of "share-able" link with short-lived token that we include in response to `getResult`
2. have a separate endpoint for downloading, that has common auth mechanism
Decided to got option 2 in order to not refactor existing functionality with `getResult` a lot (it is already mixed for Fortune and others)
Taking into account that "results" is not big in size and the fact that now we get it into app memory in order to decrypt (due …
=> [Job Launcher] feat: ability to download decrypted job results

packages/apps/human-app/server/src/modules/cron-job/cron-job.service.ts, packages/apps/human-app/server/src/modules/cron-job/spec/cron-job.service.spec.ts, packages/apps/human-app/server/src/modules/oracle-discovery/model/oracle-discovery.model.ts, packages/apps/human-app/server/src/modules/oracle-discovery/oracle-discovery.controller.ts, packages/apps/human-app/server/src/modules/oracle-discovery/oracle-discovery.service.ts, packages/apps/human-app/server/src/modules/oracle-discovery/spec/oracle-discovery.controller.spec.ts, packages/apps/human-app/server/src/modules/oracle-discovery/spec/oracle-discovery.fixture.ts, packages/apps/human-app/server/src/modules/oracle-discovery/spec/oracle-discovery.service.spec.ts
Closes #2815 
- Modify response dto of oracles discovery to include `chainIdsEnabled`
- Update tests
- Unit tests
- Run locally and verified the response
Frontend should be updated.
Node
=> [HUMAN App] Add enabled chain ids to oracles discovery response

packages/examples/cvat/recording-oracle/src/core/oracle_events.py
- Remove extra Job Launcher webhooks from the code of Recording Oracle
- Added missing Exchange Oracle webhooks in the list of acceptable webhooks of Recording Oracle
Manual test
=> [CVAT] Fix Recording Oracle webhook reception

packages/apps/job-launcher/server/tsconfig.json, packages/apps/reputation-oracle/server/docker-compose.yml, packages/apps/reputation-oracle/server/src/common/errors/base.ts, packages/apps/reputation-oracle/server/src/modules/payout/payout.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/payout/payout.service.ts, packages/apps/reputation-oracle/server/src/modules/reputation/reputation.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/reputation/reputation.service.ts, packages/apps/reputation-oracle/server/src/modules/storage/storage.errors.ts, packages/apps/reputation-oracle/server/src/modules/storage/storage.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/storage/storage.service.ts, packages/apps/reputation-oracle/server/test/constants.ts, packages/apps/reputation-oracle/server/tsconfig.json
Resolves #2719 
Storage module in SDK is going to be deprecated, so we get rid of it here. At the same time existing storage utils have a bug in working with binaries: when doing `copyFileFromURLToBucket` it's being downloaded as string instead of binary (which is expected to be a `.zip`) and it leads to file in invalid format being copied; this PR also fixed that.
Merge & deploy as is.
Only open question is if we need to fix some files that already uploaded as string instead of zip?!
Can't think of any
=> [Reputation Oracle] feat: get rid of sdk's storage module

packages/apps/reputation-oracle/server/src/modules/cron-job/cron-job.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/cron-job/cron-job.service.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.service.ts
N/A
1. When there is no `finalResultsUrl` in `escrowCompletionTrackingEntity`, we get it, update the entity, but in the code we still use destructured value, hence no proper value passed to `executePayouts`. Fixing this and adding a test on it
2. If webhook receiver returns code other than `201` - we considered it as error, but we need any 2xx, so changing the behavior to throw native Axios error
Merge
N/A
=> [Reputation Oracle] fix: escrow completion tracking process

packages/apps/human-app/frontend/src/i18n/en.json, packages/apps/human-app/frontend/src/pages/worker/registration/registration.page.tsx
Closes #2823 
We can handle middle-click with `onAuxClick` handler, but user is still able to click on right button and choose "open in new tab", so in order to avoid some other potential edge cases we simply change the link to button.
Merge
N/A
=> [Human App] feat: replace tutorial link with button

packages/apps/human-app/frontend/src/auth-web3/web3-auth-context.tsx, packages/apps/human-app/frontend/src/auth/auth-context.tsx, packages/apps/human-app/frontend/src/shared/types/browser-auth-provider.ts
N/A
Failing to deploy ([ref](https://vercel.com/humanprotocol/human-app/8eNQxHXRSEcXrgBWeg3EpM6W4RSW?filter=errors)) after merging https://github.com/humanprotocol/human-protocol/pull/2824. By some reason linter didn't catch invalid imports (neither did `yarn dev`)
Merge
Monitor that deployment is successful after merge
=> [Human App] fix: invalid imports of auth schema

packages/apps/human-app/server/src/integrations/kv-store/kv-store.gateway.ts, packages/apps/human-app/server/src/modules/oracle-discovery/spec/oracle-discovery.service.spec.ts, packages/apps/human-app/server/src/modules/ui-configuration/ui-configuration.dto.ts
This issue was identified due to a circular dependency error when attempting to document `ChainId` from `@human-protocol/sdk` in the NestJS Swagger schema. The error was triggered by using `ChainId` directly as an array in `@ApiProperty`. 
To resolve the circular dependency and make sure Swagger correctly interprets the `ChainId` enum, the following changes were made:
- Updated the `@ApiProperty` decorator for `chainIdsEnabled` in the `UiConfigResponseDto` to properly handle the `ChainId` enum in an array.
- Changed `type: [ChainId]` to `type: [String]` and included `enum: ChainId` for correct enum documentation.
- Ensured that Swagger UI shows the list of possible enum values for `ChainId`.
- `yarn build && yarn start:prod` 
- Verified the Swagger UI to ensure the `ChainId` enum is …
=> [Human App] Fixed ui configuration response dto

packages/apps/dashboard/server/docker-compose.yml, packages/apps/dashboard/server/src/modules/stats/stats.service.ts, packages/apps/human-app/server/docker-compose.yml
N/A
When getting values from cache it returns `undefined` when no value is there, so we have to properly check if the stat is missing.
Also updated docker-compose files for human-app and dashboard server:
- removed `version` because it's not necessary anymore
- added `name`, so when you have `redis` started in one of servers already, starting it in another one doesn't kill existing (they run on different ports anyways)
Merge
N/A
=> [Dashboard] fix: properly filter dashboard stats values

packages/apps/job-launcher/client/src/components/Jobs/Create/CvatJobRequestForm.tsx, packages/apps/job-launcher/client/src/types/index.ts, packages/apps/job-launcher/client/src/utils/api.ts, packages/apps/job-launcher/server/src/common/constants/index.ts, packages/apps/job-launcher/server/src/common/enums/job.ts, packages/apps/job-launcher/server/src/common/utils/index.ts, packages/apps/job-launcher/server/src/common/utils/storage.ts, packages/apps/job-launcher/server/src/database/migrations/1732612497937-addJobTypeToJobsRequestTypeEnum.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts
**## Issue tracking**  
The progress of this issue is being tracked in [Job Launcher][Client/Server] Add a new CVAT job type - IMAGE_POLYGONS
[#2700](https://github.com/humanprotocol/human-protocol/issues/2700).  
**## Context behind the change**  
This PR introduces a new CVAT job type: `IMAGE_POLYGONS`.  
- **Front-End (FE):**  
The implementation for the `IMAGE_POLYGONS` job type uses the same general and annotation details as the existing `IMAGE_BOXES` job type.  
- **Back-End (BE):**  
The manifest schema for `IMAGE_POLYGONS` follows the same structure as `IMAGE_BOXES` to maintain consistency.  
New migration was added `1732612497937-addJobTypeToJobsRequestTypeEnum.ts`.
**## How has this been tested?**  
The following tests were conducted to validate the changes:  
1. **Unit tests:** …
=> [Job Launcher] Implemented image polygons job type

packages/apps/human-app/frontend/src/i18n/en.json, packages/apps/human-app/frontend/src/smart-contracts/EthKVStore/config.ts, packages/apps/reputation-oracle/server/src/common/constants/index.ts, packages/apps/reputation-oracle/server/src/common/enums/job.ts, packages/apps/reputation-oracle/server/src/modules/payout/payout.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/payout/payout.service.ts, packages/apps/reputation-oracle/server/src/modules/reputation/reputation.service.ts
Addition to https://github.com/humanprotocol/human-protocol/pull/2845
In order to properly support new job type we need to add it to `human-app` and `reputation-oracle`.
For `human-app` it's just about updating few enums that affect:
- how job type is displayed (aka human-readable labels for user)
- adds new job type to list of options for "operator registration" form
For `reputation-oracle` we need to:
- update enums, so types are valid
- update mappings for payouts and reputation calculation
Ideally, would be nice to refactor code in RO to not depend on job type (code is the same for all CVAT types, but different for Fortune), but it would be better to do it in separate PR
1. Merge. Release together with main PR that adds it to ExO and JL.
2. In order to see proper job types on …
=> feat: add image_polygons to human-app and repo

packages/examples/cvat/recording-oracle/src/handlers/process_intermediate_results.py, packages/examples/cvat/recording-oracle/tests/integration/services/test_validation_service.py, packages/examples/cvat/recording-oracle/tests/utils/helpers.py
Sometimes it was possible to get repeated validation frames in 1 job. This PR fixes this problem.
- Fixed honeypot reroll calls in RO
Unit test
=> [CVAT] Refactor and fix honeypot rerolls

package.json
Freestyle
Right now in case you have `human-app/server` built and then try to `yarn install` - you will get an error about duplicated `@human-protocol/human-app-server` workspace. It's because `package.json` is included in build and when `yarn` searches for workspaces using existing glob-pattern it finds another one in `dist` folder.
Changing glob pattern to not take `dist` into account.
As an alternative - we can list all workspaces manually, but it might be tedious.
Simply merge
N/A
=> fix: change yarn workspaces pattern

packages/apps/dashboard/server/src/common/enums/roles.ts, packages/apps/dashboard/server/src/modules/details/details.service.ts
[Dashboard server] Error fetching reputations
[#2848](https://github.com/humanprotocol/human-protocol/issues/2848)
The Reputation Oracle server returned errors when validating role values because they were provided in uppercase (`JOB_LAUNCHER`, etc.), while the server expected them in lowercase (`job_launcher`, etc.).  
To address this, was implemented an `OracleRole` enum that standardizes the role values to lowercase, ensuring compatibility with the Reputation Oracle server and preventing further validation errors.
Changes made:  
- Created a new `OracleRole` enum to enforce consistent lowercase role values.
- Updated relevant code sections where role values are assigned or validated to use the `OracleRole` enum.
1. **Manual Testing**  
- Simulated different role assignments and …
=> [Dashboard Server] Fixed roles values

packages/core/.openzeppelin/bsc-testnet.json, packages/core/.openzeppelin/sepolia.json, packages/core/.openzeppelin/unknown-80002.json, packages/core/contracts/Escrow.sol, packages/core/test/Escrow-USDT.ts, packages/core/test/Escrow.ts
#2895
This pull request modifies the complete function to allow direct invocation for finalizing the escrow after the bulkPayOut function has already been executed. Previously, the complete function is just for compatibility with old escrows. The goal of this change is to simplify the workflow, enhance user experience, and reduce unnecessary steps.
The following parts of the code were updated:
- complete function: Updated logic to support direct completion from Paid or Partial states.
- bulkPayOut function: Integrated with the new logic for seamless transition.
- Test cases: Added and updated tests to validate the updated behavior of the complete function.
Deployed locally testing some edge cases and unit tests 
Deploy contracts.
Check if payments are being made properly to the launcher …
=> Allow direct call to complete after bulkPayOut

packages/apps/human-app/frontend/src/api/services/worker/oracles.ts, packages/apps/human-app/server/src/modules/cron-job/cron-job.module.ts, packages/apps/human-app/server/src/modules/cron-job/cron-job.service.ts, packages/apps/human-app/server/src/modules/cron-job/spec/cron-job.service.spec.ts, packages/apps/human-app/server/src/modules/jobs-discovery/jobs-discovery.service.ts, packages/apps/human-app/server/src/modules/jobs-discovery/spec/jobs-discovery.service.spec.ts, packages/apps/human-app/server/src/modules/oracle-discovery/model/oracle-discovery.model.ts, packages/apps/human-app/server/src/modules/oracle-discovery/oracle-discovery.controller.ts, packages/apps/human-app/server/src/modules/oracle-discovery/oracle-discovery.mapper.profile.ts, packages/apps/human-app/server/src/modules/oracle-discovery/oracle-discovery.service.ts, packages/apps/human-app/server/src/modules/oracle-discovery/spec/oracle-discovery.controller.spec.ts, packages/apps/human-app/server/src/modules/oracle-discovery/spec/oracle-discovery.fixture.ts, packages/apps/human-app/server/src/modules/oracle-discovery/spec/oracle-discovery.service.mock.ts, packages/apps/human-app/server/src/modules/oracle-discovery/spec/oracle-discovery.service.spec.ts
Closes #2863 
Right now we fetch and cache all jobs for oracle, w/o preliminary filtration by `chainId`, so all visible for user regardless of configuration. The proper way to fix it would be to fetch & store jobs per chain, then also request them per chain, but it involves much more refactoring on BE + changing the UI to support that.
Right now we go simple path an just filter out jobs that do not belong to enable chains when retrieving them for UI.
Also fixed `jobTypes` filter fo `hCaptcha` oracle on UI.
Later we will discuss UI changes and refactor jobs discovery for good.
As a "scout rule" for now refactored "oracle discovery" and "cron" a bit.
1. [ ]  Fix values of `job_types` in KV store of Reputation Oracle
2. [ ] Fix values of `jobTypes` in KV store for `Fortune` oracles (in all …
=> [Human App] feat: filter out oracle jobs as per enabled chain id

packages/sdk/python/human-protocol-sdk/pyproject.toml
Closes #2857 
Change python sdk name to be PEP 625 compliance
Cannot be tested until deployment is triggered.
- Trigger release
- Check if sdk with old name is linked to the new released version: https://pypi.org/project/human-protocol-sdk/
- Pypi might consider them as different packages.
=> [SDK] Change python sdk name to be PEP 625 compliance

packages/apps/human-app/server/src/integrations/exchange-oracle/exchange-oracle.gateway.ts, packages/apps/human-app/server/src/modules/job-assignment/job-assignment.service.ts, packages/apps/human-app/server/src/modules/job-assignment/spec/job-assignment.service.spec.ts
Fixes #2927 
When doing assign/resign job there is a background functionality to update existing assignments cache for the user. To do so it uses jwt token from the request and there can be situations when it's in time to perform main operation, but when updating the cache token expires and it leads to 401 error.
For `resignJob` we had an `await`, so when such error happened it was handled by global exception filter, but for `processJobAssignment` we didn't, so it led to the global unhandled rejection for the app
Taking into account that updating cache shouldn't affect the result of assign/resign for the user, now we will be running both in background and handle errors just with logging purpose. Didn't add `try..catch` to `updateAssignmentsCache` itself because it's used in …
=> [Human App] fix: unhandled errors from updateAssigmentsCache

packages/apps/job-launcher/server/src/common/utils/index.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts, packages/apps/job-launcher/server/src/modules/job/routing-protocol.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/routing-protocol.service.ts
N/A
When creation job in Job Launcher, we send `jobType` value in snake case from UI, but later on BE map it to human readable values that are used for getting oracles from network. However, it's expected that oracles have `jobTypes` as snake cased value, not human-readable, so fixing it here.
1. [ ] Merge this PR
2. [ ] Fix `job_types` in Reputation Oracle KV in mainnet
3. [ ] Deploy this PR
That we might not able to run jobs on JL in the time window between step 2 and 3 of the release plan. However, we were able to run jobs while having snake cased values on staging: because when setting up escrow we use values from env config ([ref](https://github.com/humanprotocol/human-protocol/blob/efc80d3114bfd050bbf3a58537822567afa6fb00/packages/apps/job-launcher/server/src/modules/job/job.service. …
=> [Job Launcher] fix: get rid of job types mapping in job creation

packages/apps/reputation-oracle/server/src/common/constants/errors.ts, packages/apps/reputation-oracle/server/src/modules/reputation/reputation.controller.ts, packages/apps/reputation-oracle/server/src/modules/reputation/reputation.error.filter.ts, packages/apps/reputation-oracle/server/src/modules/reputation/reputation.error.ts, packages/apps/reputation-oracle/server/src/modules/reputation/reputation.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/reputation/reputation.service.ts
#2928
- Refactored error handling for reputation module.
- Minor fixes in business logic for unused errors
1. Setup a local postgres database, apply migrations.
2. Deploy reputation oracle locally.
3. Get reputation of any address not used for any process. 
None
None
=> [Reputation Oracle] Error handling for `reputation`module

packages/apps/reputation-oracle/server/src/common/constants/errors.ts, packages/apps/reputation-oracle/server/src/common/constants/index.ts, packages/apps/reputation-oracle/server/src/common/guards/jwt.auth.ts, packages/apps/reputation-oracle/server/src/common/utils/signature.spec.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.controller.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.error-filter.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.errors.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts, packages/apps/reputation-oracle/server/src/modules/auth/strategy/jwt.http.ts, packages/apps/reputation-oracle/server/src/modules/credentials/credential.service.ts, packages/apps/reputation-oracle/server/src/modules/user/user.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/user/user.service.ts, packages/apps/reputation-oracle/server/test/constants.ts
Part of #2928
- refactored error handling of `auth` module.
- removed `getByCredentials` from `UserService` because in fact it did auth check and shouldn't live there; instead introduced `checkPasswordMatchesHash`  and use it for auth checks
- in methods where we send emails (e.g. forgotPassword) now we won't throw when user is not found, but just return; previously it was `ControlledError` with `204` status code, so result is expected to be the same
Simply merge & deploy
It might be that there is some client implicitly relying on returned error message/code that changed in this PR. To monitor it we can check logs.
=> [Reputation Oracle] refactor: auth module error handling

packages/apps/dashboard/server/src/modules/networks/network.service.spec.ts, packages/apps/dashboard/server/src/modules/networks/networks.service.ts, packages/apps/dashboard/ui-2024/src/components/SearchBar/SearchBar.tsx, packages/apps/dashboard/ui-2024/src/features/Leaderboard/components/SelectNetwork.tsx, packages/apps/dashboard/ui-2024/src/services/api-paths.ts, packages/apps/dashboard/ui-2024/src/utils/hooks/use-filtered-networks.ts, packages/apps/dashboard/ui-2024/src/utils/hooks/use-leaderboard-search.ts, packages/apps/dashboard/ui-2024/src/utils/hooks/use-wallet-search.ts
#2855 #2972
- Updated the frontend to dynamically fetch active networks from the backend.
- Ensured that only active networks are displayed in all select inputs across the application (e.g., SearchBar and Leaderboard components).
- Modified data querying logic to restrict API calls to enabled networks only, improving reliability and efficiency.
- Deployed the changes locally.
- Set up a test environment with predefined active networks from the backend.
- Verified the following:
- Active networks are correctly displayed in the SearchBar select input.
- Data filtering and display in the Leaders table function as expected.
- Network-related navigation and data fetching work as intended.
Deploy frontend and backend.
None
=> [Dashboard client] Show only enabled networks

packages/apps/reputation-oracle/server/src/common/constants/errors.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.controller.ts, packages/apps/reputation-oracle/server/src/modules/escrow-completion/escrow-completion.service.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook-incoming.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook-incoming.service.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook-outgoing.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook-outgoing.service.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.controller.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.error.filter.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.error.ts
#2928
- Refactored error handling for webhook module.
- Removed some unused imports.
- Setup a local postgres database, apply migrations.
- Deploy reputation oracle locally.
- Send webhook with an invalid event type.
None
None
=> [Reputation Oracle] Error handling for webhook module

packages/apps/human-app/frontend/src/modules/operator/views/sign-up/add-keys.page.tsx
N/A
When operator attempts to sign up and opens add/edit keys form the page is blank and app crashes. It's a [regression introduced by this line](https://github.com/humanprotocol/human-protocol/pull/2933/files#diff-e7638f3c31c56213c2663c5fbbc165cf41aef63fa17375b27456af39b71d50b4R65).
There is a "peculiarity" in TypeScript in how it infers types of "optional properties" when used with generic types (which is the case for `Object.values`/`Object.entires`), e.g.:
```
ype Test = { a?: string | undefined };
const test: Test = { a: undefined };
Object.values(test).filter((value) => value?.length); // 'value' typed as 'string'
function demo<T>(object: Record<string, T>): T {
return object.a;
}
const value = demo(test); // 'value' typed as 'string'
```
but if you remove `?` from the type - it …
=> [Human App] fix: operator signup keys form

packages/apps/job-launcher/server/src/common/constants/errors.ts, packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.controller.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.controller.ts, packages/apps/job-launcher/server/src/modules/job/job.module.ts, packages/apps/job-launcher/server/src/modules/job/job.service.spec.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts, packages/apps/job-launcher/server/src/modules/payment/payment.service.ts
#2931
Check that the user has a credit card during job creation, so we can slash him in case of abuse.
This check does not apply to whitelisted users
Deployed locally and launched tests
None
None
=> [Job Launcher] Check that the user has a credit card during job creation

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/gql/operator.py
#2992
Missing website value in Leader entity. 
Added website value in leader_fragment for solving it.
Made some requests locally. Also ran some tests
None
None
=> Add website to Leader fragment for subgraph queries

packages/apps/staking/package.json, packages/apps/staking/vercel.json
NA
Add Vercel config for staking dashboard deployment
Deployment succesfull on Vercel
NA
NA
=> Add Vercel config for staking dashboard deployment

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/constants.py, packages/sdk/typescript/subgraph/tests/kvstore/kvstore.test.ts
The progress of this issue is being tracked on GitHub under issue [SDK] Remove validator role
[#2980](https://github.com/humanprotocol/human-protocol/issues/2980).
The change involves removing the `validator` role from the SDK. This role is no longer necessary.
The changes have been tested through unit tests that cover role assignments and permissions checks.
=> [SDK] Removed validator role

.github/workflows/cd-subgraph.yaml, packages/sdk/python/human-protocol-sdk/human_protocol_sdk/constants.py, packages/sdk/typescript/human-protocol-sdk/src/constants.ts
NA
- Update deployed subgraph ids for beta version
- Update deployment workflow to allow passing the networks to be deployed in a comma separated list.
Workflow used to upgrade subraphs from local
NA
NA
=> Update deployed subgraph ids and update deployment workflow

packages/examples/cvat/recording-oracle/src/handlers/process_intermediate_results.py, packages/examples/cvat/recording-oracle/src/handlers/validation.py, packages/examples/cvat/recording-oracle/tests/integration/services/test_validation_service.py
- Restored and fixed unexpectedly skipped test
- Improved several log messages with percent values
- Fixed confusing mean dataset quality computation for the resulting quality log message
=> [CVAT] Improve log messages in Recording Oracle

packages/sdk/typescript/human-protocol-sdk/src/escrow.ts, packages/sdk/typescript/human-protocol-sdk/src/statistics.ts, packages/sdk/typescript/human-protocol-sdk/src/transaction.ts, packages/sdk/typescript/human-protocol-sdk/src/utils.ts, packages/sdk/typescript/human-protocol-sdk/test/statistics.test.ts
#2912
1. Updated all instances of getTime() / 1000 to use Math.floor to ensure dates are rounded to the nearest second.
2. Updated tests to round also expected values
Ran examples and tests with different dates.
Deploy new SDK version
=> [SDK] fix: date rounding issues

packages/apps/reputation-oracle/server/src/common/constants/errors.ts, packages/apps/reputation-oracle/server/src/common/constants/networks.ts, packages/apps/reputation-oracle/server/src/modules/escrow-completion/escrow-completion.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/escrow-completion/escrow-completion.service.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook-incoming.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook-incoming.service.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook-outgoing.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook-outgoing.service.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook.error.ts
Part of #2928 
Removing `ControlledError` from escrow-completion module as per refactoring plan.
WIth this module it was decided to not create custom error classes because there is no need to control execution flow based on specific error type, it's enough to just throw and log details in place.
Simply merge.
Can't think of any
=> [Reputation Oracle] refactor: get rid of controlled error in escrow completion

packages/apps/dashboard/server/package.json, yarn.lock
N/A
After recent dep update in [PR#3046](https://github.com/humanprotocol/human-protocol/pull/3046) Dashboard server is failing to start. Dep wasn't updated properly (it's used not only by dashboard server, but by other apps as well) and might need some additional changes due to major version updated
Deploy with original PR.
N/A
=> fix: nestjs platform package

packages/apps/dashboard/client/package.json, packages/apps/dashboard/client/vite.config.ts
#3078
Current deployments are failing due to SDK build process.
Add vercel-build script to package.json for SDK build process to fix the current failure.
Deploy dashboard client
=> [Dashboard] Add vercel-build

packages/apps/staking/src/components/modals/KVStoreModal.tsx
#3080
Remove CaseConverter usage in KVStoreModal to display role values directly
None
None
=> [Staking] Unify kvstore dropdowns

packages/apps/fortune/exchange-oracle/server/src/common/enums/webhook.ts, packages/apps/fortune/exchange-oracle/server/src/database/migrations/1739274494282-escrowFailed.ts, packages/apps/fortune/exchange-oracle/server/src/modules/job/job.service.ts, packages/apps/fortune/exchange-oracle/server/src/modules/webhook/webhook.dto.ts, packages/apps/fortune/exchange-oracle/server/src/modules/webhook/webhook.entity.ts, packages/apps/fortune/exchange-oracle/server/src/modules/webhook/webhook.service.spec.ts, packages/apps/fortune/exchange-oracle/server/src/modules/webhook/webhook.service.ts, packages/apps/job-launcher/server/src/common/enums/webhook.ts, packages/apps/job-launcher/server/src/database/migrations/1739194616649-escrowFailed.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts, packages/apps/job-launcher/server/src/modules/webhook/webhook.service.ts, packages/sdk/typescript/subgraph/config/localhost.json
#3059 
remove `TASK_CREATION_FAILED` event and add `failureDetail` to webhook entity
Launched locally. 
Also ran tests.
Deploy DB migrations in JL and ExO
None
=> [Job Launcher][Exchange Oracle] Remove TASK_CREATION_FAILED event

.github/workflows/ci-test-cvat-recording-oracle.yaml, packages/examples/cvat/recording-oracle/docker-compose.test.yml, packages/examples/cvat/recording-oracle/dockerfiles/blockchain-node.Dockerfile, yarn.lock
N/A
https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/1128
After recent deps update we got one dependency with the issue, so rolling it back.
Also refactored Docker file for CVAT tests bloackchain node to be build from the pulled code, not `develop`
Simply merge
No
=> fix: broken dependency causing Docker builds to fail

packages/apps/reputation-oracle/server/src/modules/health/health.controller.spec.ts, packages/apps/reputation-oracle/server/src/modules/health/health.controller.ts
Part of #3084 
`health` module doesn't have much business logic, so just covering controller with unit tests to make sure we will get what we expect in health checks.
Simply merge
No
=> [Reputation Oracle] test: cover health controller with unit tests

package.json, yarn.lock
N/A
Follow-up to https://github.com/humanprotocol/human-protocol/pull/3103
Simply merge
No
=> deps: updated lockfile for semver

packages/apps/human-app/frontend/src/modules/worker/components/profile/profile.page.tsx, packages/apps/human-app/frontend/src/shared/contexts/wallet-connect/wallet-connect.tsx
Closes: HUM-170
- Added wallet connect initialization check
- Relaxed `isReady` condition as the `mutation.data` could be empty
- tested the expected behaviour on production build
normal
N/A
=> [HUM-170]: fix: error notification is displayed twice when should be once

packages/core/contracts/governance/MetaHumanGovernor.sol, packages/core/hardhat.config.ts, packages/core/scripts/deploy-hub.ts, packages/core/scripts/deploy-vhmt.ts, packages/core/scripts/proposal.ts, packages/core/scripts/queue-proposal.ts, packages/core/scripts/update-spokes.ts, packages/core/test/GovernanceUtils.ts, packages/core/test/MetaHumanGovernorHubOnly.ts
While Governance is designed to support cross-chain voting, we still want to support voting only on hub chain.
Current vote collection flow is only working when there are spoke contracts, and wormhole relayer is properly configured.
This changes allows us to finish collection phase only on hub chain after the vote ends, when there are no dao spoke contracts.
I added a new test case for governance contract to execute the proposal, without dao spoke contracts deployed.
=> fix: allow governance execution without dao spoke contract

packages/examples/cvat/exchange-oracle/poetry.lock, packages/examples/cvat/exchange-oracle/pyproject.toml, packages/examples/cvat/exchange-oracle/src/chain/web3.py, packages/examples/cvat/exchange-oracle/tests/integration/chain/test_web3.py, packages/examples/cvat/recording-oracle/poetry.lock, packages/examples/cvat/recording-oracle/pyproject.toml, packages/examples/cvat/recording-oracle/src/chain/web3.py, packages/examples/cvat/recording-oracle/tests/integration/chain/test_escrow.py, packages/examples/cvat/recording-oracle/tests/integration/chain/test_web3.py, packages/examples/cvat/recording-oracle/tests/integration/cron/test_process_exchange_oracle_webhooks.py, packages/examples/cvat/recording-oracle/tests/integration/cron/test_process_reputation_oracle_webhooks.py, packages/examples/cvat/recording-oracle/tests/utils/setup_kvstore.py
#3121 
`human-protocol-sdk` version upgrade to 4.0.3 and all the corresponding changes in src.
Unit/integration tests + github action
N/A
Monitor CVAT oracles
=> [CVAT] bump: `human-protocol-sdk` upgrade to 4.0.3

packages/apps/human-app/frontend/src/modules/worker/hcaptcha-labeling/enable-labeler.page.tsx, packages/apps/human-app/frontend/src/modules/worker/hcaptcha-labeling/hooks/enable-hcaptcha-labeling.ts, packages/apps/human-app/frontend/src/modules/worker/hcaptcha-labeling/hooks/index.ts
HUM-102
- moved hook to corresponding module
- checked build: no logic changes
standard
N/A
=> [HUM-102]: chore: move hcaptcha labeling hook to its module

packages/apps/human-app/frontend/src/modules/governance-banner/components/governance-banner.tsx
N/A
Prevent rendering of governance banner if KYC is not approved
N/A
None
None
=> [Human App] Prevent rendering governance banner if KYC is not approved

packages/apps/human-app/frontend/src/router/router.tsx, packages/apps/human-app/frontend/src/shared/components/layout/protected/layout.tsx
N/A
Operator UI is currently broken because we attempt to render `GovernanceBanner` that uses `useWorkerKycStatus` -> `useAuthenticatedUser` -> `AuthenticatedUserContext`, which is available only for worker user, not operator.
Fixing it by displaying banner only for worker layout
Simply merge
No
=> [HUMAN App] fix: show governance banner only for workers

packages/apps/dashboard/server/src/common/config/env-config.service.ts, packages/apps/dashboard/server/src/modules/stats/stats.service.ts
#3151
update HMT price source to CoinLore API and make system compatible with Coingecko and CoinLore in case we need to switch between them
Update `HMT_PRICE_SOURCE` and remove `HMT_PRICE_SOURCE_API_KEY` from current env to use CoinLore
None
How will we handle any issues if they arise? Do we need rollback plan?
Undo env change
=> [Dashboard] Change third party service to get HMT price

packages/apps/dashboard/server/src/modules/stats/stats.service.ts
N/A
validate HMT symbol in Coinlore API response
None
None
=> [Dashboard] Validate HMT symbol in Coinlore API response

packages/apps/reputation-oracle/server/src/config/env-schema.ts, scripts/cvat/docker-compose.local.yml, scripts/cvat/env-files/.env.reputation-oracle
N/A
Right now if `NDA_URL` is not provided app can start but it's not possible to sign-in. So we need to add `NDA_URL` as `reuiqred` var in env schema validation to avoid it.
`NDA_URL` must be added to list of env vars
No
=> [Reputation Oracle] fix: add nda_url as required env

packages/apps/human-app/frontend/src/modules/homepage/components/index.ts, packages/apps/human-app/frontend/src/modules/homepage/components/logo-section.tsx, packages/apps/human-app/frontend/src/modules/homepage/components/sign-in-section.tsx, packages/apps/human-app/frontend/src/modules/homepage/components/welcome.tsx
HUM-154
- separated some components from welcome paga
- checked if page displays the same as before and works in all sizes
- checked if buttons work
normal
n/a
=> [HUM-154]: chore: separated components form welcome page

.github/workflows/cd-subgraph.yaml, .github/workflows/ci-test-subgraph.yaml
NA
Correct indentation in subgraphs CI workflow configuration
workflow executed locally
NA
NA
=> fix: correct indentation in subgraphs CI workflow configuration

packages/apps/job-launcher/server/src/common/constants/errors.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts, packages/apps/job-launcher/server/src/modules/whitelist/whitelist.service.spec.ts, packages/apps/job-launcher/server/src/modules/whitelist/whitelist.service.ts
=> [Job Launcher] Fix payment creation order and enable whitelist check

packages/apps/human-app/server/src/common/constants/hmt.ts, packages/apps/human-app/server/src/common/enums/global-common.ts, packages/apps/human-app/server/src/common/utils/pagination.utils.ts, packages/apps/human-app/server/src/modules/cron-job/cron-job.service.ts, packages/apps/human-app/server/src/modules/cron-job/spec/cron-job.service.spec.ts, packages/apps/human-app/server/src/modules/job-assignment/job-assignment.service.ts, packages/apps/human-app/server/src/modules/jobs-discovery/jobs-discovery.service.ts, packages/apps/human-app/server/src/modules/jobs-discovery/model/jobs-discovery.model.ts, packages/apps/human-app/server/src/modules/jobs-discovery/spec/jobs-discovery.fixtures.ts
Fixes #2679 
`reward_amount` is returned from exchange oracles as `string` that represents decimal. Even if we convert it to some big int - we will have to store it as string in Redis and then convert it back when responding to client, so taking into account there are no more use cases other than sort we simply pass a comparator function to pagination+sort util when `reward_amount` property is desired as sort field.
Also changed job discovery process to ensure that it always has all necessary fields before caching jobs in Redis.
Just merge.
No.
=> [HUMAN App] fix: invalid sorting by `reward_amount`

packages/apps/job-launcher/client/src/components/Jobs/Create/HCaptchaJobRequestForm.tsx
NA
Remove external link from HCaptchaJobRequestForm.
Hcaptcha job creation from the frontend is disabled anyway. In case we enable it, a proper link should be set.
Run locally
NA
NA
=> [Job Launcher] Remove external link from HCaptchaJobRequestForm

packages/apps/job-launcher/client/src/components/BillingDetails/BillingDetailsModal.tsx, packages/apps/job-launcher/client/src/types/index.ts, packages/apps/job-launcher/server/src/modules/payment/payment.service.ts
#3206
Update validation logic for optional VAT and VAT Type in BillingDetailsModal
None
Check if Vat and Vat type can be added appropriately
=> [Job Launcher Client] Allow adding biliing details without tax ID

packages/apps/job-launcher/server/src/modules/cron-job/cron-job.service.ts, packages/apps/job-launcher/server/src/modules/webhook/webhook.repository.ts
N/A
Support multiple event types in webhook status query.
Deployed locally. Created a new escrow, canceled it and checked that the webhook has been created and sent to Exchange Oracle
None
Check if ESCROW_CANCELED webhooks are being processed
=> [Job Launcher] Send ESCROW_CANCELED webhooks

yarn.lock
Follow up to https://github.com/humanprotocol/human-protocol/pull/3235
`vite` got bumped, but not all resolutions were respected. Fixing in this PR.
Searched in `yarn.lock` for `vite` entries to ensure they are correct.
Simply merge
No
=> fix: vite package resolutions

packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts
Found on staging
When some key isn't presented in KVStore - sdk throws and error instead of returning `undefined` or `null`. Recently we changed the code where we removed try..catch around KVStore utils by mistake, so adding it back here.
Together w/ main `auth` module refactoring PR
No
=> [Reputation Oracle] fix: handle key not found kv store errors

packages/apps/reputation-oracle/server/src/modules/auth/auth.error.filter.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.error.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts
Closes #3236 
- Forbid workers with `inactive` status to signin
- Forbid operators with `inactive` status (in DB!) to signin
N/A
N/A
=> [Reputation Oracle] Forbid login if user is in `inactive` status

packages/apps/job-launcher/client/src/components/Headers/AuthHeader.tsx, packages/apps/job-launcher/client/src/components/Jobs/Create/CreateJob.tsx, packages/apps/job-launcher/client/src/components/Jobs/Create/CryptoPayForm.tsx, packages/apps/job-launcher/client/src/components/Jobs/Create/CvatJobRequestForm.tsx, packages/apps/job-launcher/client/src/components/Jobs/Create/FiatPayForm.tsx, packages/apps/job-launcher/client/src/components/Jobs/Create/FortuneJobRequestForm.tsx, packages/apps/job-launcher/client/src/components/Jobs/Create/FundingMethod.tsx, packages/apps/job-launcher/client/src/components/Jobs/Create/HCaptchaJobRequestForm.tsx, packages/apps/job-launcher/client/src/components/Jobs/Create/LaunchJobProgress.tsx, packages/apps/job-launcher/client/src/components/Jobs/Create/LaunchSuccess.tsx, packages/apps/job-launcher/client/src/components/Jobs/Create/PayJob.tsx, packages/apps/job-launcher/client/src/components/Jobs/Create/helpers.ts, packages/apps/job-launcher/client/src/components/Jobs/Create/index.tsx, packages/apps/job-launcher/client/src/providers/CreateJobPageUIProvider.tsx, packages/apps/job-launcher/client/src/types/index.ts
Closes #3209
The spinner being shown regardless of the request's status, no matter whether it's fulfilled or rejected. Instead, let's display an ErrorIcon if the request is failed. Moreover, I've added a button that lets users get back to the form and see what values might be wrong.
Also this pr includes some refactoring
tested it locally: go to the job launching form, fill in all the fields and click on Pay Now. you shall see the error icon and 'cancel' button, that takes you back to the second step
https://github.com/user-attachments/assets/278fc4ab-d27d-4dc9-b49f-33a7afe88245
regular plan
not determined yet
=> [Job Launcher] [Client] Infinite spinner when create job fails

packages/examples/cvat/exchange-oracle/src/core/annotation_meta.py, packages/examples/cvat/exchange-oracle/src/core/oracle_events.py, packages/examples/cvat/exchange-oracle/src/core/types.py, packages/examples/cvat/exchange-oracle/src/crons/__init__.py, packages/examples/cvat/exchange-oracle/src/crons/webhooks/recording_oracle.py, packages/examples/cvat/exchange-oracle/src/handlers/completed_escrows.py, packages/examples/cvat/exchange-oracle/src/handlers/cvat_events.py, packages/examples/cvat/exchange-oracle/src/handlers/job_export.py, packages/examples/cvat/exchange-oracle/src/services/cvat.py, packages/examples/cvat/exchange-oracle/src/services/webhook.py, packages/examples/cvat/exchange-oracle/tests/integration/cron/state_trackers/test_track_completed_escrows.py, packages/examples/cvat/exchange-oracle/tests/integration/cron/test_process_recording_oracle_webhooks.py, packages/examples/cvat/recording-oracle/src/core/annotation_meta.py, packages/examples/cvat/recording-oracle/src/core/oracle_events.py, packages/examples/cvat/recording-oracle/src/core/types.py, packages/examples/cvat/recording-oracle/src/core/validation_results.py, packages/examples/cvat/recording-oracle/src/crons/__init__.py, packages/examples/cvat/recording-oracle/src/crons/process_exchange_oracle_webhooks.py, packages/examples/cvat/recording-oracle/src/handlers/completion.py, packages/examples/cvat/recording-oracle/src/handlers/process_intermediate_results.py, packages/examples/cvat/recording-oracle/src/handlers/validation.py, packages/examples/cvat/recording-oracle/src/services/webhook.py, packages/examples/cvat/recording-oracle/tests/integration/cron/test_process_exchange_oracle_webhooks.py, packages/examples/cvat/recording-oracle/tests/integration/services/test_validation_service.py
Annotation export for an escrow can take huge amount of time, but it's not really necessary as we do validation in CVAT. This PR moves exporting to happen only after successful escrow acceptance.
Messaging:
old:
1. EO -> job_finished -> RO
2. RO -> job_completed -> EO, RepO
new:
1. EO -> job_finished -> RO
2. RO -> job_completed -> EO
3. EO -> escrow_recorded -> RO
4. RO -> job_completed -> RepO
- Added a new EO -> RO event `escrow_recorded`, it is sent after successful annotation export
- EO: 
- Removed annotation export from validation attempt preparations (right before `job_finished` event)
- Added annotation export to RO `job_completed` event handling
- Added sending of new event `escrow_recorded` after successful export in RO `job_completed` event handling
- RO: 
- Removed annotation …
=> [CVAT] Move annotation downloading after successful validation

packages/apps/human-app/server/src/modules/cron-job/cron-job.service.ts, packages/apps/job-launcher/server/src/common/enums/webhook.ts, packages/apps/job-launcher/server/src/database/migrations/1743611706650-AudinoOracleType.ts, packages/apps/job-launcher/server/src/modules/job/job.service.ts
Follow up to https://github.com/humanprotocol/human-protocol/pull/3258
When creating webhooks, we also specify oracle type, and this part was missed while adding Audino. Adding it here.
Also changed HUMAN App to fetch & cache only `active` jobs from ExcO.
- locally
W/ main PR
No
=> [Job Launcher] fix: add missing OracleType for audino

yarn.lock
https://github.com/humanprotocol/human-protocol/actions/runs/14310193487?pr=3213
Bumping resolved `vite` package version to avoid dep review
- CI
Simply merge
N/A
=> chore: bump vite to address dep review

packages/apps/human-app/frontend/src/modules/signup/operator/views/add-stake.page.tsx, packages/apps/human-app/frontend/src/modules/signup/worker/views/sign-up-worker.page.tsx, packages/apps/human-app/frontend/src/modules/worker/jobs-discovery/components/oracles-table.tsx, packages/apps/human-app/frontend/src/modules/worker/jobs/available-jobs/hooks/use-assign-job.ts, packages/apps/human-app/frontend/src/modules/worker/jobs/hooks/use-jobs-notifications.tsx, packages/apps/human-app/frontend/src/shared/errors/get-error-message-for-error.ts, packages/apps/human-app/frontend/src/shared/types/global.type.ts
N/A
Currently we display common error message for signup
so fixing handler here: now it takes bool, but should take error object
Merge
N/A
=> [HUMAN App] fix: signup error handling

packages/apps/reputation-oracle/server/src/config/auth-config.service.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts
N/A
Introduced in https://github.com/humanprotocol/human-protocol/pull/3205: expiration time for JWT is multiplied by 1000, but JWT modules accepts value in seconds, hence JWT expiration time is longer than expected now. Fixing it back to be seconds.
Just merge
No
=> [Reputation Oracle] fix: jwt expiration time

packages/apps/reputation-oracle/server/src/config/auth-config.service.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts
Follow up to https://github.com/humanprotocol/human-protocol/pull/3281
In previous PR, while fixing access token TTL, introduced a bug to refresh token TTL by mistake: it's value is used in ms in code when generated. Fixing it here
Merge
Buggy version was released, so we might want to extend refresh token TTL env var till we release the fix or release it quickly
=> [Reputation Oracle] fix: refresh token expiration

packages/apps/reputation-oracle/server/src/modules/reputation/fixtures.ts, packages/apps/reputation-oracle/server/src/modules/reputation/reputation.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/reputation/reputation.service.ts
Part of #3084 
In previous refactoring PR usage of `increment` and `decrement` repository operations was introduced, but these operations do not update `updated_at` column. Taking into account that we want to keep it updated, change the implementation back to the `updateOne`.
This implementation has a gap for concurrent executions: increment/decrement is not atomic and can lead to lost updates. We accept this risk for now.
Together with main PR.
No.
=> [Reputation Oracle] refactor: replace increment operation for reputation

packages/apps/human-app/frontend/src/modules/homepage/views/home.page.tsx, packages/apps/human-app/frontend/src/modules/worker/jobs-discovery/components/oracles-table-item-mobile.tsx, packages/apps/human-app/frontend/src/modules/worker/jobs/available-jobs/available-jobs-filter-modal.tsx, packages/apps/human-app/frontend/src/modules/worker/jobs/my-jobs/components/desktop/status-chip.tsx, packages/apps/human-app/frontend/src/modules/worker/jobs/my-jobs/components/mobile/my-jobs-filter-modal.tsx, packages/apps/human-app/frontend/src/modules/worker/jobs/my-jobs/components/mobile/my-jobs-list-mobile.tsx, packages/apps/human-app/frontend/src/router/components/layout/protected/navbar.tsx, packages/apps/human-app/frontend/src/shared/components/ui/chip.tsx, packages/apps/human-app/frontend/src/shared/styles/dark-color-palette.ts, packages/apps/human-app/frontend/src/shared/styles/dark-theme.ts, packages/apps/human-app/frontend/src/shared/styles/theme.ts
HUM-177
- fixed naming of white color pallete
- tested components on desktop and mobile if they look correctly
normal
n/a
=> [HUM-177]: fix: fix color pallete naming, adjust usage

packages/apps/human-app/server/src/integrations/reputation-oracle/reputation-oracle.gateway.ts, packages/apps/human-app/server/src/modules/user-operator/model/operator-signin.model.ts, packages/apps/human-app/server/src/modules/user-operator/operator.controller.ts
N/A
Some time ago `/auth/web3/signup` was changed to correspond to `void` return type, but actually it returned auth tokens for operators. This broke sign up flow for operator on UI, so changing it back here and fixing types to correspond to reality.
Just merge
No
=> [HUMAN App] fix: operator signup endpoint

.github/workflows/ci-dependency-review.yaml, packages/apps/reputation-oracle/server/src/common/errors/manifest.ts, packages/apps/reputation-oracle/server/src/common/filters/exception.filter.ts, packages/apps/reputation-oracle/server/src/database/base.repository.ts, packages/apps/reputation-oracle/server/src/database/errors.ts, packages/apps/reputation-oracle/server/src/database/index.ts, packages/apps/reputation-oracle/server/src/modules/abuse/abuse.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/abuse/abuse.service.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts, packages/apps/reputation-oracle/server/src/modules/auth/types.ts, packages/apps/reputation-oracle/server/src/modules/escrow-completion/escrow-completion.service.ts, packages/apps/reputation-oracle/server/src/modules/kyc/kyc.service.ts, packages/apps/reputation-oracle/server/src/modules/kyc/types.ts, packages/apps/reputation-oracle/server/src/modules/qualification/qualification.service.ts, packages/apps/reputation-oracle/server/src/modules/qualification/types.ts, packages/apps/reputation-oracle/server/src/modules/reputation/reputation.repository.ts, packages/apps/reputation-oracle/server/src/modules/reputation/reputation.service.ts, packages/apps/reputation-oracle/server/src/modules/reputation/types.ts, packages/apps/reputation-oracle/server/src/modules/web3/index.ts, packages/apps/reputation-oracle/server/src/modules/web3/types.ts, packages/apps/reputation-oracle/server/src/modules/web3/web3.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/web3/web3.service.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook-incoming.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/webhook/webhook-incoming.service.ts
Part of #3084
Moving some types to separate `types.ts` in order to have smaller `service` (and similar) files and improve their readability. This should be general approach for `service` file and types that are shared within or outside the module. However, if it's a type that declared just to improve readability but can be inline (e.g. `EscrowFinalResultsDetails`), no need to move it.
Just merge
No
=> [Reputation Oracle] refactor: move some types to separate files

.github/workflows/ci-lint.yaml, .github/workflows/ci-test-core.yaml, .github/workflows/ci-test-dashboard.yaml, .github/workflows/ci-test-faucet-server.yaml, .github/workflows/ci-test-fortune.yaml, .github/workflows/ci-test-human-app.yaml, .github/workflows/ci-test-job-launcher.yaml, .github/workflows/ci-test-node-sdk.yaml, .github/workflows/ci-test-python-sdk.yaml, .github/workflows/ci-test-reputation-oracle.yaml, .github/workflows/ci-test-subgraph.yaml
N/A
[Recently changed triggers for actions](https://github.com/humanprotocol/human-protocol/pull/3316), it led to actions run twice when there is a PR opened to `main` branch and you merge a PR to `develop`.
The main difference between `pull_request` and `push` triggers is that `push` runs on the actual commits history from branch/ref, but `pull_request` runs on "merge commit". In case we change it to always be `push` - in PRs it will run on exact commit history only, removing duplicates. It should be fine because after we do actual merge we will run on `develop`/`main` as on `push` trigger to see if it's all good.
Just merge
No
=> refactor: change ci actions to run on push

packages/apps/reputation-oracle/server/src/common/enums/hcaptcha.ts, packages/apps/reputation-oracle/server/src/common/enums/index.ts, packages/apps/reputation-oracle/server/src/common/types/request.ts, packages/apps/reputation-oracle/server/src/modules/abuse/abuse.controller.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.controller.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.service.ts, packages/apps/reputation-oracle/server/src/modules/auth/jwt-http-strategy.ts, packages/apps/reputation-oracle/server/src/modules/kyc/kyc.controller.ts, packages/apps/reputation-oracle/server/src/modules/kyc/kyc.repository.ts, packages/apps/reputation-oracle/server/src/modules/kyc/kyc.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/kyc/kyc.service.ts, packages/apps/reputation-oracle/server/src/modules/nda/nda.controller.ts, packages/apps/reputation-oracle/server/src/modules/nda/nda.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/nda/nda.service.ts, packages/apps/reputation-oracle/server/src/modules/user/index.ts, packages/apps/reputation-oracle/server/src/modules/user/user.controller.ts, packages/apps/reputation-oracle/server/src/modules/user/user.error.ts, packages/apps/reputation-oracle/server/src/modules/user/user.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/user/user.service.ts
Part of #2803 
Removed user fetching from JwtHttpStrategy. `userId` is being passed instead and handled by services accordingly
N/A
Just in case, need to monitor affected endpoints
=> [Reputation Oracle] Remove fetching user from a db in a guard

packages/apps/fortune/exchange-oracle/server/package.json, yarn.lock
Follow up to https://github.com/humanprotocol/human-protocol/pull/3324
Fortune ExcO fails to start (but builds 😬 ) due to missing dependency which is not linked by `yarn` and can't be loaded. Just installed same version as for other services.
Together with main PR
As in base PR
=> [Fortune] fix: missing dep for fortune

packages/apps/reputation-oracle/server/src/database/migrations/1747301407259-AddDbTtlCronJob.ts, packages/apps/reputation-oracle/server/src/modules/auth/auth.module.ts, packages/apps/reputation-oracle/server/src/modules/auth/index.ts, packages/apps/reputation-oracle/server/src/modules/auth/token.repository.ts, packages/apps/reputation-oracle/server/src/modules/cron-job/constants.ts, packages/apps/reputation-oracle/server/src/modules/cron-job/cron-job.module.ts, packages/apps/reputation-oracle/server/src/modules/cron-job/cron-job.service.spec.ts, packages/apps/reputation-oracle/server/src/modules/cron-job/cron-job.service.ts
Part of #2803
PG doesn't support TTL functionality in a native way, so we considered next options:
1) use `pg_cron` (or similar extension) to run scheduled removals
2) writing DB triggers
3) partition data and drop partitions
4) use cron in app to delete records
2 & 3 are over-engineering atm and `pg_cron` can't be installed on our instance unfortunately, so we ended up to nubmer 4.
It's expected to have single cron job to delete expired entities from all necessary tables, so this is why `deleteExpiredDatabaseRecords` has it's own unit tests block.
Just merge
When releasing this feature it might introduce some load on DB because will run for the first time, but taking into account we don't have too much items - should be fine.
=> [Reputation Oracle] feat: add db ttl cron job

packages/apps/reputation-oracle/server/src/modules/qualification/qualification.service.spec.ts, packages/apps/reputation-oracle/server/test/fixtures/date.ts
N/A
Flaky test discovered - [ref](https://github.com/humanprotocol/human-protocol/actions/runs/15043070119/job/42279116757?pr=3338).
Faker's `future` date utils generates a date in a "range" you provide and can be even "later today", but for expiration we need "from some point in the future".
Just merge
N/A
=> [Reputation Oracle] fix: flaky test

packages/examples/cvat/exchange-oracle/src/handlers/job_creation.py
Depends on #3356
During the GT preparation for a `skeletons_from_boxes` task, GT skeletons and input RoI boxes are matched between each other so that only unambiguous GT is used for validation. After #3356, we can detect and allow more unambiguous cases, as now annotators have a marker on the requested object. The default ambiguity checks are still needed, but they still can be too cautious, so it can be desired by the requester to customize this matching.
- Relaxed default object matching by checking that the RoI marker point resolves an ambiguous skeleton - RoI bbox match
- Added support for the `object_id` annotation attribute. This can be used to forcefully match skeletons and boxes that otherwise would be skipped by the ambiguity detection algorithm
=> [Dependent] [CVAT] Relax filtering for overlapping gt skeletons

packages/examples/cvat/exchange-oracle/src/core/tasks/skeletons_from_boxes.py, packages/examples/cvat/exchange-oracle/src/handlers/job_creation.py, packages/examples/cvat/exchange-oracle/src/utils/annotations.py
In skeleton annotation tasks, it can be difficult or even impossible to annotate the correct object, if there are several objects inside a RoI. This PR allows EO to put a point marker along with object bbox in the RoI images. Points have to be passed in the `boxes` field of the manifest, they are required.
=> [CVAT] Draw roi point along with bbox in skeleton tasks

packages/apps/job-launcher/server/package.json, packages/apps/reputation-oracle/server/package.json, packages/core/contracts/Escrow.sol, packages/core/package.json, packages/core/test/Escrow-USDT.ts, packages/core/test/Escrow.ts
NA
- In some escrows balance and remainingFunds is missmatching. It was due to decimals being truncated when oracle fees are calculated. With this fix truncated amount is paid to workers.
- Tests improvements.
- Document the contract with comments.
- Use faker library at full monorepo level.
With unit tests
Upgrade escrow factory contracts
- Possible issues upgrading the contracts
=> Fix escrow payouts

packages/apps/job-launcher/server/src/common/validators/token-decimals.ts
N/A
Refactor token validation to use PaymentCurrency enum and add support for USD decimal checks
Tested locally 
None
Check if fiat payments can be created
=> [Job Launcher] Check USD decimals

packages/apps/reputation-oracle/server/src/modules/escrow-completion/escrow-completion.service.ts
Freestyle
Changed the way of how we retrieve instances of escrow processors. Before we directly injected them to main class, but in order to simplify that and improve readability use `moduleRef` container from Nest directly now.
Just merge
Don't see any
=> [Reputation Oracle] refactor: use module ref for factory method

packages/apps/dashboard/client/src/components/SearchResults/AbbreviateClipboard.tsx, packages/apps/dashboard/client/src/pages/SearchResults/WalletAddress/WalletAddressTransactions/cells/TransactionTableCellMethod.tsx, packages/apps/dashboard/client/src/pages/SearchResults/WalletAddress/WalletAddressTransactions/cells/TransactionTableCellValue.tsx, packages/apps/dashboard/client/src/pages/SearchResults/WalletAddress/WalletAddressTransactions/tableComponents/TransactionsTableBody.tsx, packages/apps/dashboard/client/src/pages/SearchResults/WalletAddress/WalletAddressTransactions/tableComponents/TransactionsTableHead.tsx
Closes #3369 
This PR adds a tooltip in to the Value cell in transactions table head and body, if method is `approve`
only locally;
go to http://localhost:3004/search/80002/0x4708354213453af0cdC33eb75d94fBC00045841E, scroll down until transactions table and then paginate to page 9
regular plan
=> [Dashboard] Approve transaction does not transfer funds

packages/sdk/python/human-protocol-sdk/human_protocol_sdk/constants.py, packages/sdk/typescript/human-protocol-sdk/src/constants.ts, packages/sdk/typescript/subgraph/src/mapping/EscrowTemplate.ts, packages/sdk/typescript/subgraph/tests/escrow/escrow.test.ts, packages/sdk/typescript/subgraph/tests/escrow/fixtures.ts
#3401
Improve handleCompleted to create InternalTransaction and reset escrow balance when transferring funds on completion.
Created new tests for it and ran it
Deploy new subgraph version
Check if escrow balance is 0 when calling complete and the escrow is not totally paid
=> [Subgraph] Wrong balance

.github/workflows/cd-core.yaml, .github/workflows/cd-node-sdk.yaml
No
Recently change CI to use `yarn` to publish packages, it appeared that it need its own env var name which is different from NPM in order to auth in npm registry.
-
Merge & trigger workflow
No
=> fix: use yarn env var for npm auth token

.github/workflows/cd-core.yaml, .github/workflows/cd-node-sdk.yaml, packages/sdk/typescript/human-protocol-sdk/package.json, yarn.lock
Counterpart of https://github.com/humanprotocol/human-protocol/pull/3419 & https://github.com/humanprotocol/human-protocol/pull/3422 for develop branch
=> fix: sdk cd

packages/apps/human-app/server/src/modules/oracle-discovery/oracle-discovery.controller.ts
Related to #3407
Follow up to https://github.com/humanprotocol/human-protocol/pull/3408: return all oracles in non-prd env for simplicity.
--
Just merge
No
=> [HUMAN App] feat: return all oracles for non prd

packages/apps/human-app/frontend/src/modules/governance-banner/hooks/use-active-proposal-query.ts
NA
Change the block number from which the governance logs are fetch to avoid timeouts.
Since the blocktime in polygon is 2s, voting delay is 1 day (86400s) and the duration of proposals is1 day (86400s), we won't need 
more than 86400/2+86400/2= 86400 blocks and we rounded it 100k.
Run locally
NA
NA
=> update block number calculation for query filter

packages/examples/cvat/exchange-oracle/src/core/tasks/boxes_from_points.py, packages/examples/cvat/exchange-oracle/src/core/tasks/roi_based.py, packages/examples/cvat/exchange-oracle/src/core/tasks/skeletons_from_boxes.py, packages/examples/cvat/exchange-oracle/src/handlers/job_export.py, packages/examples/cvat/recording-oracle/src/core/config.py, packages/examples/cvat/recording-oracle/src/handlers/process_intermediate_results.py
- \[RO\] Added an option to disable GT bans
- \[EO\] Resulting annotations will now include RoI ids in RoI-based task types (`skeletons_from_boxes`, `boxes_from_points`)
Set `ENABLE_GT_BANS=0` for recording oracle production.
=> [CVAT] Updates

packages/sdk/typescript/subgraph/src/mapping/utils/transaction.ts
#3421 
When receiving multiple events in one transaction, transaction from value was not showing the right value. This was due to it was setting the one from the first event that subgraph receives. In order to show it properly, we have to set the right from value when transaction is mainMethod, overwriting  the value from the first event.
Ran tests
Deploy new SDK version
None
=> [Subgraph] Wrong information in transaction data

packages/apps/faucet/server/src/index.ts
None
Express was using the server's IP for all requests, causing everyone to be blocked by the rate limit as if they shared the same IP.
It was fixed by setting app.set('trust proxy', 1), so Express now correctly uses the real client IP for rate limiting
Deployed and made some requests to confirm it's working
Deploy Faucet server
None
=> [Faucet] Improve IP handling

packages/apps/human-app/frontend/src/modules/worker/services/oracles.service.ts
Closes #2804
Atm UI has functionality to filter UI job by chain & also we do not expect that in our version of protocol there might be oracle with different setup in different chains, instead we run same oracle in different chains (atm only on testnets). So it is fine to just remove duplicates from UI and filter jobs by chain_id later.
Just merge
No
=> [HUMAN App] feat: avoid same oracle displaying in oracle discovery

packages/examples/cvat/exchange-oracle/src/handlers/job_creation.py
- Fixed a possible error in annotation uploading for a CVAT GT job if there are empty GT frames during task creation
=> [CVAT] Fix empty GT frames in point annotation task

packages/apps/job-launcher/server/src/main.ts
None
Change application type to NestExpressApplication and set trust proxy.
Since we're using cloudflare and render, requests are going through 2 different proxies, so rate limits were not being applied.
Launched 4 different requests till I receive `Too many requests` error
None
None
=> [Job Launcher] Fix rate limit

packages/apps/job-launcher/server/src/common/exceptions/exception.filter.ts
Follow up to https://github.com/humanprotocol/human-protocol/pull/3497
JL in case of errors doesn't handle status code properly, which leads to wrong status code and exception logging.
Just merge
No
=> [Job Launcher] fix: do not log non-5xx errors

packages/apps/reputation-oracle/server/src/common/validators/index.ts, packages/apps/reputation-oracle/server/src/modules/auth/dto/password.dto.ts, packages/apps/reputation-oracle/server/src/modules/auth/dto/sign-in.dto.ts, packages/apps/reputation-oracle/server/src/modules/auth/dto/sign-up.dto.ts, packages/apps/reputation-oracle/server/src/modules/user/user.controller.ts, packages/apps/reputation-oracle/server/src/modules/user/user.dto.ts
N/A
Token can be sent as any string, which leads to querying DB with weird values in case if somebody tries to send them and it ends up in unhandled exception. To address it - added uuid format validation.
Also tightened password validation.
> [!NOTE]
> Interesting finding while testing: `class-validator` uses `validator` library under the hood and it validates uuid not just for "uuid-like" string (it can be achieved with `loose` version param), but for actual value, so `hCaptchaToken` that is used for development is invalid because it doesn't correspond to RFC of uuid.
Just merge
No
=> [Reputation Oracle] feat: validate restore password token as uuid

packages/apps/human-app/frontend/src/modules/smart-contracts/EthKVStore/config.ts, packages/apps/human-app/frontend/src/shared/i18n/en.json, packages/apps/reputation-oracle/server/src/common/enums/manifest.ts
=> Release 2025-09-XX

.changeset/grumpy-hotels-help.md, .changeset/metal-fans-lay.md, .changeset/petite-comics-float.md, .changeset/plenty-melons-fetch.md, packages/core/package.json, packages/libs/logger/package.json, packages/sdk/typescript/human-protocol-sdk/package.json
N/A
Used `yarn changeset version` to bump packages for upcoming release
Merge. Publish packages via new GitHub action
As mentioned in [parent PR](https://github.com/humanprotocol/human-protocol/pull/3539)
=> chore: bump changed packages version

packages/examples/cvat/exchange-oracle/src/endpoints/authentication.py, packages/examples/cvat/exchange-oracle/src/endpoints/exchange.py, packages/examples/cvat/exchange-oracle/src/services/cvat.py, packages/examples/cvat/exchange-oracle/src/services/exchange.py, packages/examples/cvat/exchange-oracle/tests/api/test_exchange_api.py, packages/examples/cvat/exchange-oracle/tests/integration/services/test_exchange.py, packages/examples/cvat/exchange-oracle/tests/utils/manifest.json
To close #3564 
Added qualification validation for `POST /assignment`
N/A
N/A
=> [CVAT] Add qualification validation for `POST /assignment`

packages/examples/cvat/exchange-oracle/debug.py, packages/examples/cvat/exchange-oracle/src/crons/cvat/state_trackers.py, packages/examples/cvat/exchange-oracle/src/db/__init__.py, packages/examples/cvat/recording-oracle/debug.py
It's ok for the locks to be unavailable in CVAT state trackers. The code that was supposed to ignore such errors was a little bit incorrect.
=> [CVAT] Reduce logs about failed lock acquisitions

packages/apps/dashboard/server/src/modules/details/dto/validation/role-validation.ts, packages/apps/fortune/exchange-oracle/server/src/common/errors/index.ts, packages/apps/fortune/exchange-oracle/server/src/common/exceptions/exception.filter.ts, packages/apps/fortune/exchange-oracle/server/src/common/interceptors/snake-case.ts, packages/apps/fortune/exchange-oracle/server/src/common/pipes/validation.ts, packages/apps/fortune/exchange-oracle/server/src/common/utils/case-converter.spec.ts, packages/apps/fortune/exchange-oracle/server/src/common/utils/case-converter.ts, packages/apps/fortune/exchange-oracle/server/src/modules/webhook/webhook.service.ts, packages/apps/fortune/recording-oracle/src/common/errors/index.ts, packages/apps/fortune/recording-oracle/src/common/exceptions/exception.filter.ts, packages/apps/fortune/recording-oracle/src/common/interceptors/snake-case.ts, packages/apps/fortune/recording-oracle/src/common/pipes/validation.ts, packages/apps/fortune/recording-oracle/src/common/utils/case-converter.spec.ts, packages/apps/fortune/recording-oracle/src/common/utils/case-converter.ts, packages/apps/fortune/recording-oracle/src/common/utils/webhook.ts, packages/apps/job-launcher/server/src/common/errors/index.ts, packages/apps/job-launcher/server/src/common/exceptions/exception.filter.ts, packages/apps/job-launcher/server/src/common/interceptors/snake-case.ts, packages/apps/job-launcher/server/src/common/pipes/validation.ts, packages/apps/job-launcher/server/src/common/utils/case-converter.spec.ts, packages/apps/job-launcher/server/src/common/utils/case-converter.ts, packages/apps/job-launcher/server/src/modules/auth/auth.dto.ts, packages/apps/job-launcher/server/src/modules/job/job.dto.ts, packages/apps/job-launcher/server/src/modules/webhook/webhook.service.ts, packages/apps/reputation-oracle/server/src/common/pipes/validation.ts, packages/apps/reputation-oracle/server/src/common/validators/index.ts, packages/apps/reputation-oracle/server/src/integrations/hcaptcha/hcaptcha.guard.spec.ts, packages/apps/reputation-oracle/server/src/integrations/hcaptcha/hcaptcha.guard.ts, packages/apps/reputation-oracle/server/src/modules/user/user.dto.ts, packages/apps/reputation-oracle/server/src/utils/case-converters.ts
Close #3381
- Refactor validation error handling to include detailed error messages for all oracles 
- Improve class validation response structure for JL, Exchange Oracle and Reputation Oracle
Deployed locally and made some calls to make sure all error messages are in snake_case
Deploy again all services
None
=> Invalid property name in API validation messages

.changeset/stale-glasses-slide.md, packages/sdk/typescript/human-protocol-sdk/src/escrow.ts, packages/sdk/typescript/human-protocol-sdk/test/escrow.test.ts
None
Fix EscrowUtils.getEscrow to include chainId in the returned object
Ran unit tests and launched examples locally
Deploy new SDK version
None
=> [SDK][Typescript] Add chainId into getEscrow returned object

.gitbook.yaml, .github/workflows/cd-gitbook-sdk-docs.yaml, docs/sdk/README.md, docs/sdk/SUMMARY.md, scripts/gitbook-sync-sdk.mjs
Close #3483
- Add GitHub Actions workflow 
- Add script for publishing SDK documentation to GitBook
- Unify the first page of documents
Launched several times via act 
Add some github secrets:
`GITBOOK_API_TOKEN=
GITBOOK_ORG_ID=
GITBOOK_PARENT_SPACE_ID=
GITBOOK_SITE_ID=
MAKE_DEFAULT=true`
None
=> [SDK] publish docs to GitBook
